### ISSUE TITLE
Problem converting pdf to txt with pdf2txt.py

### ISSUE THREAD

**Issue by ganeshtata** [pdfminer/pdfminer.six#100]
Can someone look into this issue - https://github.com/euske/pdfminer/issues/104  ? I have submitted a pull request to the same repositary - https://github.com/euske/pdfminer/pull/190 .

**Comment by ganeshtata** [comment]
A fork of this repository has been created at - https://github.com/strideai/pdfminer.six . This issue has been fixed in this fork, and we will now be maintaining the forked repository.

**Comment by goulu** [comment]
Hi @ganeshtata ,
since you're willing to help, I invited you to the group that is supposed to maintain this fork.
If you have an account on Pypi, I'll add you as a maintainer there so you can upload new versions.
I think it's better not to multiply forks ...

**Comment by ganeshtata** [comment]
Hi @goulu ,
I have accepted your invitation to join the group, and will help in maintaining this fork. I have also created a Pypi account with username - # tataganesh.

**Comment by goulu** [comment]
Nice @ganeshtata . I added you as owner on https://pypi.python.org/pypi?:action=role_form&package_name=pdfminer.six 
Welcome aboard !

**Comment by ganeshtata** [comment]
@goulu  Thank you!

**Comment by ganeshtata** [comment]
This issue has been fixed in this commit -  chttps://github.com/pdfminer/pdfminer.six/commit/1b88575e79fb5a8a77243fa1c227da9366707d40
