### ISSUE TITLE
no module named 'pdfminer.settings'

### ISSUE THREAD

**Issue by WtfJoke** [pdfminer/pdfminer.six#102]
I use python 3.6.3 and a virtualenv.

```
(env) F:\dev\git\pdfminer.six>pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
chardet (3.0.4)
pdfminer.six (20170720)
pip (9.0.1)
pycryptodome (3.4.7)
setuptools (36.6.0)
six (1.11.0)
wheel (0.30.0)
```

When I try to run following command I get the exception:
```
(env) F:\dev\git\pdfminer.six>pdf2txt.py samples/simple1.pdf
Traceback (most recent call last):
  File "F:\dev\git\pdfminer.six\env\Scripts\pdf2txt.py", line 9, in <module>
    import pdfminer.settings
ImportError: No module named pdfminer.settings
```

Does anybody knows why? Other issues I found like #52 said should avoid conflicts with original pdfminer. But I dont have any conflict...

**Comment by oct15demo** [comment]
Me too.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/pdf2txt.py", line 9, in <module>
    import pdfminer.settings
ImportError: No module named pdfminer.settings

Yet I'm able to import both pdfminer and pdfminer settings inside Eclipse or interactively 
>>> import pdfminer.settings
>>>

**Comment by paulovitorjp** [comment]
@WtfJoke I see you are using windows. You should be calling pdf2text.py with a 'python' before. e.g.:
`python PATH_TO_PYTHON_SCRIPTS\pdf2text.py`
By calling pdf2text.py directly windows will try to open it with the configured default program, which might be python 2.7 or something else you may have configured before.
But even if you configure it to be opened by python3 it will not pass the args forward if you call it directly, so always call a "*.py" script with "python" preceding it in windows.

**Comment by WtfJoke** [comment]
Thanks @paulovitorjp this actually worked. Didnt thought it make any difference.

For future reference:
`
(myenv) F:\dev\git\pdfminer.six>python myenv\Scripts\pdf2txt.py samples\simple1.pdf`
