### ISSUE TITLE
ImportError: cannot import name 'format_int_alpha' from 'pdfminer.utils' 

### ISSUE THREAD

**Issue by jatinchhabriya** [pdfminer/pdfminer.six#1022]
While importing camelot-py internally uses pdfminer.six and there is the following error:

**ImportError: cannot import name 'format_int_alpha' from 'pdfminer.utils' (/databricks/python/lib/python3.8/site-packages/pdfminer/utils.py)**

Please include this bug in the feature release and try to make the import of this PyPi successful.

**Comment by pietermarsman** [comment]
Cannot reproduce. 

The [format_int_alpha](https://github.com/pdfminer/pdfminer.six/blame/1a8bd2f730295b31d6165e4d95fcb5a03793c978/pdfminer/utils.py#L806) function has not changed in the last 2 years. 

Also this works with the latest version. 

```
python 
Python 3.10.0 (default, Mar 15 2023, 16:24:21) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pdfminer.utils import format_int_alpha
>>>
```

Perhaps you have pdfminer and pdfminer.six installed on your system?
