### ISSUE TITLE
Currently, the "text that should start with tab" and the "general sentence" are executed as .txt file without any distinction.

### ISSUE THREAD

**Issue by yeonsuyam** [pdfminer/pdfminer.six#103]
Is there any way to separate sentences that begin with tabs in the ".txt" file with "space"?

**Comment by ganeshtata** [comment]
@yeonsuyam Can you please elaborate more on the issue? A brief description can help someone to understand the issue better, and find a possible solution.

**Comment by yeonsuyam** [comment]
What I want to do with this program is, to extract the headwords from the words in the index part of the major book. In the book, headwords and others are separated by indentation. (Book is .pdf file)

ex) Book.pdf file's example
Abdomen, insect, 704f          <-- headword
Abiotic factors, 1163              <-- headword
    microclimate and, 1163      <-- not headword
    in pollination, 820f             <-- not headword

But when I change it to the .txt file, It comes like
Abdomen, insect, 704f          <-- headword
Abiotic factors, 1163              <-- headword
microclimate and, 1163      <-- not headword
in pollination, 820f

So I cannot recognize what is headword, and what is not headword.
I would like to separate the words through indentation in the .txt file too.

**Comment by ganeshtata** [comment]
@yeonsuyam If you want to preserve the "indentation" ( by this I think you mean the structure ), you should not use the text file, but rather, use pdfminer's layout analyzer to find lines and their corresponding bboxes. If each line has the bbox [x1, y1, x2, y2], where x1 indicates the distance of the first letter of the line from the left margin, you can use x1 to differentiate between your headword, and other words.
