### ISSUE TITLE
pdf2txt.py HTML output has bad formatting

### ISSUE THREAD

**Issue by f-t-alves** [pdfminer/pdfminer.six#1038]
I've tried out a few of the PDFs found in the `samples` directory and most had pretty bad formatting. Is this a known limitation or did something go horribly wrong somewhere? For example, trying out `samples/font-size-test.pdf` with all three layout modes produced overlapping characters, with varying degrees of wonkiness when trying to interactively highlight the text.

To reproduce, run `pdf2txt.py -o test.html font-size-test.pdf`, then open the HTML in a browser of your choice.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by KaboChow** [comment]
> to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html) maybe this will solve your problem.

This is a malicious link. Do not click it. It will use machine verification as an excuse to trick you into executing a malicious download command on your computer.

If you have already executed it, you can follow these steps:
1.Disconnect from the internet.
2.Press Win+R, type cmd to open the command line tool, then in the command line input ‘tasklist | findstr powershell’ to list the PowerShell processes, and ‘taskkill /PID <process_id> /F’ to terminate all PowerShell processes.
