### ISSUE TITLE
PyPI package published with CRLF

### ISSUE THREAD

**Issue by ishitatsuyuki** [pdfminer/pdfminer.six#104]
Probably you ran publishing on Windows, and it resulted in broken shebangs.

```
/usr/bin/env: ‘python\r’: No such file or directory
```

**Comment by oct15demo** [comment]
If you get this
env: python\r: No such file or directory
In vi open pdf2txt.py and do this
:set ff=unix
As told here:
https://stackoverflow.com/questions/19425857/env-python-r-no-such-file-or-directory

**Comment by ishitatsuyuki** [comment]
Sure, there's many way to convert the line format, and even without that running with `python =pdf2txt.py` works because it bypasses shebang. The issue is that the pip package is bad.

**Comment by kerrickstaley** [comment]
+1 please fix the package on PIP, it should not use CRLF line endings. The package is unusable on macOS and Linux because of this issue.

**Comment by ganeshtata** [comment]
@kerrickstaley Can you please tell me how should I go about doing it? I am an admin of this project, but I am unaware of a lot of specifics.

**Comment by ishitatsuyuki** [comment]
@ganeshtata please publish the package again on a non-Windows OS.

**Comment by drunkwcodes** [comment]
@ganeshtata 
Or saving those files with line-ending aware editors, such as Notepad++, Sublime Text editor,  Atom etc.

**Comment by pietermarsman** [comment]
This is a duplicate of #27. Also, the issue is fixed.

This can be closed.
