### ISSUE TITLE
pdfdocument.py fallback

### ISSUE THREAD

**Issue by cole-dda** [pdfminer/pdfminer.six#108]
pdfdocument.py on  582 line,  why comment fallback=True  and use pass ?  when pass argument fallback=False, if has error,always skip fallback

**Comment by ganeshtata** [comment]
@cole-dda  Can you elaborate a little more on this issue?

**Comment by pietermarsman** [comment]
I'm closing this because I think the code is correct:

- If there is an xref, no exception is thrown
- If there is no xref
    - and `fallback` is false, raise a PDFSyntaxError
    - and `fallback` is `true`, use `PDFXRefFallback`
