### ISSUE TITLE
psparser bug

### ISSUE THREAD

**Issue by cole-dda** [pdfminer/pdfminer.six#109]
psparser.py 
    
    def _parse_comment(self, s, i):
        m = EOL.search(s, i)
        if not m:
            self._curtoken += bytesindex(s,i,-1)
            return (self._parse_comment, len(s))
        j = m.start(0)
        self._curtoken += bytesindex(s,i,j)
        self._parse1 = self._parse_main
        # We ignore comments.
        #self._tokens.append(self._curtoken)
        return j

============
should return len(s),but return (self._parse_comment,len(s))

**Comment by ganeshtata** [comment]
Hi. Can you elaborate more on this issue? And if you are sure about a particular fix, you can send a pull request.

**Comment by cole-dda** [comment]
the bug is return difference args number, one or two

**Comment by pietermarsman** [comment]
Fixed by https://github.com/pdfminer/pdfminer.six/pull/134
