### ISSUE TITLE
It generates multiple LTTextLineHorizontal on single level instead of a single one

### ISSUE THREAD

**Issue by KOLANICH** [pdfminer/pdfminer.six#110]
It often generates multiple `LTTextLineHorizontal`s instead of a single one. I guess it is because of hardcoded `word_margin`. I guess we need to find it adaptively rather than use hardcoded one.

I have tried `sklearn.cluster.dbscan` on characters centers and it gives nice results. I guess it's better to use bounding boxes to measure distances, but I'm not very familiar with sklearn and I don't want to make a dense matrix. But we can define own metrics taking in account bounding boxes.

**Comment by pietermarsman** [comment]
I'm interpreting this issue as: are there ways we can improve the grouping of character objects. 

Currently the `word_margin` takes the width (or height) of the character bounding boxes into account. What other parameters can we use to make its value more dynamic? DBScan takes the local density into account but I'm not sure if that makes sense for characters. 

We could introduce an `word_margin='auto'` value that dynamically sets the `word_margin` for each page.

**Comment by pietermarsman** [comment]
@KOLANICH do you have a pdf that demonstrates this? What issues does this cause in extracting the text? Can you tune (i.e. increase) the `char_margin` to prevent the problem?

**Comment by KOLANICH** [comment]
In fact I have already solved this issue with an another PR (the pdfs were pathological (I have removed embedded fonts from them to make them smaller, so the info pdfminer relies on got lost), so that PR got an approximation of glyphs sizes from an another source and that worked fine).

**Comment by pietermarsman** [comment]
Great!
