### ISSUE TITLE
Extra quotes in PSLiteral.__repr__

### ISSUE THREAD

**Issue by jcushman** [pdfminer/pdfminer.six#12]
The .six fork adds extra quotes to `PSLiteral.__repr__`:

```
ipdb> from pdfminer.psparser import PSLiteral
ipdb> PSLiteral("Name")
/'Name'
```

... where regular pdfminer would just print `/Name`.

This seems to be because of [this line](https://github.com/goulu/pdfminer/blob/master/pdfminer/psparser.py#L98), which switched from using `'/%s'` to  `'/%r'`.

Should be a one-character fix, unless there's some reason using `%r` is important?

(Seems like a minor issue, I know, but pdfquery uses `__repr__` for serializing PDFs, so this becomes a blocker for py3 support.)

Thanks!

**Comment by goulu** [comment]
as mentionned in PSLiteral doc "Note: Do not create an instance of PSLiteral directly. Always use PSLiteralTable.intern()" This seems to take care of the problem you mention. Please reopen with a test case if not
