### ISSUE TITLE
Graphical lines detection

### ISSUE THREAD

**Issue by Thy87** [pdfminer/pdfminer.six#126]
Hello everyone, I hope I am posting in the right place.

I am writing code to parse pdf containing tables
I precise that I don't know how the pdf is produced
and I don't produce it myself

Here is how I build the LTPage objects

    lt_page_list = []
    page_list = PDFPage.create_pages(doc)
    for page in page_list:
        interpreter.process_page(page)
        lt_page_list.append(device.get_result())
    
I have no problem extracting text, what I'd like
to extract is the position of the graphical lines
Those lines are put in LTCurve objects but there's
only horizontal lines (i.e. y0 == y1)

For more info, I attach the result of the following
command line
    pdf2txt.py -t xml -m 1 in.pdf | grep curve > output.txt

[output.txt](https://github.com/pdfminer/pdfminer.six/files/1739828/output.txt)

The curves of the command line output and the LTCurve
objects I get with my code matches

What I'd like to understand is, if there any reason
for pdfminer to produce LTCurves instead of LTLines ?
Should they be interpreted as LTLines ? And why I don't
get vertical lines ?

Thanks for the answers

**Comment by Thy87** [comment]
I have written code to draw the lines I detect in an image
Here the output image
![page0](https://user-images.githubusercontent.com/36447405/36589586-12f280d2-188c-11e8-9496-539c8901f2af.jpeg)
and here is a screenshot of the corresponding page where I erased the text with gimp
![screenshot](https://user-images.githubusercontent.com/36447405/36589692-75478868-188c-11e8-861b-7e7a0bb30895.jpeg)

I interpreted the LTCurve objects as lines
It seems that's right, but still, I can't detect vertical lines and pdf2txt neither.
Unless I am missing something

**Comment by abhishek-27** [comment]
Take a look at this Library, [https://github.com/jsvine/pdfplumber]

This library takes care of detecting lines as well as the table structure.

**Comment by ganeshtata** [comment]
@Thy87 Have you found a solution to this issue? If so, please let me know, so that I can close it. Thanks!

**Comment by Thy87** [comment]
Indeed, the problem was related to the way the pdf was written. You can
close it

Le sam. 9 juin 2018 à 20:23, Tata Ganesh <notifications@github.com> a
écrit :
