### ISSUE TITLE
Wrong image saving

### ISSUE THREAD

**Issue by bashkirtsevich** [pdfminer/pdfminer.six#131]
Strange condition at the `104` line in `image.py` (https://github.com/pdfminer/pdfminer.six/blob/master/pdfminer/image.py#L104).

`image.colorspace` has value:
```
result = {list} <class 'list'>: [/'DeviceRGB']
 0 = {PSLiteral} /'DeviceRGB'
 __len__ = {int} 1
```
But condition checks list with string value and always equals false and instead of saving picture to BMP it save as raw data.

If I change condition to `image.bits == 8 and LITERAL_DEVICE_RGB in image.colorspace` all OK and image will save as `BMP`.

Is this condition wrong? Or this is feature?

![proof](http://s1.micp.ru/a8B19.png)

**Comment by pietermarsman** [comment]
Fixed by #132
