### ISSUE TITLE
Pages repeatedly extracted

### ISSUE THREAD

**Issue by stuartspotlight** [pdfminer/pdfminer.six#146]
When extracting images from a pdf document version 1.4 all the images in the pdf will be extracted for every page.

**Comment by RolandColored** [comment]
Can you tell us how you are extracting the images?

**Comment by stuartspotlight** [comment]
```
from PIL import Image
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfpage import PDFPage


fp = open(pdf_filename, 'rb')
parser = PDFParser(fp)
document = PDFDocument(parser)
pages = []

#extract the pages into a list
for page in PDFPage.create_pages(document):
    pages.append(page)

#cycle through the pages
for page in pages:

    resources = page.resources
    image_resources = resources["XObject"]
    for image in image_resources.keys():

        im_ref = image_resources[image]

        bts = im_ref.resolve().get_data()

        im = Image.open(BytesIO(bts)).convert("RGB")

        #Process the extracted image

```

**Comment by stuartspotlight** [comment]
When I try to process a pdf V1.4 it attaches every image object to every page

**Comment by stuartspotlight** [comment]
For the moment I've hacked around it by using subprocess to call gs to convert to pdf V1.5 which works fine:-
```
    subprocess.call(["gs", "-sDEVICE=pdfwrite", "-dCompatabillityLevel=1.5", "-dNOPAUSE", "-dQUIET", "-dBATCH", "-sOutputFile=%s"%os.path.join(download_folder, 'output.pdf'), os.path.join(download_folder, 'document.pdf')])
```

**Comment by Black-Eyes-SGC** [comment]
how 

> For the moment I've hacked around it by using subprocess to call gs to convert to pdf V1.5 which works fine:-
> 
> ```
>     subprocess.call(["gs", "-sDEVICE=pdfwrite", "-dCompatabillityLevel=1.5", "-dNOPAUSE", "-dQUIET", "-dBATCH", "-sOutputFile=%s"%os.path.join(download_folder, 'output.pdf'), os.path.join(download_folder, 'document.pdf')])
> ```

hi, how can i get the pdf version? Thank you !

**Comment by stuartspotlight** [comment]
@Black-Eyes-SGC I seem to remember the pdf version was set by -dCompatabillityLevel=1.5. You can check the version of the outputted pdf in the properties tab in your file explorer

**Comment by pietermarsman** [comment]
I'm closing this issue because I cannot replicate this. I'm testing this with a PDF-1.4 with multiple pages and pictures: [settles-activelearning.pdf](https://github.com/pdfminer/pdfminer.six/files/3855706/settles-activelearning.pdf)

```python
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfpage import PDFPage


fp = open('/Users/pieter/Downloads/settles-activelearning.pdf', 'rb')
parser = PDFParser(fp)
document = PDFDocument(parser)

for page in PDFPage.create_pages(document):
    resources = page.resources
    if 'XObject' in resources:
        image_resources = resources["XObject"]
        for image in image_resources.keys():
            im_ref = image_resources[image]
            print(im_ref)
```

And the output: 

```text
<PDFObjRef:215>
<PDFObjRef:264>
<PDFObjRef:304>
<PDFObjRef:329>
<PDFObjRef:569>
<PDFObjRef:767>
<PDFObjRef:878>
<PDFObjRef:879>
<PDFObjRef:1016>
```

All the object references are different.
