### ISSUE TITLE
Extract structured data from PDF

### ISSUE THREAD

**Issue by pk-python** [pdfminer/pdfminer.six#148]
**Readme:**
- I am having a PDF attached below, is it possible to get each paragraph as one string  
[drylab.pdf](https://github.com/pdfminer/pdfminer.six/files/2058131/drylab.pdf)

EX: 
```
Welcome to our first newsletter of 2017! It's been a while since the last one, and a lot has
happened. We promise to keep them coming every two months hereafter, and permit
ourselves to make this one rather long. The big news is the beginnings of our launch in
the American market, but there are also interesting updates on sales, development,
mentors and (of course) the investment round that closed in January.
```

**Comment by RolandColored** [comment]
Of course it is. Have a look at the documentation https://media.readthedocs.org/pdf/pdfminer-docs/latest/pdfminer-docs.pdf at point "2.3 Performing Layout Analysis". Objects of type LTTextBox are your paragraphs.

**Comment by pk-python** [comment]
@RolandColored 
- I gone through the documentation and used the piece of code, i captured response in below string
```
Welcome to our first newsletter of 2017! It's
been a while since the last one, and a lot has
happened. We promise to keep them coming
every two months hereafter, and permit
ourselves to make this one rather long. The
big news is the beginnings of our launch in
the American market, but there are also
interesting updates on sales, development,
mentors and (of course) the investment
round that closed in January.
New capital: The investment round was
successful. We raised 2.13 MNOK to match
```

- If i open the above string in linux machine vim editor it is showcasing one paragraph in multiple lines

- But i want one paragraph as one string like below
```
Welcome to our first newsletter of 2017! It's been a while since the last one, and a lot has happened. We promise to keep them coming every two months hereafter, and permit ourselves to make this one rather long. The big news is the beginnings of our launch in the American market, but there are also interesting updates on sales, development, mentors and (of course) the investment round that closed in January. New capital: The investment round was successful. We raised 2.13 MNOK to match
```

- Now is it possible to get like this ?

**Comment by pk-python** [comment]
@RolandColored 
- Yes, exactly i do the same. but if i follow this process for multiple paragraphs data becomes noisy

EX:
- **Before parsing**
```
ram is a good boy,
krish is a bad boy

ravi leaves india by this week end
```
- In the above string their are two paragraphs
```
ram is a good boy,
krish is a bad boy
```
and
```
ravi leaves india by this week end
```
- **After parsing**
```python
 >>> l = '''
... ram is a good boy,
... krish is a bad boy
...
... ravi leaves india by this week end
...
...
... '''
>>> l.replace('\n', ' ')
' ram is a good boy, krish is a bad boy  ravi leaves india by this week end   '
>>>
```
- If i do parsing based on `\n`, multiple paragraphs becomes single paragraph(**noisy data**) 
- Can you help me here ? Any suggestions ?

**Comment by RolandColored** [comment]
If the LTTextBox objects contain more than one paragraph in your opinion, then the layout analysis of pdfminer gone wrong in the first place.
To fix this have a look at the constructor of `LAParams`. You can play around with the parameters to achieve the arrangement of TextBoxes you desire. Consult chapter 1.3.1 for nice documentation. Maybe lowering line_margin could help in your case.

**Comment by RolandColored** [comment]
And if this doesn't help you can still split the paragraphs on multiple `\n\n` before cleaning them away.

**Comment by ganeshtata** [comment]
@pk-python Closing the issue because it seems to be resolved. @RolandColored Thank you for your help!

**Comment by ramakth1** [comment]
do you have code
