### ISSUE TITLE
Use a more universal line ending

### ISSUE THREAD

**Issue by charlesreid1** [pdfminer/pdfminer.six#149]
After successfully running `pip install pdf2txt.six` I see the following error when I run the program on the sample:

```
$ pdf2txt.six sample.pdf
env: python\r: No such file or directory
```

This is caused by the file being saved in Windows. Please replace `\r\n` with `\n` as it is more universal.

**Comment by charlesreid1** [comment]
Related issue that gives a temporary workaround: #145

Discussion in this thread is about a permanent fix.

**Comment by RolandColored** [comment]
Looks like a good idea. Can you open a pull request for this?

**Comment by charlesreid1** [comment]
See #160

**Comment by pietermarsman** [comment]
Duplicate of #27
