### ISSUE TITLE
image.py: TypeError: object of type 'zip' has no len() in Python 3.5.1

### ISSUE THREAD

**Issue by robo3945** [pdfminer/pdfminer.six#15]
Extracting text with images there is an error "TypeError: object of type 'zip' has no len()
". 

"File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pdfminer/image.py", line 74, in export_image
    if len(filters) == 1 and filters[0][0] in LITERALS_DCT_DECODE:
TypeError: object of type 'zip' has no len()"

I converted also a PDF file "i1040nr.pdf" in your test set and there is the same error.

**Comment by goulu** [comment]
solved in commit https://github.com/pdfminer/pdfminer.six/commit/9b9d69aee96f0e7a35f5b48c6c80f450e629ccd6 

sorry for the one year delay ...
