### ISSUE TITLE
Release Master to Pip?

### ISSUE THREAD

**Issue by jeremyschiff** [pdfminer/pdfminer.six#151]
Great work on this project!  Is it possible you could push a new version of master to pip?  It would be much more convenient than adding from source every time.

Pip is almost a year out of date:
https://pypi.org/project/pdfminer.six/

Thanks!

**Comment by RolandColored** [comment]
There are a lot of fixes and improvements which we are looking forward too. Just like Barney Stinson said: "New is always better". Personally I am looking into the speed improvements, but the PRs are not yet merged.
If you need any help, just let me know.

**Comment by pquentin** [comment]
@goulu do you think you could help here?

**Comment by tataganesh95** [comment]
@RolandColored  I have been trying to review the PRs, but sadly haven't got much time to do that. If each of the PRs ( particularly #142 and #133 ) have been well tested, I have no problems merging them. Before we release master to pip, we could do some final sanity checks. I, too, want all these improvements to be made available to all users.

**Comment by ganeshtata** [comment]
@RolandColored I have been trying to review the PRs, but sadly haven't got much time to do that. If each of the PRs ( particularly #142 and #133 ) have been well tested, I have no problems merging them. Before we release master to pip, we could do some final sanity checks. I, too, want all these improvements to be made available to all users.

**Comment by timb07** [comment]
If it helps, I have been using my fork which includes #133 and #141 in production for two months without problem. (Production in my case is extracting text and URLs from PDFs received in emails flagged as spam by consumers, so it includes a wide variety of PDFs.)

**Comment by pombredanne** [comment]
@ganeshtata do you still need some help for this?

**Comment by ganeshtata** [comment]
A new version has been released.
