### ISSUE TITLE
2 empty rows in table

### ISSUE THREAD

**Issue by ChaosPredictor** [pdfminer/pdfminer.six#156]
I'm working with table that have some empty rows, like this
![image](https://user-images.githubusercontent.com/1302083/41646708-3097c92e-747d-11e8-9c01-fc2bec80ab3f.png)

The result of this input is:

> 07 MO
> 08 TU
> 09 WE
> 
> 10 TH
> 
> 13 SU
> 
> 14 MO
> 
> 15 TU 

or as text

> \n07 MO\n08 TU\n09 WE\n\n10 TH\n\n13 SU\n\n14 MO\n\n15 TU\n\n

the pdf2txt leave one empty line in case of 1 **and** 2 skipped rows in the original table. I need to know how many empty rows after each row with data.

**Comment by pquentin** [comment]
I don't know if this is possible with the pd2txt tool. An option is to ask PDFMiner to produce an XML file that will give you the coordinates of each row, which you can use to get the number of lines, which is easier for you because you know the layout of your PDF files.

**Comment by RolandColored** [comment]
As an alternative you can use some tools, which extract tables from PDF. But unfortunately this is not a trivial problem and the results vary from case to case.

**Comment by tataganesh95** [comment]
@ChaosPredictor  Have you tried out the solution provided by pquentin?

**Comment by ganeshtata** [comment]
@ChaosPredictor  Have you tried out @pquentin 's solution?

**Comment by ChaosPredictor** [comment]
@ganeshtata Thanks, Not I didn't. 
I moved to Tabula, 
Sorry :/

**Comment by ganeshtata** [comment]
@ChaosPredictor  No problem. Glad that you found something to help with your issue.
