### ISSUE TITLE
question about pdf coordinate

### ISSUE THREAD

**Issue by 3y3y3y** [pdfminer/pdfminer.six#159]
hello! I am now using your pdfminer to treat the pdf files but I am confused to your bbox attribute. Is the original coordinate of the pdf document is at the bottom-left corner? How do you define the length and weight of the pdf page?
Thank you very much!

**Comment by RolandColored** [comment]
Like you said: Pdfminer uses the PDF coordinate system, hence the units are points ake "PDF units".
https://www.leadtools.com/help/leadtools/v19/dh/to/pdf-topics-pdfcoordinatesystem.html

**Comment by 3y3y3y** [comment]
Thank you very much! 
How can I get the PDF units for height and weight using your codes?
Thanks a lot!

**Comment by tataganesh95** [comment]
@3y3y3y Have you found a solution to your problem?

**Comment by ganeshtata** [comment]
@3y3y3y Have you found a solution to your problem?

**Comment by 3y3y3y** [comment]
@ganeshtata Not yet. :(

**Comment by RolandColored** [comment]
Maybe this could be the way to go: https://stackoverflow.com/a/48886525/6397425
