### ISSUE TITLE
 TypeError: unicode argument expected, got 'str'

### ISSUE THREAD

**Issue by nithinivi** [pdfminer/pdfminer.six#161]
I am using python 2.7.15. When running the following code I get a unicode error
This is the code written based on [stackoverflow ](https://stackoverflow.com/questions/26494211/extracting-text-from-a-pdf-file-using-pdfminer-in-python)

```
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
from io import StringIO
import os

def convert_pdf_to_txt(path):
    rsrcmgr = PDFResourceManager()
    retstr = StringIO()
    codec = 'utf-8'
    laparams = LAParams()
    device = TextConverter(rsrcmgr, retstr, codec=codec, laparams=laparams)
    fp = open(path, 'rb')
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    password = ""
    maxpages = 0
    caching = True
    pagenos=set()

    for page in PDFPage.get_pages(fp, pagenos, maxpages=maxpages, password=password,caching=caching, check_extractable=True):
        interpreter.process_page(page)

    text = retstr.getvalue()

    fp.close()
    device.close()
    retstr.close()
    return text

path = os.getcwd() + '/yolo.pdf'
path = os.path.realpath(path)
assert os.path.isfile(path)

convert_pdf_to_txt(path)


```

This is the trace back

```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    interpreter.process_page(page)
  File "C:\Users\nithi\Anaconda3\envs\pdfminer\lib\site-packages\pdfminer\pdfinterp.py", line 853, in process_page
    self.device.end_page(page)
  File "C:\Users\nithi\Anaconda3\envs\pdfminer\lib\site-packages\pdfminer\converter.py", line 56, in end_page
    self.receive_layout(self.cur_item)
  File "C:\Users\nithi\Anaconda3\envs\pdfminer\lib\site-packages\pdfminer\converter.py", line 212, in receive_layout
    render(ltpage)
  File "C:\Users\nithi\Anaconda3\envs\pdfminer\lib\site-packages\pdfminer\converter.py", line 202, in render
    render(child)
  File "C:\Users\nithi\Anaconda3\envs\pdfminer\lib\site-packages\pdfminer\converter.py", line 202, in render
    render(child)
  File "C:\Users\nithi\Anaconda3\envs\pdfminer\lib\site-packages\pdfminer\converter.py", line 202, in render
    render(child)
  File "C:\Users\nithi\Anaconda3\envs\pdfminer\lib\site-packages\pdfminer\converter.py", line 204, in render
    self.write_text(item.get_text())
  File "C:\Users\nithi\Anaconda3\envs\pdfminer\lib\site-packages\pdfminer\converter.py", line 195, in write_text
    self.outfp.write(text)
TypeError: unicode argument expected, got 'str'

```

If more info is needed to fix the issue, let me know. I can also provide the PDF file that produces the issue. Other than that keep the good work up, I really enjoy pdfminer.six!
Thanks in advance for  your time!

**Comment by ganeshtata** [comment]
I am not too sure as to what the problem is here. You are using Anaconda 3, so doesn't Anaconda3, by default, come with python 3.6? But you are running the code in python 2.7. Could you ensure that Anaconda is also using the same version of python?
Tip: If you don't have any specific reason to use python 2.7, use python 3.6 that comes by default with Anaconda3.

**Comment by nithinivi** [comment]
I figured out my mistake I have to  use 
`from io import BytesIO`
instead of **StringIO** ,since **StringIO** is an in-memory stream for unicode text.
Thank you so much for the help .

**Comment by tsengchan** [comment]
I got this error after change to BytesIO:

TypeError: descriptor 'write' requires a '_io.BytesIO' object but received a 'str'

**Comment by jainna** [comment]
I am still facing the same issue as @nithinivi, even though I made the changes you mentioned above. 
Can you please help me out here?

**Comment by neetinkandhare** [comment]
here is complete code which works for python 2 and python 3:
import io
from pdfminer.converter import TextConverter
from pdfminer.pdfinterp import PDFPageInterpreter
from pdfminer.pdfinterp import PDFResourceManager
from pdfminer.pdfpage import PDFPage
import six
   resource_manager = PDFResourceManager()
        # To Handle unicode conversion in python 2 and python 3
   if six.PY2:
            fake_file_handle = io.BytesIO()
        else:
            fake_file_handle = io.StringIO()

        converter = TextConverter(resource_manager, fake_file_handle)
        page_interpreter = PDFPageInterpreter(resource_manager, converter)

        extracted_input = u""

        with tempfile.NamedTemporaryFile(mode="w+b", delete=True) as temp_pdf_file:
           # try:
            # Write and close temp file
            temp_pdf_file.write(attachment_input)
                # Reading the Data from Created Temp File
            for page in PDFPage.get_pages(temp_pdf_file, caching=True, check_extractable=True):
                page_interpreter.process_page(page)

            extracted_input = fake_file_handle.getvalue()
            #except Exception as error_msg:
                #raise ValueError("Failed Convert .pdf files data to string format. Error: {0}".format(error_msg))
            #finally:
            # close open handles
            converter.close()
            fake_file_handle.close()

**Comment by neetinkandhare** [comment]
Complete code to convert bytes to pdf and pdf to text.
``import io
from pdfminer.converter import TextConverter
from pdfminer.pdfinterp import PDFPageInterpreter
from pdfminer.pdfinterp import PDFResourceManager
from pdfminer.pdfpage import PDFPage
import six
   resource_manager = PDFResourceManager()
        # To Handle unicode conversion in python 2 and python 3
   if six.PY2:
            fake_file_handle = io.BytesIO()
        else:
            fake_file_handle = io.StringIO()

        converter = TextConverter(resource_manager, fake_file_handle)
        page_interpreter = PDFPageInterpreter(resource_manager, converter)

        extracted_input = u""

        with tempfile.NamedTemporaryFile(mode="w+b", delete=True) as temp_pdf_file:
           # try:
            # Write and close temp file
            temp_pdf_file.write(attachment_input)
                # Reading the Data from Created Temp File
            for page in PDFPage.get_pages(temp_pdf_file, caching=True, check_extractable=True):
                page_interpreter.process_page(page)

            extracted_input = fake_file_handle.getvalue()
            #except Exception as error_msg:
                #raise ValueError("Failed Convert .pdf files data to string format. Error: {0}".format(error_msg))
            #finally:
            # close open handles
            converter.close()
            fake_file_handle.close()

**Comment by neetinkandhare** [comment]
`#Complete code to convert bytes to pdf and pdf to text.
import io
from pdfminer.converter import TextConverter
from pdfminer.pdfinterp import PDFPageInterpreter
from pdfminer.pdfinterp import PDFResourceManager
from pdfminer.pdfpage import PDFPage
import six
import tempfile


def extract_text_from_pdf(cls, attachment_input):
    """
    Wrapper to convert bytes data in into PDF file and extracting the text data from .pdf file
    :param attachment_input:  attachment Bytes data from resilient api call
    :return:  Text Data
    """
    resource_manager = PDFResourceManager()
    # To Handle unicode conversion in python 2 and python 3
    if six.PY2:
        fake_file_handle = io.BytesIO()
    else:
        fake_file_handle = io.StringIO()

    converter = TextConverter(resource_manager, fake_file_handle)
    page_interpreter = PDFPageInterpreter(resource_manager, converter)

    extracted_input = u""

    with tempfile.NamedTemporaryFile(mode="w+b", delete=True) as temp_pdf_file:
        try:
        # Write and close temp file
            temp_pdf_file.write(attachment_input)
            # Reading the Data from Created Temp File
            for page in PDFPage.get_pages(temp_pdf_file, caching=True, check_extractable=True):
                page_interpreter.process_page(page)

            extracted_input = fake_file_handle.getvalue()
        except Exception as error_msg:
            raise ValueError("Failed Convert .pdf files data to string format. Error: {0}".format(error_msg))
        finally:
        # close open handles
            converter.close()
            fake_file_handle.close()
    return extracted_input
`
