### ISSUE TITLE
Add documentation for extracting images

### ISSUE THREAD

**Issue by 3y3y3y** [pdfminer/pdfminer.six#162]
Hello! Recently I am working on pdf text and image extraction and I found your cool tool. 
It works quite well on text extraction but the image saved using ImageWriter looks quite terrible. It looks like  a negative photo... 
Perhaps it's the problem of image compression or image type?
Could someone explain how could we get the image type from the pdf data?
Thanks!

**Comment by pietermarsman** [comment]
Hi @3y3y3y, thanks for your question. I'm planning on adding an example for this to the documentation. If that's done I'm considering this issue closed. 

If you have any specific problems you could open a new issue. Don't forget to add an example PDF file and the code you are using.

**Comment by pietermarsman** [comment]
We could also add a high-level API for extracting images: `extract_images()`.
