### ISSUE TITLE
Almost one year since last release

### ISSUE THREAD

**Issue by jessek** [pdfminer/pdfminer.six#165]
Can you please push a new release of the project? https://github.com/pdfminer/pdfminer.six/releases It's been almost a year since the last release and there's been a lot of great work added to the project since then. 

They've recently updated the documentation on how to create a release at https://help.github.com/articles/creating-releases/.

thank you!

**Comment by ganeshtata** [comment]
@jessek We are planning on a new release. Just left to review with 1-2 important PRs.

**Comment by jessek** [comment]
What are the PRs which need review? I'd be happy to take a look.

**Comment by ganeshtata** [comment]
@jessek Waiting for a clarification regarding https://github.com/pdfminer/pdfminer.six/pull/141. Will try and merge this whenever I get time.

**Comment by h2ri** [comment]
Is there any estimate on the new release ?

**Comment by ganeshtata** [comment]
A new version has been released.
