### ISSUE TITLE
Host docs using Github Pages

### ISSUE THREAD

**Issue by ranisalt** [pdfminer/pdfminer.six#171]
I see that documentation is available at /docs. Coincidentally, that's exactly one of the options where Github can automatically serve pages:

![image](https://user-images.githubusercontent.com/1993083/43988549-a330be50-9d27-11e8-9e09-ff6d71b7be48.png)

Please do this, so that documentation is available at pdfminer.github.io/pdfminer.six

**Comment by pietermarsman** [comment]
I've started working on sphinx documentation on the [documentation](https://github.com/pdfminer/pdfminer.six/tree/documentation) branch. It is published on [readthedocs](https://pdfminersix.readthedocs.io/en/documentation/). 

Keep in mind: work in progress, help is appreciated.
