### ISSUE TITLE
pdfminer unable to extract metadata - returns PDFObjRef

### ISSUE THREAD

**Issue by sowdust** [pdfminer/pdfminer.six#172]
When trying to extract metadata from some pdf files, instead of getting a string value for the metadata information, I get a PDFObjRef. 
I tried with PyPDF2 and I get the same problem.
I also tried dumping the whole pdf as xml, but the metadata tags are not there either.
The metadata information IS there, because regular pdf readers and pdfminer command line tool extract it correctly.
I also tried to see if there was a 'Metadata' key in the doc.catalog, but it isn't there.

EDIT: it's probably worth mentioning that the issue happens mostly with pdf file produced with mac os

**Comment by typhoon71** [comment]
The following was how I solved it:

```python
from pdfminer.pdftypes import PDFObjRef, resolver1

if isinstance(value, PDFObjRef):
    value = resolve1(value)

```
Where "value" is something like <PDFObjRef:5860>.

**Comment by sowdust** [comment]
It works, thanks!

**Comment by os-gabe** [comment]
I'm having this same problem where my `doc.catalog` has no `Metadata` key and don't quite understand the solution here. Would it be possible to post a super short example of reading a pdf and using the `resolve1` trick to extract metadata?

**Comment by sowdust** [comment]
You can see how I'm doing in this edited version of "dumppdf.py": https://github.com/sowdust/pdfxplr/blob/master/dumppdf.py built for the tool https://github.com/sowdust/pdfxplr

**Comment by pietermarsman** [comment]
@os-gabe if you need more attention for your question you could also create a new issue. Make sure to include the code and pdf you are using.

**Comment by typhoon71** [comment]
Would something similar to "docs/source/tutorial/extract_pages.rst" be OK? 

Also, I'll need some help: how do I add stuff there? Fork PDFMiner, add my file and when it's done do a pull request?
(no experience here)
