### ISSUE TITLE
Add option to ignore Django

### ISSUE THREAD

**Issue by codekoala** [pdfminer/pdfminer.six#18]
I'm running into an issue with pdfminer trying to import settings from Django. I have my virtualenv configured to use the system site-packages so I don't have to constantly recompile packages like numpy. I also happen to have Django installed in my system site-packages directory. Even though my project doesn't need/use Django, pdfminer still tries to access django.conf.settings.PDF_MINER_IS_STRICT.

It would be nice to have a way to ignore Django if it's installed but not actually used.

**Comment by codekoala** [comment]
I'm able to get past the error by including this hack in my project:

```python
import sys
sys.modules['django.conf'] = None
```

**Comment by goulu** [comment]
solved by #41
