### ISSUE TITLE
Parsing diff for fonts doesn't work correctly

### ISSUE THREAD

**Issue by janslifka** [pdfminer/pdfminer.six#183]
When a font object has difference array (e.g. Hebrew or Cyrillic) the substitution characters are not parsed correctly resulting into mangled text. After exploring the issue I found out that the problem is in `encodingdb.py` where the unicode codes are parsed as decimals while they are actually hex.

Changing the regular expression and use base 16 when converting to int resolves the issue:

```python
STRIP_NAME = re.compile(r'[0-9A-F]+')


##  name2unicode
##
def name2unicode(name):
    """Converts Adobe glyph names to Unicode numbers."""
    if name in glyphname2unicode:
        return glyphname2unicode[name]
    m = STRIP_NAME.search(name)
    if not m:
        raise KeyError(name)
    return six.unichr(int(m.group(0), base=16))
```

I can open a pull request if you think this would not break anything else.

**Comment by ganeshtata** [comment]
Have you tested this change? You can raise a PR to the develop branch.

**Comment by 0xabu** [comment]
This fixes a bug for me as well. I'll create a PR.
