### ISSUE TITLE
PDFMiner does not parse more than 1 page

### ISSUE THREAD

**Issue by MonkeyBot2020** [pdfminer/pdfminer.six#187]
I'm using PDFMiner6 with Python 3.5. It's far better than PyPDF2 (slower, but more accurate and doesn't spit out a bunch of letters that are not separated by spaces). I tried to parse this document:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2963791/ (You can download the PDF free from the NIH website).

I used this code (it's part of a larger spider, but the rest of the code is not relevant to this question):
```
import io
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage

class PDFMiner6(object):
    def __init__(self):
        pass

    def PdfFileReader(self, fp):
        text = []
        rsrcmgr = PDFResourceManager()
        retstr = io.StringIO()
        codec = 'utf-8'
        laparams = LAParams()
        device = TextConverter(rsrcmgr, retstr, codec=codec, laparams=laparams)
        interpreter = PDFPageInterpreter(rsrcmgr, device)
        password = ""
        maxpages = 0
        caching = True
        pagenos = set()

        for page in PDFPage.get_pages(fp, pagenos, maxpages=maxpages, password=password, caching=caching, check_extractable=True): 
            interpreter.process_page(page)
            output = retstr.getvalue()
            text.append(output)

        fp.close()
        device.close()
        retstr.close()
        return text
```
It parses the first page perfectly, then stops. The rest of the document is not parsed.

I tested the same document using PyPDF2, it parses the entire document but outputs garbage without any spaces (hence I switched over to PDFMiner6). So I'm sure that it's not that the entire document is not being read but something wrong with the code that's parsing it. What is wrong?

EDIT: I went ahead and tested it on different PDF files with varying results - it parses some completely, whereas others, it stops at the first page. This is frustrating, as PDFMiner6 is a better parser compared to PyPDF2.

Could anybody help?

**Comment by austynh** [comment]
@MonkeyBot2020 Looks like you might need to adjust the maxpages parameter in the PDFPage.get_pages function call. 

The get_pages function is a generator that yields pages while maxpages <= pagenum+1. This check happens after yielding the first page which guarantees one page is returned. 

get_pages source can be found here https://github.com/pdfminer/pdfminer.six/blob/master/pdfminer/pdfpage.py

Hope this helps.

**Comment by Recursing** [comment]
Using `pdfminer.high_level.extract_text("nihms233215.pdf")` on the pdf at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2963791/pdf/nihms233215.pdf seems to work fine in version 20191110

I think you can close this issue

**Comment by pietermarsman** [comment]
Indeed, you are right!
