### ISSUE TITLE
Extracting bold text and non bold text from pdf

### ISSUE THREAD

**Issue by lkmh** [pdfminer/pdfminer.six#189]
Is there a way to extract bold text and non bold text from pdf ?

**Comment by ZanonEdoardo** [comment]
I think actually no.

**Comment by Bachstelze** [comment]
You can convert it to HTML with `high_level.extract_text_to_fp(fin, output, laparams=LAParams(), output_type='html', codec=None)` and filter it with soup or lxml.

**Comment by pietermarsman** [comment]
Hi @lkmh, thanks for your question! There is no such thing as bold or italic text in a PDF. However, most PDF's use multiple variants of the same font-family to get bold (and italic) text. E.g. a specific font for bold, one for italic and one for regular. The names of these fonts often reflect this.

You could use `extract_pages` to get the pages of a pdf, and iterate over the elements in it. For every character you should check the font-name and see if it contains "bold". 

See the [docs](https://pdfminersix.readthedocs.io/en/develop/api/highlevel.html#extract-pages) and e.g. this [comment on extracting font names](https://github.com/pdfminer/pdfminer.six/issues/380#issuecomment-597648152).

**Comment by harozudu** [comment]
I did something like that using the help from the website:

from pdfminer.high_level import extract_pages
from pdfminer.layout import LTTextContainer, LTChar
for page_layout in extract_pages('PDF_FILE.pdf'):
    for element in page_layout:
        if isinstance(element, LTTextContainer):
            for text_line in element:
                # print(text_line)
                
                for character in text_line:
                    if isinstance(character, LTChar):
                        if 'Bold' in character.fontname:
                            print(text_line)

**Comment by sethidden** [comment]
I've found that using the [pdfplumber](https://github.com/jsvine/pdfplumber) library (based on pdfminer) for something like this is slightly easier.

See https://github.com/jsvine/pdfplumber/issues/89#issuecomment-435747202 - you'll just need to add an additional condition like 
```py
with pdfplumber.open(file_to_parse) as pdf: 
    text = pdf.pages[0]
    clean_text = text.filter(lambda obj: not (obj["object_type"] == "char" and "Bold" in obj["fontname"]))
    print(clean_text.extract_text())
```
No need for nested loops :)

**Comment by deskobar** [comment]
> 



> I've found that using the [pdfplumber](https://github.com/jsvine/pdfplumber) library (based on pdfminer) for something like this is slightly easier.
> 
> See [jsvine/pdfplumber#89 (comment)](https://github.com/jsvine/pdfplumber/issues/89#issuecomment-435747202) - you'll just need to add an additional condition like `"Bold" in obj["fontname"]` as harozudu did above.
> 
> ```python
> with pdfplumber.open(file_to_parse) as pdf: 
>     text = pdf.pages[0]
>     clean_text = text.filter(lambda obj: not (obj["object_type"] == "char" and "Bold" in obj["fontname"]))
>     print(clean_text.extract_text())
> ```
> 
> No need for nested loops :)

I was looking for almost the same solution, thx :)
