### ISSUE TITLE
Suggestion: rename to pdfminer/pdfminer and defork

### ISSUE THREAD

**Issue by jbarlow83** [pdfminer/pdfminer.six#197]
If you contact GitHub support and ask them to defork this project they will break the link to euske/pdfminer, removed the "forked from ..." text, and make the code searchable.

This is the maintained version of pdfminer now, and Debian experimental has already packaged IIRC, i.e. they are intending to drop the Py2 pdfminer.

**Comment by pombredanne** [comment]
@jbarlow83 Good point an alternative be to merge back in  @euske head repo if possible too?

**Comment by pietermarsman** [comment]
Should we also rename the pypi package? That could work out if we simultaneously dropped python2 support (#194).

**Comment by pombredanne** [comment]
@euske Dear Yusuke-SAN, have you ever considered that we could help you keep your upstream code updated and maintained?

**Comment by pietermarsman** [comment]
In the gitter lobby we agreed on rebranding the name because renaming causes to much trouble.

**Comment by pietermarsman** [comment]
Good and bad options for a punchline that would justify the "six" part in our package name (in no particular order): 

- "six times as fast"
- "six of one and a half-dozen of the others" 😂
- "watch your six" (e.g. PDF is dangerous)
- "as easy as two times three"

**Comment by pietermarsman** [comment]
Another thing we can do is empasize that pdfminer.six is the version of pdfminer that is maintained by the community, and that we are actively fixing bugs and features. This has nothing to do with the ".six" part but it does make it more clear why there are two versions of pdfminer. 

I'm thinking of adding a FAQ page in the readthedocs.

**Comment by pietermarsman** [comment]
Todo:

- [ ] Invent a punchline
- [ ] Change the github description of this project
- [ ] Add punchline to README.md
- [ ] Add punchline to sphinx docs
- [ ] Add FAQ question about why this package is called pdfminer.six
- [ ] Add FAQ question about why there are so many versions of pdfminer.six, and why this one is special
- [ ] Add FAQ question about the differences between pdfminer/pdfminer.six and euske/pdfminer

**Comment by jbarlow83** [comment]
On the punchlines - "six times as fast" is not the case, and for "watch your six" pdfminer(.six) isn't particularly robust at handling malformed PDFs, and I'd argue, nor should it be since qpdf does a great job of that already and pikepdf (shameless plug) binds qpdf for Python.

The second and fourth suggestions make it clear that .six has no particular meaning.

**Comment by ArchangeGabriel** [comment]
I’m also in favour of removing the .six from the name, because it is pointless and confusing especially when the original project tells you to use this fork instead. So just take the namespace and be done with it. ;)

**Comment by pietermarsman** [comment]
Update: the project is deforked from the original pdfminer.

**Comment by 27ShanuGarg** [comment]
May I know how to get the layout of whole pdf

**Comment by pietermarsman** [comment]
So any great ideas for a punchline?

**Comment by jstockwin** [comment]
I don't love it, but this is the best I can come up with:

Something using the phrase "knock for six" (i.e. which originates from getting a six in cricket, I believe)? Note quite sure how to force it in to PDFs, though... maybe "knocking PDFs for 6".

**Comment by pietermarsman** [comment]
Maybe acronyms... but then what would the "x" be :confounded: 

Or we could just say what it is: "because we used to use six to support both python2 (not anymore) and python3"

**Comment by NickFabry** [comment]
pdfminer.six - because it fathoms PDFs.

(six feet = one fathom. And to fathom something means to deeply understand/measure it.)

Yes, it's a stretch, but it's a whimsical one.

BTW, I really appreciate the solid job of maintaining pdfminer. I worked on it back in 2008 by giving Euske a sample of a thousand or so PDFs I had and working on pdfminer until it could extract the text from every one without error. That was fun :-) - and it still seems to be the best python pdf text extraction engine out there. Thanks for keeping it well!

**Comment by jstockwin** [comment]
You could spell e.g. "extract" starting with an x... But I'm not sure I like that idea.

I really like fathoms, and if there's some way to phrase it that doesn't need the explanation in brackets that'd be great. Alternatively we just don't give the explanation in most places? I guess this issue will always be here anyway XD.

P.S. cool that you worked in it in 2008!

**Comment by pietermarsman** [comment]
> pdfminer.six - because it fathoms PDFs.

This goes the whole nine yards :p

**Comment by pietermarsman** [comment]
Someone cares to review my changes in #520?
