### ISSUE TITLE
Documentation on examples of how to use the library

### ISSUE THREAD

**Issue by fippli** [pdfminer/pdfminer.six#199]
Hi! I have a really hard time finding examples of how to use the library.
Would you consider adding some examples in your wiki or README?

For example Im trying to figure out how to read a pdf file and get it converted to html and store it as string in a variable in a python script e.g.
```python
. . . some algorithm
htmlString = pdfminer.someMethod('./foo.pdf')
```

**Comment by ganeshtata** [comment]
This example might be of help to you - https://gist.github.com/vinovator/c78c2cb63d62fdd9fb67
Will try and update the repo with proper docs.

**Comment by mangos47** [comment]
for Python 3.x, it appears that there is a package "pdfminer3k" indicated in the script above, which actually doesn't work. "pdfminer.six" as suggested in the main page here works.

Also, for some reason unknown to me, when I run "python pdf2txt.py samples/sample1.pdf", it doesn't work. I need to supply full path as "python c:/path/to/pdf2txt.py samples/sample1.pdf" to make it work. Even though that "c:/path/to" is actually in my PATH and I can open the file from command prompt by simply type "pdf2txt.py"
