### ISSUE TITLE
NameError: global name 'ImageWriter' is not defined

### ISSUE THREAD

**Issue by ivanteoh** [pdfminer/pdfminer.six#20]
When running this command below on pdfminer.six version 20160202 in Python 2.7.10, `NameError: global name 'ImageWriter' is not defined` error message occurred.

```
$ pdf2txt.py -O myoutput -o myoutput/myfile.html -t html -p 1,3 myfile.pdf
```

**Comment by goulu** [comment]
Solved by #21 . Image export works (again) with Py3
