### ISSUE TITLE
Also push an sdist to Pypi

### ISSUE THREAD

**Issue by pombredanne** [pdfminer/pdfminer.six#208]
The recent release only includes a wheel. An sdist tarball should be pushed too IMHO

**Comment by eriol** [comment]
Pleas publish an sdist tarball, I would like to switch to the latest release of this project for the official pdfminer Debian package, but an sdist is required to do this. Right now I can only package the 20170720 release.
Thanks!

**Comment by jessek** [comment]
We would also appreciate having a source tarball in PyPi.

**Comment by eriol** [comment]
I switched the Debian packaging to use git tags, but I still think that an sdist tarball should be pushed to PyPi.

**Comment by jessek** [comment]
Any progress here? Our project is blocked until we can get a source tarball.

**Comment by pombredanne** [comment]
@jessek are you really blocked? you can crate one and bundle it if needed. 

@ganeshtata do you need help? this is really about:
`python setup.py sdist bdist_wheel`
`twine upload dist/*`

**Comment by jessek** [comment]
Yes, we're blocked. For better or worse or system will only accept a source package from Pypi.

**Comment by ganeshtata** [comment]
Extremely sorry for the late reply. I haven't been able to get back to this project for a while now.
@pombredanne Would I have to make a new release for this?

**Comment by pombredanne** [comment]
@ganeshtata re:

> Would I have to make a new release for this?

nope! Thanks and I am closing now that this is fixed
