### ISSUE TITLE
Unable to text parse version PDF-1.7

### ISSUE THREAD

**Issue by Drise13** [pdfminer/pdfminer.six#212]
I have been working on a project to read PDF forms. PDF's of version <= 1.6 work just fine. For 1.7 pdf's I can't seem to get any text of the pdf, or any of the form fields, except for the two signature fields. I'm reluctant to upload the PDF, since it's not mine. Is there any guidance on how to look into the logs/debug or a known issue with 1.7 pdf's? 

If I had to take a guess after spending the last 8 hours becoming familiar with the PDF language, it seems to be something wrong with decoding(?) the streams.

As a side note, dumppdf.py seems to find bits of the text, so I know it's parseable, I just don't know how to debug and fix the main miner.

**Comment by romk1n** [comment]
the same problem, anyone figured out a fix ?

**Comment by pietermarsman** [comment]
It is quite hard for us to understand the problem without having an example pdf, stack trace and example code. Let alone we are able to propose a fix. 

If this is still relevant to you, could you supply the error message with the stack trace? Also, give an example of the code you are using. If possible, also upload the pdf. This makes testing and fixing a lot easier.
