### ISSUE TITLE
multiple xrefs in pdf cause page extraction return only the first page

### ISSUE THREAD

**Issue by meldonization** [pdfminer/pdfminer.six#214]
PDF file: [bad_page_number.pdf](https://github.com/pdfminer/pdfminer.six/files/2672072/bad_page_number.pdf)
- pdfminer extracts only the first page of the file 
- parser.bufpos stop at size 10325
- it looks like this file contains two `%%EOF` lines

```python
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfinterp import PDFResourceManager
from pdfminer.pdfinterp import PDFPageInterpreter
from pdfminer.pdfdevice import PDFDevice
from pdfminer.layout import LAParams
from pdfminer.converter import PDFPageAggregator
from pdf2html import *
fpath = '~/bad_page_number.pdf.pdf'
fp = open(fpath, 'rb')
parser = PDFParser(fp)
laparams = LAParams()
document = PDFDocument(parser)
rsrcmgr = PDFResourceManager()
device = PDFPageAggregator(rsrcmgr, laparams=laparams)
interpreter = PDFPageInterpreter(rsrcmgr, device)
print(len(list(PDFPage.create_pages(document))))
```

Could you please look into the problem please?

**Comment by bmteller** [comment]
This can be fixed by changing `line.startwith(b'trailer')` to `line.strip().startswith(b'trailer')`. https://github.com/pdfminer/pdfminer.six/blob/develop/pdfminer/pdfdocument.py#L102

the document has an xref table where the trailer keyword is indented.
```
0003575084 00000 n
 trailer
<</Size 973
>>
```

**Comment by pietermarsman** [comment]
Looks like a valid solution. Feel free to implement if you have the time.

**Comment by jstockwin** [comment]
I can take a look at this

**Comment by pietermarsman** [comment]
@jstockwin I accidentally merged the PR while the build was broken. Could you see what the issue was and recreate the PR?

**Comment by jstockwin** [comment]
Huh, oops. Sure, I will take another look...
