### ISSUE TITLE
pdfminer.six get list index out of range error in objid1 = x[-2]

### ISSUE THREAD

**Issue by youngspring1** [pdfminer/pdfminer.six#216]
I got this error when I use pdfplumber and concurrent to parse pages in one pdf file. 
But it's OK if I parse it directly(without concurrent).

```
  File "/Users/xuyangchun/.pyenv/versions/evaluation365/lib/python3.6/site-packages/pdfminer/pdfdocument.py", line 661, in _getobj_parse
    objid1 = x[-2]
IndexError: list index out of range
```

my env:
python 3.6.5
pdfminer.six==20170720
pdfplumber==0.5.10

It seems have something to do with this issue: https://github.com/euske/pdfminer/issues/35

test pdf file:
http://www.cninfo.com.cn/finalpage/2018-09-26/1205464895.PDF

**Comment by pietermarsman** [comment]
I can't reproduce this issue because the PDF files are no longer available.

But probably it is fixed because the current code is like this:

```python
            if len(x) >= 2:
                objid1 = x[-2]
```
