### ISSUE TITLE
lzw.py error when trying to log and self.table=None

### ISSUE THREAD

**Issue by mmiguel** [pdfminer/pdfminer.six#221]
Error in line 93 of lzw.py, exception due to trying to index None (i.e. self.table).
 I ran into this when parsing a PDF file. The code variable at the time of the exception was 257, so I believe the feed method never initialized self.table due to never receiving code=256 when parsing the file I'm guessing.

I suggest either setting self.table=[] in __init__ or changing the logging.debug line in line 93/94 to
```python
logging.debug('nbits=%d, code=%d, output=%r, table=%r' % (self.nbits, code, x, self.table[258:] if self.table is not None else ''))
```

**Comment by jstockwin** [comment]
@pietermarsman found this one while going through the issues. Do you have a preferred solution given the above?
@mmiguel If this is still an issue, are you able to open a PR to fix it?

**Comment by pietermarsman** [comment]
Either print whole table or initialize table with an empty list. 

A bigger issue might be the performance cost of this log statement. Not sure how often it is called, but it formats the string even if it is not printed. The data should be passed as positional arguments such that `logger.debug` does the formatting only if it needs to be printed.
