### ISSUE TITLE
Error Install Python 3.7.2

### ISSUE THREAD

**Issue by carocorrea2343** [pdfminer/pdfminer.six#223]

**Comment by carocorrea2343** [comment]
I'm trying to use pdfminer.six in Python 3.7.2 but it's not working. Can you please let me know which version of Python/Anaconda should I use? 

Thanks in advance

**Comment by Freakwill** [comment]
> I'm trying to use pdfminer.six in Python 3.7.2 but it's not working. Can you please let me know which version of Python/Anaconda should I use?
> 
> Thanks in advance

I work with pdfminer.six in Python 3.6

**Comment by pietermarsman** [comment]
Can you copy the error and stacktrace? This helps identifying the problem and allows others to check if they are also affected.

**Comment by ashemedai** [comment]
Just to add my EUR 0,02: works for me using a pyenv'd Python 3.7.4 on Mac.

**Comment by pietermarsman** [comment]
I think we can close this issue since there is nothing we can work on
