### ISSUE TITLE
Limitation in pdf2txt.py?

### ISSUE THREAD

**Issue by ktnx** [pdfminer/pdfminer.six#229]
I use the usually very well working pdfannots, a script for extracting annotations from pdf files which is based on pdfminer.six. For one pdf file I was not able to extract any source code-like text. However, all the other text worked perfectly. Could this be an issue in pdfminer.six, specifically pdf2txt.py?

You can find the original issue here: https://github.com/0xabu/pdfannots/issues/15

**Comment by pietermarsman** [comment]
@0xabu, this issue can be closed because you have merged your PR
