### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'codec'

### ISSUE THREAD

**Issue by dzhang228** [pdfminer/pdfminer.six#232]
fail to run pdf2text  pdfminer.six.

(base) C:\wamp64\www\pydev\pdfproc>py pdf2txt.py -d -o npm.html -t text 201806-exam.pdf
Traceback (most recent call last):
  File "pdf2txt.py", line 136, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "pdf2txt.py", line 131, in main
    outfp = extract_text(**vars(A))
  File "pdf2txt.py", line 63, in extract_text
    pdfminer.high_level.extract_text_to_fp(fp, **locals())
  File "C:\Users\David\Anaconda3\lib\site-packages\pdfminer\high_level.py", line 70, in extract_text_to_fp
    imagewriter=imagewriter)
TypeError: __init__() got an unexpected keyword argument 'codec'

**Comment by dzhang228** [comment]
the pdfminer.six was installed over the previous pdfminer.
uninstall and then reinstall the pdfminer.six solved the problem

**Comment by surya-x** [comment]
> the pdfminer.six was installed over the previous pdfminer.
> uninstall and then reinstall the pdfminer.six solved the problem

thankyou! its working now.

**Comment by kritisharma1303** [comment]
its not working for me

**Comment by ERHash** [comment]
> its not working for me

1)Uninstall pdfminer and pdfminer.six
2) install pdfminer.six
