### ISSUE TITLE
possible bug? strange code and indentation in pdfdocument.py 267-288 def get_pos

### ISSUE THREAD

**Issue by dzhang228** [pdfminer/pdfminer.six#234]
the indentation of "else:" on line 275 looks strange. If it is correct, then, there is no "if" block for that "else"

below are the code. 

    def get_pos(self, objid):
        index = 0
        for (start, nobjs) in self.ranges:
            if start <= objid and objid < start+nobjs:
                index += objid - start
                break
            else:
                index += nobjs
        else:
            raise KeyError(objid)
        offset = self.entlen * index
        ent = self.data[offset:offset+self.entlen]
        f1 = nunpack(ent[:self.fl1], 1)
        f2 = nunpack(ent[self.fl1:self.fl1+self.fl2])
        f3 = nunpack(ent[self.fl1+self.fl2:])
        if f1 == 1:
            return (None, f2, f3)
        elif f1 == 2:
            return (f2, f3, 0)
        else:
            # this is a free object
            raise KeyError(objid)

**Comment by wlbentley** [comment]
I can't speak to the functionality of this code, but `else:` is a valid optional clause in a `for` loop.

See [https://wiki.python.org/moin/ForLoop](https://wiki.python.org/moin/ForLoop) for more information.

**Comment by dzhang228** [comment]
thanks for pointing out the reference
