### ISSUE TITLE
additional if/else block and indentation issue : pdfdocument.py  769~783, 780 else

### ISSUE THREAD

**Issue by dzhang228** [pdfminer/pdfminer.six#235]
the "else" on pdfdocument.py  line 780 doesn't match a if with proper indentation

    def find_xref(self, parser):
        """Internal function used to locate the first XRef."""
        # search the last xref table by scanning the file backwards.
        prev = None
        for line in parser.revreadlines():
            line = line.strip()
            log.debug('find_xref: %r', line)
            if line == b'startxref':
                break
            if line:
                prev = line
        else:
            raise PDFNoValidXRef('Unexpected EOF')
        log.info('xref found: pos=%r', prev)
        return long(prev) if six.PY2 else int(prev)

**Comment by wlbentley** [comment]
See my comment in #235.

**Comment by dzhang228** [comment]
thanks for pointing out the reference
