### ISSUE TITLE
Python 3.6 pdf2txt.py ImportError: No module named six

### ISSUE THREAD

**Issue by Marius-Juston** [pdfminer/pdfminer.six#241]
Hello, I am running Python 3.6.8 on a Windows 10, I am using Anaconda3 for my environment and I installed pdfminer.six using the `conda install -c conda-forge pdfminer.six`; however, when I tried running the `pdf2txt.py samples/simple1.pdf` command I ran into a 
```
Traceback (most recent call last):
  File "C:\Users\*****\Anaconda3\envs\***********************\Scripts\pdf2txt.py", line 8, in <module>
    import six
ImportError: No module named six
```

I tried installing the `six` package using pip install, uninstalling it and reinstalling it, using the conda environment to install it, deleting and recreating my Anaconda3 environment to no avail. I also installed `cardet` as per the issue

> I guess you should reinstall packages after upgrading from 2.7 to 3.4.
> 
> setup.px contains line
> install_requires=['six', 'chardet'] if sys.version_info >= (3, 0) else ['six'],
> 
> so for Python 3.x it will also install package chardet, which is probably missing .
_Originally posted by @goulu in https://github.com/pdfminer/pdfminer.six/issues/30#issuecomment-241975667_

**Comment by pietermarsman** [comment]
Hi @Marius-Juston, 

I can't replicate this with the current version. I use the exact same command to install pdfminer.six into a conda environment and it just works. 

Could you test if you are still experiencing this problem?

**Comment by starfriend10** [comment]
I have a similar issue. I have the same Python and OS environment. 
First, when I installed the lib using
`pip install pdfminer.six`
There is no "pdfminer.six" folder under the path "C:\ProgramData\Anaconda3\Lib\site-packages", it only has a folder "pdfminer" and a folder "pdfminer.six-20191110.dist-info"
Second, in the folder "pdfminer", it has 28 python files and one folder "cmap", no other folders (e.g. tools, samples, ...)
Therefore, when I ran 
'pdf2txt.py /BuffaloCl.pdf'

It gave an error:
'Traceback (most recent call last):

  File "<ipython-input-5-93bc243ad3b0>", line 1, in <module>
    pdf2txt.py /BuffaloCl.pdf

NameError: name 'pdf2txt' is not defined'

Suggestions and advice are welcome!
Thanks.

**Comment by pietermarsman** [comment]
We have removed six from the dependencies of pdfminer, since we only support python 3 now. Therefore I consider this issue closed.

@Marius-Juston feel free to create a new issue if you are still experiencing problems.

@starfriend10, your issue looks like something else. You should open a new issue if you are still having this problem.
