### ISSUE TITLE
ModuleNotFoundError: No module named 'chardet

### ISSUE THREAD

**Issue by jbdoster** [pdfminer/pdfminer.six#249]
Installed this version for MACOSX 10.13.6 and Python version 3.7.3

I tried samples, tried parsing in scripts, they all return this error:

`ModuleNotFoundError: No module named 'chardet`

Thank you!

**Comment by jbdoster** [comment]
Oops, pip did the trick thank you it works great!

**Comment by nielsole** [comment]
for anyone else getting stuck, `pip install --force-reinstall pdfminer.six` did the trick
