### ISSUE TITLE
TextConverter output wrong with table

### ISSUE THREAD

**Issue by yogiderek** [pdfminer/pdfminer.six#256]
I am trying to convert page 1 of a PDF to text and have come across a problem. The attached HTML is converted to PDF by a third party application which i have no control over. The document properties suggest the tool used is wkhtmltopdf v0.12.4.

TextConverter generates the following 

Full name\n\nAddress\n\nJohn Smith \n\n13 Green Lane, GreensVile \n\n\x0c

I expected

Full name\n\nJohn Smith \n\nAddress\n\n13 Green Lane, GreensVile \n\n\x0c

I have tried changing some of the LAParams with no success. Is this possibly a bug?

[Test.pdf](https://github.com/pdfminer/pdfminer.six/files/3318609/Test.pdf)
[Test_html.txt](https://github.com/pdfminer/pdfminer.six/files/3318610/Test_html.txt)

**Comment by pietermarsman** [comment]
Hi @yogiderek, 

Thanks for the example pdf. Could you also share the code that you are using to proces these pdf's? And which version of pdfminer are you using?

**Comment by Tam678** [comment]
Hi @pietermarsman ,
I have a same question like that.Here are my code to process these pdfs.And my version of pdfminer.six is 20191110.

**Comment by Tam678** [comment]
def pdf_to_detail(path):
    rsrcmgr = PDFResourceManager()		
    retstr = StringIO()
    codec = 'utf-8'
    laparams = LAParams()		
    device = TextConverter(rsrcmgr, retstr, codec=codec, laparams=laparams)
    fp = open(path, 'rb')
    interpreter = PDFPageInterpreter(rsrcmgr, device)	        
    maxpages = 0
    pagenos=set()
    for page in PDFPage.get_pages(fp, pagenos, maxpages=maxpages, check_extractable=True):
        interpreter.process_page(page)
    fp.close()
    device.close()
    detail = retstr.getvalue()
    retstr.close()
    return(detail)

**Comment by pietermarsman** [comment]
Hi @Tam678, you can create a new issue for your problem. Take some time to format your message and don't forget to attach a PDF.

**Comment by pietermarsman** [comment]
I'm closing this due to no response.
