### ISSUE TITLE
Willing to pay someone to speed up pdfminer

### ISSUE THREAD

**Issue by jeffoneill** [pdfminer/pdfminer.six#257]
pdfminer works great for text extraction and most PDF files I process take less than a second.  

But some PDF files can take a couple minutes (even though the size is similar), which is too slow when you are trying to provide an immediate response. 

I'd be happy to hire someone to make pdfminer faster and your changes could be open source.  Please contact me if you are interested in doing that.

**Comment by elvisTechnologies** [comment]
hi, i want to improve pdfminer, i will contact you.

**Comment by benzkji** [comment]
also, https://jazzband.co/ could be a long time solution?

**Comment by pietermarsman** [comment]
Hi @jeffoneill,

Thanks for your willingness to pay money to active contributors to this project. You could also consider to pay money to the people who have created pdfminer from scratch. Check out the Change Log of the original pdfminer [here](https://euske.github.io/pdfminer/). 

If you would like to speak to current maintainers, you could checkout the [gitter](https://gitter.im/pdfminer-six/Lobby). 

If you would like to speed up the processing of specific pdf's, please provide examples of those pdf's and the code that you are using to process it.

**Comment by jeffoneill** [comment]
Hi @pietermarsman, I'd go broke quickly if I started paying the developers of every open source project that I use! 😄 

I'll find an example PDF that I can share.

**Comment by pietermarsman** [comment]
Closing this because there is nothing actionable. Feel free to create a new issue if you have a problem with a specific pdf.
