### ISSUE TITLE
Describe how to behave as a contributor

### ISSUE THREAD

**Issue by pietermarsman** [pdfminer/pdfminer.six#258]
I think it would help future contributors to participate if it is clear what we expect from them and what they can expect from the project. I'm thinking of the following:

- Use issues to point to problems
    - Discuss possible improvements in an issue
    - Include a minimal reproducible example if possible
    - Include the package version
- Use pull requests to fix problems
    - So no PR without an issue
    - Point your PR to the develop branch
    - PR's should be PEP8 compliant
    - PR's should create or update PEP257 docstrings if necessary. 
    - PR's should include testing of the minimal reproducing examle if possible
    - PR's should work with python2 and python3 (for now)
    - PR's should succesfully run test-suite (on travis)

**Comment by ganeshtata** [comment]
This is great! Thank you @pietermarsman !

**Comment by fakabbir** [comment]
Maybe this could have directly hit the master branch since `CONTRIBUTIONS.md`'s reference is in master branch and the file is present in develop branch.
