### ISSUE TITLE
Add export for JBIG2 images

### ISSUE THREAD

**Issue by hason** [pdfminer/pdfminer.six#26]
Can you please review and merge PR https://github.com/euske/pdfminer/pull/107

**Comment by bumblebritches57** [comment]
You can fork it and import that change if it means that much to you.

**Comment by goulu** [comment]
hopefully @side2k will PR his improvement here

**Comment by side2k** [comment]
here it is: #46

**Comment by pietermarsman** [comment]
@hason, the PR is ready for merging, only we don't have any pdf to test it with. Do you have a PDF with JBIG2 images?
