### ISSUE TITLE
conversion for devanagari ,hindi language

### ISSUE THREAD

**Issue by prokarm19** [pdfminer/pdfminer.six#260]
how can i read Hindi or Devanagari text from pdf and create an html file . for Japanese and other language it is working fine

**Comment by pietermarsman** [comment]
Hi @prokarm19, 

Do you have specific problems with reading Hindi of Devanagari from pdf's? If so, please give some more context on what you are trying to do and what goes wrong. This will allow anyone to understand your problem, give advice and/or change the code of pdfminer.six. 

If your question is more general, please look at the documentation. For example, look at [pdf2txt.py](https://pdfminer-docs.readthedocs.io/pdfminer_index.html#command-line-tools).

**Comment by khivraj-jangid** [comment]
Hi @pietermarsman 

how can i extract accurate Hindi font characters from PDF?

I try with pdfminer.six, but I did not reach to extract exact or all characters from PDF.

Please find below attachments and suggest me resolution on this issue.
1->PDF file
[hindi_heart.pdf](https://github.com/pdfminer/pdfminer.six/files/8330324/hindi_heart.pdf)

2->html output using pdfminer.six (as screenshot)
![Screenshot from 2022-03-23 11-54-37](https://user-images.githubusercontent.com/98871422/159637310-f54eb8b9-ae4a-4de3-8f3a-64c291f8d728.png)


Thanks in advanced

**Comment by pietermarsman** [comment]
Hi, 

You can use pdfminer.six as normal. 

```bash
pdf2txt.py ~/Downloads/hindi_heart.pdf
```

The output:

```
3/22/22, 1:51 PM

दय - िविकपीिडया

दय

मु ानकोश िविकपीिडया से

यह लेख शरीर के  एक अंग के  बारे म है। अ योगों के  िलए, दय (बिवकी) देख।

दय  या  िदल  एक  पेशीय  (muscular)  अंग  है,  जो  सभी  कशेकी
(vertebrate)  जीवों  म  आवृत  ताल  ब  संकु चन  के   ारा  र  का  वाह
शरीर के  सभी भागो तक पचाता है।

कशेिकयों  का  दय  द  पेशी  (cardiac  muscle)  से  बना  होता  है,  जो
एक  अनैक  पेशी  (involuntary muscle)  ऊतक  है,  जो  के वल  दय
अंग  म  ही  पाया  जाता  है।  औसतन  मानव  दय  एक  िमनट  म  ७२  बार
धड़कता  है,  जो  (लगभग  ६६वष)  एक  जीवन  काल  म  २.५  अरब  बार
धड़कता  है।  मनु  का  िदल  1  िमनट  मे  70  िमली  लीटर  र  प  करता
है,1 िदन मे 7600 लीटर(2000 gallons) तथा अपने जीवन काल मे 200
िमिलयन लीटर र प करता है।इसका भार औसतन मिहलाओं म २५०
से ३०० ाम और पुषों म ३०० से ३५० ाम होता है।[1]

कोरोनरी धमिनयों के  साथ मानव दय।

अनुम

ारं िभक िवकास

संरचना

िया

ाथिमक िचिका

खोजों का इितहास

थ दय

खा उपयोग

इ भी देख

सभ

बाहरी स

ारं िभक िवकास

मु लेख: Heart development

नधारयों का दय ूणीय म जनन र (mesoderm) से िवकिसत होता है जो गेस ला भवन (gastrulation) के
बाद मकला (mesothelium), अंत: कला (endothelium) और दपेशी (myocardium) म िवभेिदत हो जाता है।
म कला का पेरीकािडयम (pericardium) दय का भीतरी अर बनता है। दय का बाहरी आवरण, लिसका और
र वािहिनयाँ अः  कला से िवकिसत होती है। दयपेशी या मायोकािडयम का िवकास दय की पेिशयों म होता है।[2]

https://hi.wikipedia.org/wiki/दय

ि

ि

ि

1/8
```

**Comment by khivraj-jangid** [comment]
Hi @pietermarsman 

check your output text from PDF, and compare with below actual text which use in PDF.
"
हृदय
मुक्त ज्ञानकोश विकिपीडिया से 
यह लेख शरीर के एक अंग के बारे में है। अन्य प्रयोगों के लिए, हृदय (बहुविकल्पी) देखें।
हृदय या दिल एक पेशीय(muscle) अंग है, जो सभी कशेरुकी (vertebrate) जीवों में आवृत ताल बद्ध संकुचन के द्वारा [रक्त] का प्रवाह [शरीर] के सभी भागो तक पहुचाता है।

कशेरुकियों का हृदय हृद पेशी (cardiac muscle) से बना होता है, जो एक अनैच्छिक पेशी (involuntary muscle) ऊतक है, जो केवल हृदय अंग में ही पाया जाता है। औसतन मानव हृदय एक मिनट में ७२ बार धड़कता है, जो (लगभग ६६वर्ष) एक जीवन काल में २.५ अरब बार धड़कता है। मनुष्य का दिल 1 मिनट मे 70 मिली लीटर रक्त पम्प करता है,1 दिन मे 7600 लीटर(2000 gallons) तथा अपने जीवन काल मे 200 मिलियन लीटर रक्त पम्प करता है।इसका भार औसतन महिलाओं में २५० से ३०० ग्राम और पुरुषों में ३०० से ३५० ग्राम होता है।[1]
"

PDF text =  हृदय, मुक्त ज्ञानकोश
pdfminer.six text(after extract) = दय, मु ानकोश

pdfminer.six is not support or read the text which is special in Hindi language. (I checked in fontfile, It shows all characters in font file, but pdfminer.six could not able to give text in text extraction so its shows blank at special character )

**Comment by pietermarsman** [comment]
I can't read hindi, so cannot tell the difference. The first characters look different, but I wouldn't know which sections to compare. Some cntrl+F'ing doesn't result in many hits. 

Can you check what happens if you copy-paste some text from the PDF to a text editor? Do you get the correct output? If that output is different from the pdfminer.six output we should be able to solve this. If they are the same, there is not much that pdfminer.six can do. 

Can you create a new issue if the output is different?

**Comment by pietermarsman** [comment]
Also make sure to include (1) the PDF, (2) the code that you use to extract the text and (3) the expected output (e.g. the first few lines).

**Comment by khivraj-jangid** [comment]
Hi @pietermarsman 

I create new bug for this issue https://github.com/pdfminer/pdfminer.six/issues/740

And also share all required details in new issue.

Let me know if any more details you required to resolved the issue.

Thanks
