### ISSUE TITLE
How to get the color of the highlight?

### ISSUE THREAD

**Issue by pluieciel** [pdfminer/pdfminer.six#278]
I am trying to extract highlighted sentences from PDF, some are highlight in green, some red.
And I will need to extract regarding to different colors.
Could anyone help me with that?

I've got resolved highlight info, but I cannot find which part is about color.

{'AP': {'N': <PDFObjRef:35>},
 'Border': [0, 0, 1],
 'C': [1, 1, 0],
 'CA': 1,
 'CreationDate': b"D:20190722204110+01'00'",
 'F': 4,
 'M': b"D:20190722204110+01'00'",
 'NM': b'faf6d63c-3e84-4506-99e2-85ec37a4396f',
 'P': <PDFObjRef:3>,
 'Popup': <PDFObjRef:36>,
 'QuadPoints': [246.259,
  766.084,
  505.495,
  766.084,
  246.259,
  756.073,
  505.495,
  756.073],
 'Rect': [246.259, 756.073, 505.495, 766.084],
 'Subj': b'\xfe\xff\x9a\xd8N\xae',
 'Subtype': /'Highlight',
 'T': b'yyy333',
 'Type': /'Annot'}

Thanks a lot for your help!

**Comment by pietermarsman** [comment]
Hi @pluieciel, thanks for your question. I'm not sure where to look for the color, but perhaps you can use the [PDF Reference](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf) to find that out. 

Let us know when you figured out how to do it. Perhaps we can include an example into our codebase that demonstrates how to extract highlights. This would help others enormously.

**Comment by pluieciel** [comment]
Hi @pietermarsman , thanks a lot for your help!!!
I have found the info in the 'PDF Reference' page 607.
So 'C' is the color, and 'C': [1, 1, 0], is in RGB means yellow.

**Comment by pluieciel** [comment]
And here is the code I based on to extract highlight:
https://github.com/0xabu/pdfannots
