### ISSUE TITLE
Extra Character in pdf2text.py output

### ISSUE THREAD

**Issue by fakabbir** [pdfminer/pdfminer.six#284]
![image](https://user-images.githubusercontent.com/13721550/62819250-200d8900-bb70-11e9-8469-c8290c5b7a54.png)

In the extraction of PDF files an extra arrow character (↑) is present . Is it a symbol for denoting end of processing or something is wrong with encoding ?

**Comment by pietermarsman** [comment]
Is it in the output for every pdf?

**Comment by fakabbir** [comment]
Almost, I tried with two or three PDFs from different source and all got this extra arrow character. My first guess was that, maybe #264 is the culprit but no without those changes also the behavior is the same.

**Comment by fakabbir** [comment]
Surprisingly while using tesseract to scan images. I got the same symbol denoting end of process

**Comment by pietermarsman** [comment]
Do you know when this issue appeared? Does it also happen on the master branch?

If you have some time to work on this, maybe you can use [git bisect](https://git-scm.com/docs/git-bisect) to find the commit that introduced the bug.

**Comment by pietermarsman** [comment]
I cannot replicate this on master or develop. Could you upload the pdf file that you are using?

**Comment by jstockwin** [comment]
@fakabbir Just a quick bump as I'm working through all the open issues. Are you able to confirm if this is still happening? If it is, can you provide an example PDF?

**Comment by pietermarsman** [comment]
Closing this because not reproducible.
