### ISSUE TITLE
Can not parse the pages with watermark

### ISSUE THREAD

**Issue by betterRunner** [pdfminer/pdfminer.six#285]
it seems like the tool can not parse the pages with the watermark.

Only the first page of the attached pdf (without the watermark) can be parsed while the others can not.
Is this issue about the watermark?
Thanks in advanced!
[watermark.pdf](https://github.com/pdfminer/pdfminer.six/files/3489553/watermark.pdf)

**Comment by fakabbir** [comment]
Can you please attach any error log encountered or the present behavior.

**Comment by betterRunner** [comment]
The present behavior is that only the content of first page can be parsed while the others can not. And there is no error shown.

**Comment by pietermarsman** [comment]
Fixed with the current version on master.
