### ISSUE TITLE
PDFType1Font bug

### ISSUE THREAD

**Issue by naivefeeling** [pdfminer/pdfminer.six#288]
In pdffont.py
```python
        try:
            (descriptor, widths) = FontMetricsDB.get_metrics(self.basefont)
        except KeyError:
            descriptor = dict_value(spec.get('FontDescriptor', {}))
```
> Note: For the standard 14 fonts, the entries FirstChar, LastChar, Widths, and FontDescriptor must either all be present or all be absent. Ordinarily, they are absent; specifying them enables a standard font to be overridden (see “Standard Type 1 Fonts (Standard 14 Fonts),” below). -pdf_reference1.7.pdf

**Comment by pietermarsman** [comment]
Could you explain in more detail what the bug is?

**Comment by jstockwin** [comment]
@naivefeeling Just a quick bump as we're currently working through all the open issues. Are you able to provide more details on this?

**Comment by pietermarsman** [comment]
Closing this because not reproducible.
