### ISSUE TITLE
Need new build with LTChar color fixes

### ISSUE THREAD

**Issue by keshavbohra** [pdfminer/pdfminer.six#294]
Hi Team,

Could you please update the build in PyPI from pdfminer.six==20181108 with the latest changes/fixes in pdfminer.pdfinterp file for stroking and non-stroking colors in characters.

Thanks.

**Comment by pietermarsman** [comment]
Hi @keshavbohra. The pypi release is indeed behind on the master branch and I guess many of us would appreciate it if a new version is released. However, only @goulu and @ganeshtata can do that, and they do not have much time to work on this project. So I am sure that some day a new version is released but it could take some time.

**Comment by pietermarsman** [comment]
I just got added as a collaborator on the pypi package of pdfminer. Also, @ganeshtata is being more active in the last couple of days so I expect that we will release a new version in the next week(s).

**Comment by keshavbohra** [comment]
Thanks for the help. 👍

**Comment by pietermarsman** [comment]
Done
