### ISSUE TITLE
Add requirements.txt file for developpers

### ISSUE THREAD

**Issue by pietermarsman** [pdfminer/pdfminer.six#299]
Dependencies for pdfminer are stated in various places:

- package dependencies are in `setup.py`
- test dependencies in `.travis.yml`
- some are never states, like the package Pillow that is used in [on line 87 in image.py](https://github.com/pdfminer/pdfminer.six/blob/41d1efac7ef3ac71164eeb8200af39a2bfa09c59/pdfminer/image.py#L87)

I think it is best to replace those with a single point of truth. We could use a requirements.txt file or a pipenv lock file.

**Comment by hugovk** [comment]
Please see https://github.com/pdfminer/pdfminer.six/pull/306 for an alternative.
