### ISSUE TITLE
Add LICENSE to MANIFEST?

### ISSUE THREAD

**Issue by pmlandwehr** [pdfminer/pdfminer.six#31]
Hey-lo,

I'm [building a version](https://github.com/conda-forge/staged-recipes/pull/1367#discussion_r76740176) of `PDFMiner.six` using [`conda`](http://conda.pydata.org) for [conda-forge](http://conda-forge.github.io). When possible, we try to include a link to the license file in the `meta.yaml` specification; doing so requires both:
- a license file be included in the package
- that license be indexed in [`MANIFEST.in`](https://docs.python.org/2/distutils/sourcedist.html#manifest-related-options) file.

Would you consider adding a copy of the license to the bundle and updating `MANIFEST.in` to include it?

**Comment by goulu** [comment]
I'd prefer if you could make a pull request with everything required for conda. Thanks !

**Comment by goulu** [comment]
Done. Thanks !
