### ISSUE TITLE
Use code-style enforcement

### ISSUE THREAD

**Issue by pietermarsman** [pdfminer/pdfminer.six#312]
A lot of files in this project don't follow [PEP8](https://www.python.org/dev/peps/pep-0008/). 

I would like to have some code-style enforcement in this project because (for me) it makes the code more readable and maintainable. 

I've earlier worded with [flake8](https://flake8.readthedocs.io/en/latest/faq.html) and think it works really well. 

Also see this earlier (closed) PR: https://github.com/pdfminer/pdfminer.six/pull/92.

**Comment by c4xuxo** [comment]
Will see when I can have a look into this.

**Comment by pietermarsman** [comment]
OK, nice! Also see #316 .
