### ISSUE TITLE
Added text colors to the loose html conversion

### ISSUE THREAD

**Issue by callesg** [pdfminer/pdfminer.six#337]
I was surprised to find that the html text had no colors after conversion. 
I made a patch to take the colors from the pdf and add them to the loose html conversion.

```diff
diff --git a/pdfminer/converter.py b/pdfminer/converter.py
index eaf0520..2087f40 100644
--- a/pdfminer/converter.py
+++ b/pdfminer/converter.py
@@ -346,13 +346,24 @@ class HTMLConverter(PDFConverter):
         self.write('</div>')
         return

-    def put_text(self, text, fontname, fontsize):
+    def cmyk_to_rgb(self, cmyk):
+        r = 255*(1.0-(cmyk[0]+cmyk[3]))
+        g = 255*(1.0-(cmyk[1]+cmyk[3]))
+        b = 255*(1.0-(cmyk[2]+cmyk[3]))
+        return r,g,b
+
+    def put_text(self, text, fontname, fontsize, textcolor):
         font = (fontname, fontsize)
         if font != self._font:
             if self._font is not None:
                 self.write('</span>')
-            self.write('<span style="font-family: %s; font-size:%dpx">' %
-                       (enc(fontname), fontsize * self.scale * self.fontscale))
+            htmlcolor = ""
+            if len(textcolor) == 4:
+                textcolor = self.cmyk_to_rgb(textcolor)
+            if len(textcolor) == 3:
+                htmlcolor = 'color: rgb(%s,%s,%s)'%(textcolor[0], textcolor[1], textcolor[2])
+            self.write('<span style="font-family: %s; font-size:%dpx;%s">' %
+                       (enc(fontname), fontsize * self.scale * self.fontscale, htmlcolor))
             self._font = font
         self.write_text(text)
         return
@@ -418,7 +429,7 @@ class HTMLConverter(PDFConverter):
                             render(child)
                         self.end_div('textbox')
                     elif isinstance(item, LTChar):
-                        self.put_text(item.get_text(), item.fontname, item.size)
+                        self.put_text(item.get_text(), item.fontname, item.size, item.graphicstate.ncolor)
                     elif isinstance(item, LTText):
                         self.write_text(item.get_text())
             return
```

**Comment by pietermarsman** [comment]
Hi @callesg, thanks for the suggestion and patch. 

I'm not sure what the big selling-point of the `HTMLConverter` is. Do you use the html output of pdfminer.six? What are you using it for?

**Comment by callesg** [comment]
My intention was to parse the text from the HTMLConverter. But after looking at it's results I changed my mind. It is so inaccurate that the output not really usefull. Maybe I could go look at the xml instead. See if I can convert it to HTML with an additional step.

As to the high level use, I have an idea about parsing course literature that I have in PDF format.

**Comment by pietermarsman** [comment]
> My intention was to parse the text from the HTMLConverter. 

So your goal is to get text? Than you should use `TextConverter`. 

> But after looking at it's results I changed my mind. It is so inaccurate that the output not really usefull. Maybe I could go look at the xml instead. See if I can convert it to HTML with an additional step.

Or do yo want the html? What do you need the markup for? 

I am asking this because HTML is one of the output options that we offer. However, *I think* this is nothing more than an example on how to use pdfminer.six for more advanced use cases. If you want to extract the colours you can do it by writing your own `PDFConverter`. (This would be a really good showcase in the documenation!)

For this reason I am not sure if we focus on extending the `PDFConverter`'s, or if we should prioritise improving the documentation to show how to create your own `PDFConverter`.

**Comment by callesg** [comment]
> Or do yo want the html? What do you need the markup for?
To differentiate headers from body text, based on what is coloured what is bold maybe even text location.

> For this reason I am not sure if we focus on extending the PDFConverter's, or if we should prioritise improving the documentation to show how to create your own PDFConverter.

Yeah, that makes sense.

Btw. while I was looking at this I could not find a way to do font extraction, and many of the images had an inverted colorsheme.
