### ISSUE TITLE
How to modify the content in PDF and  save as another PDF?

### ISSUE THREAD

**Issue by Jhy1993** [pdfminer/pdfminer.six#343]
I have a keyword and want to highlight all content contains this keyword. 
For example, 
<img width="666" alt="image" src="https://user-images.githubusercontent.com/12387434/70388917-2e22c780-19f3-11ea-9ab2-edd2c0d0361a.png">

**Comment by pietermarsman** [comment]
Hi @Jhy1993, 

Do I understand correctly that you want to modify a pdf? In that case, pdfminer.six will not suit your needs. It is created for reading PDF files and extracting its content. It cannot write PDF files or modify them in place.
