### ISSUE TITLE
Installation and use problem

### ISSUE THREAD

**Issue by starfriend10** [pdfminer/pdfminer.six#353]
Python 3.6.8; Windows 10; Anaconda 3. 
First, when I installed the lib using
`pip install pdfminer.six`
There is no "pdfminer.six" folder under the path "C:\ProgramData\Anaconda3\Lib\site-packages", it only has a folder "pdfminer" and a folder "pdfminer.six-20191110.dist-info"
Second, in the folder "pdfminer", it has 28 python files and one folder "cmap", no other folders (e.g. tools, samples, ...) (BTW, I found pdf2txt.py under path "C:\ProgramData\Anaconda3\Scripts"). Not sure if this is correct.

Therefore, when I ran 
`pdf2txt.py /BuffaloCl.pdf`

It gave an error:
```
Traceback (most recent call last):

  File "<ipython-input-5-93bc243ad3b0>", line 1, in <module>
    pdf2txt.py /BuffaloCl.pdf

NameError: name 'pdf2txt' is not defined
```

Suggestions and advice are welcome!
Thanks.

**Comment by pietermarsman** [comment]
Thanks for moving this question to a new issue.

It looks like you are running the code inside a python REPL, e.g. IPython.

Instead, you should run the file directly on the command line. For example:
python pdf2txt.py /BuffaloC1.pdf
```

The path to your pdf2txt.py seems right. The location is not really intuitive, this is addressed in issue #. 

If you want to interact programmatically with pdfminer.six, you can use the [high-level api](https://pdfminersix.readthedocs.io/en/latest/tutorials/highlevel.html). 

```commandline

**Comment by starfriend10** [comment]
@pietermarsman Thanks for your prompt reply. I have solved the problems and I can convert multiple PDFs to text by using some references. Please close this issue. Thank you again for developing this nice package.
