### ISSUE TITLE
Encrypted documents fail to load if Digital Signature is present

### ISSUE THREAD

**Issue by m2rtin** [pdfminer/pdfminer.six#354]
**Describe the bug**
Consider an encrypted PDF (one that has Encrypt dict in the trailer). If the password is empty and it is also digitally signed, pdfminer tries to decipher all strings and streams, however the **/Contents** entry in the digital signature dictionary (the signature value) is also deciphered. Which it should not be. Then the signature value can not be further processed and interpreted.
In some cases pdfminer even fails to decipher the hexadecimal value and crashes with "_Data must be padded to 16 byte boundary in CBC mode_" exception message.

**To Reproduce**

* Just call `PDFPage.get_pages` and see the crash on the file below:
* The File can be downloaded from:
https://uloz.to/file/hYCgVhuKIHsO/faktura-vs-515101458-vystavene-21012015-pdf

**Expected behavior**
I was unable to find the correct behavior within the PDF Reference 1.7, but I have seen tens of encrypted PDFs with digital signatures and none of them had the signature encrypted. I don't know if it is specific for the Contents entry in the digital signature dictionary or hexadecimal strings in general, but at least the signature value should not be decrypted.

There are other exceptions for deciphering, such as Identity filter in DecodeParams, used for XML metadata for example. But the concern of this Issue is the crash on this particular PDF.

**Comment by pietermarsman** [comment]
I need to log in to download the file. Could you try another method to share it?

**Comment by m2rtin** [comment]
Hi Pieter, thank You for the quick response!, no one needs to log in, it can be downloaded, it is the button below for slow speed download, here You go:
[https://uloz.to/file/hYCgVhuKIHsO/faktura-vs-515101458-vystavene-21012015-pdf?do=slowDirectDownload](url)

**Comment by Recursing** [comment]
[Faktúra VS- 515101458, vystavené- 21012015.PDF](https://github.com/pdfminer/pdfminer.six/files/4032564/Faktura.VS-.515101458.vystavene-.21012015.PDF)

For posterity

**Comment by Recursing** [comment]
Btw, I don't think I can reproduce:

```
>>> import pdfminer.high_level

>>> print(pdfminer.high_level.extract_text("Faktúra VS- 515101458, vystavené- 21012015.PDF"))
515101458#Spoločenstvo vlastníkov bytov - BRUSNÍK#220#1479#69/4#0#
...
...

**Comment by m2rtin** [comment]
Alright, sorry about that, you'll have to access the signature:

```
path = "Faktúra VS- 515101458, vystavené- 21012015.PDF"
with open(path, "rb") as fp:
    raw_bytes = fp.read()
    bytes = io.BytesIO(raw_bytes)
    pages = list(PDFPage.get_pages(bytes))
    signature = pages[0].doc.catalog['AcroForm']['Fields'][0].resolve()['V'].resolve()
```

**Comment by pietermarsman** [comment]
I used this code to reproduce: 

```python
from pdfminer.pdfpage import PDFPage

with open("/home/pieter/Downloads/issue-354.PDF", "rb") as fp:
    pages = list(PDFPage.get_pages(fp))
    signature = pages[0].doc.catalog['AcroForm']['Fields'][0].resolve()['V'].resolve()
```

Full stack trace: 

```
Traceback (most recent call last):
  File "/home/pieter/.PyCharm2019.3/config/scratches/scratch.py", line 7, in <module>
    signature = pages[0].doc.catalog['AcroForm']['Fields'][0].resolve()['V'].resolve()
  File "/home/pieter/Documents/Projects/pdfminer-upstream/pdfminer/pdftypes.py", line 70, in resolve
    return self.doc.getobj(self.objid)
  File "/home/pieter/Documents/Projects/pdfminer-upstream/pdfminer/pdfdocument.py", line 686, in getobj
    obj)
  File "/home/pieter/Documents/Projects/pdfminer-upstream/pdfminer/pdftypes.py", line 111, in decipher_all
    x[k] = decipher_all(decipher, objid, genno, v)
  File "/home/pieter/Documents/Projects/pdfminer-upstream/pdfminer/pdftypes.py", line 106, in decipher_all
    return decipher(objid, genno, x)
  File "/home/pieter/Documents/Projects/pdfminer-upstream/pdfminer/pdfdocument.py", line 447, in decrypt
    return self.cfm[name](objid, genno, data)
  File "/home/pieter/Documents/Projects/pdfminer-upstream/pdfminer/pdfdocument.py", line 457, in decrypt_aes128
    return AES.new(key, mode=AES.MODE_CBC, IV=data[:16]).decrypt(data[16:])
  File "/home/pieter/.local/share/virtualenvs/pdfminer-upstream-C1xj1ulz/lib/python3.7/site-packages/Crypto/Cipher/_mode_cbc.py", line 246, in decrypt
    raise ValueError("Data must be padded to %d byte boundary in CBC mode" % self.block_size)
ValueError: Data must be padded to 16 byte boundary in CBC mode
```

@m2rtin, it will take some time to look into this. But your issue is noted and we will fix it :)

**Comment by pietermarsman** [comment]
The issue is gone in the current release. 

I suspect the https://github.com/pdfminer/pdfminer.six/pull/456 PR has fixed this, because it changes the encryption package that pdfminer.six uses.
