### ISSUE TITLE
Unable to run using Anaconda

### ISSUE THREAD

**Issue by abhargava88** [pdfminer/pdfminer.six#355]
I've tried everything I can think of... no luck. Using anaconda DS on windows 10, running through the anaconda prompt.

Steps I've tried:

 1.   I created a new virtual environment "PDFMiner" in C:\Users\MYUSERNAME\.conda\envs\pdfminer

2. The environment, when created, has no packages in it as confirmed by "conda list"

3. I ran "pip install pdfminer.six" and let it install whatever it needed.

 4. From here: https://pdfminersix.readthedocs.io/en/latest/tutorials/commandline.html I tried running " python tools/pdf2txt.py example.pdf " and I get an error - "python: can't open file 'tools/pdf2txt.py': [Errno 2] No such file or directory"

Thanks in advance.

**Comment by pietermarsman** [comment]
The pdf2txt.py is actually in a different different location. We have another issue for this: #217 . 

If you want to get this to work, you should probably use something like this: 

```commandline
python C:\Users\USERNAME.conda\envs\pdfminer\bin\pdf2txt.py example.pdf
```
