### ISSUE TITLE
Error running command pdf2txt.py

### ISSUE THREAD

**Issue by AyeshaSarwar** [pdfminer/pdfminer.six#365]
pdf2txt.py "D:/test.pdf"
I am trying to run this simple command.
No matter which verison I use it is giving the same error

*pdf2txt.py: error: the following arguments are required: files

python version 3.8.1
Windows 10

I need some urgent help
Thanks

**Comment by AyeshaSarwar** [comment]
NO matter how I write the command, I am getting the same error

**Comment by abhishek-27** [comment]
You need to use it like this. `python pdf2txt.py samples/simple1.pdf`

Make sure you have already installed it using pip or either built it from the source code.
`pip install pdfminer.six`
 
The python version needs to be greater than v3.4.0

**Comment by AyeshaSarwar** [comment]
Is it ok that it is running from my administrative power shell but not from command prompt on windows?

**Comment by abhishek-27** [comment]
I am not an active Windows user but I think it should even work in Powershell. 

Assuming you have Python installed. In case you still face an issue, I will suggest you use either `virtualenv` or `pipenv` to setup your python environment and then do `pip install pdfminer.six` after activating the virtualenv.  `source <path-to-venv>/bin/activate`.

**Comment by AyeshaSarwar** [comment]
It is working in power shell but not in cmd
