### ISSUE TITLE
Make configurable the amount of intermediate spaces to be inserted to separate words in line

### ISSUE THREAD

**Issue by Ev2geny** [pdfminer/pdfminer.six#366]
### Current functionality

> If characters are on the same line but not part of the same word, an intermediate space is inserted.
[https://pdfminersix.readthedocs.io/en/latest/api/composable.html#laparams](url)

### What is the issue with current functionality
If words themself contain spaces (e.g. number contains space as a decimal separator ) then when such PDF file is converted to text, it becomes difficult to separate different words (e.g. numbers) from each other 

### What is desired improvement
Make configurable the amount of intermediate spaces to be inserted to separate words in line (with the default equal to 1)

**Comment by pietermarsman** [comment]
You don't have to use the string representation of the layout analysis. 

Some alternatives are:
- use `high_level.extract_pages()` to get a list of `LTPage` object that contain a hierarchy of `LTComponent`s
- Create your own extention of `PDFDevice` and use it to render the content of the pdf in a way you like.

**Comment by Ev2geny** [comment]
pietermarsman, thank you for your feedback.

Can you point me the right direction on creating own extention of PDFDevice? Are there  and examples?

**Comment by jstockwin** [comment]
Hey @Ev2geny,
I'm not an expert on doing this, but I think you could follow [this example](https://pdfminersix.readthedocs.io/en/latest/tutorial/composable.html#) from the docs, but you can create your own `TextConverter` class.

If you look at the [existing one](https://github.com/pdfminer/pdfminer.six/blob/develop/pdfminer/converter.py#L184), you should be able to extend from that, and perhaps override the `receive_layout` function to write some additional spaces after writing each `LTText` item.

**Comment by Ev2geny** [comment]
I have found, that it is quite easy to add requested functionality to the code and the changes are backwards compatible.

So, I have created a pull request: https://github.com/pdfminer/pdfminer.six/pull/468

**Comment by Ev2geny** [comment]
With the reference to the  comment from @pietermarsman  in https://github.com/pdfminer/pdfminer.six/pull/468#issuecomment-690549778 I am reopening the issue (At least trying)

I must say I am not sure, I understand what is what you mean that I have to implement functionality using an (extension of) PDFDevice?

I was looking for a place in the code, where at the moment this intermediate space is inserted between words, If two characters on the same line are further apart than **LAParams.word_margin**. 

And the only place I found was this [line.](https://github.com/pdfminer/pdfminer.six/blob/a83f853de709b44b7dbe0f03865829118b6fae53/pdfminer/layout.py#L425)

So, I thought it was logical  to use it to insert more than 1 space.  

Can you elaborate more on your suggestion?

**Comment by pietermarsman** [comment]
The structure of pdfminer.six is divided into a couple of components. 

- The `PDFDocument` represents the PDF in the language of PDF 
- The `PDFInterpreter` represents the PDF as text (and figure) objects with x and y positions (and more properties). The `LAParams` govern this representation.
- The `PDFDevice` represents the PDF as another output format. E.g. as text, html or xml. 

So the `PDFDevice` is responsible for formatting the internal pdfminer.six reprentation (of `PDFInterpreter`) as something that the user wants. And since this issue is about formatting the output, a solution to this issue should change the `PDFDevice` not the `PDFInterpreter`. 

Makes sense now? Let me know if you have any questions.

**Comment by Ev2geny** [comment]
@pietermarsman , thanks for explanation. It makes sense what you said, but when I look at the code, I see, that this already existing specific functionality of separating words by a single space is implemented outside of  ```PDFDevice```.  Namely ```PDFLayoutAnalyzer``` (which inherits from ```PDFDevice```) calls method **analyze** of the **LTLayoutContainer** [here](https://github.com/pdfminer/pdfminer.six/blob/0b44f7771462363528c109f263276eb254c4fcd0/pdfminer/converter.py#L52), which in turn calls **LTLayoutContainer.group_objects()** [here](https://github.com/pdfminer/pdfminer.six/blob/0b44f7771462363528c109f263276eb254c4fcd0/pdfminer/layout.py#L795), which in turn calls **LTTextLineHorizontal.add()**,  where the functionality to optionally add a single space to separate words based on the **word_margin** [is implemented](https://github.com/pdfminer/pdfminer.six/blob/0b44f7771462363528c109f263276eb254c4fcd0/pdfminer/layout.py#L425). So, in my PR https://github.com/pdfminer/pdfminer.six/pull/468 I simply extended this existing functionality to be able to separate words with more than one space.

The code is already there, I simply slightly extended it. 

Doesn't it make sense to  use existing code to slightly modify existing functionality?

**Comment by Ev2geny** [comment]
@pietermarsman , did you manage to look at my comments / question?

**Comment by pietermarsman** [comment]
Sorry, did not see this earlier. 

It does not add a intermediate space, it adds a `LTAnno(' ')` object to the representation of the document. This `LTAnno` object represents a space between words. With the `TextConverter` this object is also displayed as a single space. The `LTAnno` object is repsonsible for _representing_ a space, the `PDFDevice` (`TextConverter` in my example) is responsible for displaying the space. If you want to display the concept of a space differently, e.g. by using 2 or more unicode space characters, then you should create your own `PDFDevice`. 

I hope my explanation makes sense. I'm happy to continue to discuss this. But I'm very sure that changing a `PDFDevice` is the way to go if you want to do custom formatting of the internal PDF representation. 

Can you maybe explain the context you are in? Why are you trying to insert multiple spaces? What other solutions have you tried? Can you give an example document? This would help me to understand your use case better.

**Comment by Ev2geny** [comment]
> Can you maybe explain the context you are in? Why are you trying to insert multiple spaces? What other solutions have you tried? Can you give an example document? This would help me to understand your use case better.

The specific problem I am trying to solve is that if PDF  contains numbers, which use space as a thousand separator, then it is very difficult to process such document afterwards, as such numbers gets separated as if they were different words
See example in [very_simple_excel.pdf](https://github.com/pdfminer/pdfminer.six/files/5471707/very_simple_excel.pdf)

If I use the following code to extract document to txt

```py
from pdfminer.high_level import extract_text
from pdfminer.layout import LAParams

print(extract_text('very_simple_excel.pdf', laparams=LAParams(char_margin=18, boxes_flow=None)))
```

then I get the following result
```
Some_word 3 296.79
```

What I need however is something like this:

```
Some_word   3 296.79
```

Can you think of any better solution, then updating PDF miner to insert more than one space as a word separator?

**Comment by pietermarsman** [comment]
In that case I would change the `receive_layout()` method of `TextConverter` like @jstockwin suggested [here](https://github.com/pdfminer/pdfminer.six/issues/366#issuecomment-667891550). 

For example: 

```python
from io import StringIO

from pdfminer.converter import TextConverter
from pdfminer.layout import LTContainer, LTText, LTTextBox, LTImage, LTAnno, LAParams
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.pdfpage import PDFPage
from pdfminer.utils import open_filename


class TextWithSpaceConverter(TextConverter):
    def __init__(self, rsrcmgr, outfp, codec='utf-8', pageno=1, laparams=None,
                 showpageno=False, imagewriter=None, number_of_spaces=1,
                 number_of_enters=1):
        super().__init__(rsrcmgr, outfp, codec, pageno, laparams, showpageno,
                         imagewriter)
        self.number_of_spaces = number_of_spaces
        self.number_of_enters = number_of_enters

    def receive_layout(self, ltpage):
        def render(item):
            if isinstance(item, LTContainer):
                for child in item:
                    render(child)
            elif isinstance(item, LTAnno):
                text = item.get_text()
                if text == ' ':
                    self.write_text(text * self.number_of_spaces)
                else:
                    self.write_text(text * self.number_of_enters)
            elif isinstance(item, LTText):
                self.write_text(item.get_text())
            if isinstance(item, LTTextBox):
                self.write_text('\n')
            elif isinstance(item, LTImage):
                if self.imagewriter is not None:
                    self.imagewriter.export_image(item)
        if self.showpageno:
            self.write_text('Page %s\n' % ltpage.pageid)
        render(ltpage)
        self.write_text('\f')
        return


if __name__ == '__main__':
    N_SPACES = 5
    PDF_FILE = 'samples/simple1.pdf'
    with open_filename(PDF_FILE, "rb") as fp, StringIO() as output_string:
        rsrcmgr = PDFResourceManager()
        device = TextWithSpaceConverter(rsrcmgr, output_string,
                                        laparams= LAParams(),
                                        number_of_spaces=N_SPACES)
        interpreter = PDFPageInterpreter(rsrcmgr, device)

        for page in PDFPage.get_pages(fp):
            interpreter.process_page(page)

        print(output_string.getvalue())
```

With `N_SPACES = 1` this prints:

```
Hello 

World

Hello 

World

H e l l o  

W o r l d

H e l l o  

W o r l d
```

And with `N_SPACES = 2` this prints:

```
Hello 

World

Hello 

World

H     e     l     l     o      

W     o     r     l     d

H     e     l     l     o      

W     o     r     l     d
```

**Comment by Ev2geny** [comment]
Ok, thanks, for a hint, it works. 
I must say the object-oriented design of pdfminer is still beyond my amature comprehension.

In any case, don't you think that the functionality I require is generic enough to be included in the standard release? It is quite often when that you get a space as a thousands separator.

**Comment by Ev2geny** [comment]
@pietermarsman , sorry for coming back to this, but don't you think, that this functionality I requested is generic enough to be included in the standard release? 
Are you OK if I create a PR, based on your code?

**Comment by pietermarsman** [comment]
Hi @Ev2geny,

IMHO the configurable amount of spaces is not generic enough to be part of the package. There are many more conceivable features like this. For example, adding spaces between characters of different fonts or font-sizes, or adding more advanced layout techniques for recognizing tables, or recognizing structured data in the output like bank account numbers, etc. For these user and domain specific use cases pdfminer.six exposes the composable api. This can be used to adjust any of the components of pdfminer.six to your own needs.

**Comment by Ev2geny** [comment]
Hi @pietermarsman , thanks for a feedback

I still think, that adding functionality   to be able to configure qnt of spaces between words is somehow different from the list of  conceivable additional features you mentioned. As my request is not for a new feature, but for the modification of the existing hard coded functionality (which is one space as a words separator). 

In your example for instance you had to re-write a big chunk of  the ```TextConverter``` class, which does not sound like using API. What if in the next release somebody updates this class in the part, which was re-written? The code may stop functioning afterwards.. 

In any case, I think a formal API description would greatly help, but I believe this is on the roadmap already any way.

**Comment by pietermarsman** [comment]
Closing this because this feature will not be added. This is too specific to add to our code base and the composable api can be used to implement this yourself.
