### ISSUE TITLE
pdfminer has  no attribute high_level

### ISSUE THREAD

**Issue by CholoeMoretz** [pdfminer/pdfminer.six#367]
**Describe the bug**
I'm trying to use pdfminer to extract some pdf files,it's excutable in macOs commandline by using the example showing in the main page of this project.
However,when I try to use it in python3.7, it shows "'pdfminer' has no attribute 'high_level'"

**To Reproduce**
import os
text = pdfminer.high_level.extract_text('20190318.pdf')

**Expected behavior**
extraction sucess

**Comment by pietermarsman** [comment]
Did you import high_level?

```python
import pdfminer.high_level
```
