### ISSUE TITLE
Tables drawn from single path is converted to curve instead of rects

### ISSUE THREAD

**Issue by cheungpat** [pdfminer/pdfminer.six#369]
**Describe the bug**

When using Excel and Print to PDF function, borders from the generated PDF cannot be converted to HTML output. When converting to XML output, the borders become `<curve>` instead of `<rect>`.

It appears that the borders are rendered as a single path and hence it is interpreted as a curve instead of a rect.

**To Reproduce**

Run `pdf2txt.py -t html output.pdf > output.html`.

[output.pdf](https://github.com/pdfminer/pdfminer.six/files/4161100/output.pdf)

output.html: (some borders are missing)

<img width="178" alt="Screenshot 2020-02-06 at 1 39 30 AM" src="https://user-images.githubusercontent.com/170071/73867356-89512900-4881-11ea-8177-2131c2baaae0.png">

When converting to xml, the borders become `<curve>` instead of `<rect>`.

**Expected behavior**

output.html: (borders should be shown)
<img width="177" alt="Screenshot 2020-02-06 at 1 39 48 AM" src="https://user-images.githubusercontent.com/170071/73867397-98d07200-4881-11ea-9f74-ea96dee4a740.png">

**Comment by pietermarsman** [comment]
Thanks for raising this issue!

I'll review your PR and see if we can merge it.
