### ISSUE TITLE
self.__interpreter.process_page(page) taking very long time

### ISSUE THREAD

**Issue by dhavalsp** [pdfminer/pdfminer.six#370]
**Describe the bug**
I am creating API using pdfminer.six in flask. I am reading text with bbox. But, following the line of code taking very long time to run. 

`self.__interpreter.process_page(page)`

this line of code taking 7-8 sec in my all program. 

The same program is not taking too long time without a flask and class structure. I have created a program as a class and function. I am calling in API as a class object. but, getting very poor performance. Taking 8-9 sec to execute it.

**Comment by pietermarsman** [comment]
Hi @dhavalsp,

We cannot help you with integrating pdfminer.six into other applications. If you have issues with a specific pdf or if you want to report a bug or slow performance: open a new issue with more information about that.
