### ISSUE TITLE
Text Attribute from LTTextLineHorizontal (LTTextBox)

### ISSUE THREAD

**Issue by ybml** [pdfminer/pdfminer.six#374]
I can't access the text attribute of an LTTextLineHorizontal object. I can get the text via `get_text()`, but I can't write into the text attribute. 

E.g., I've written all LTTextBox objects  (`obj`) of a document into a list. I now want to go over these objects and clean them. It's possible to access all attributes with e.g. obj.y1, but not the text. I can get the text with `obj.get_text()` but not access it. When I call `obj._objs[0]`I get the LTTextLineHorizontal object, but still don't know how to access the text attribute and work on it.

**Comment by pietermarsman** [comment]
> I can't access the text attribute of an LTTextLineHorizontal object. I can get the text via `get_text()`, but I can't write into the text attribute.

A `LTTextLineHorizontal` object is a hierarchical grouping of objects that contain text. The `LTTextLineHorizontal` object itself does not contain any text. The `LTTextLineHorizontal.get_text()` method only concattenates the text from its children. That is why you cannot write to any text attribute. 

> E.g., I've written all LTTextBox objects (`obj`) of a document into a list. I now want to go over these objects and clean them. It's possible to access all attributes with e.g. obj.y1, but not the text. I can get the text with `obj.get_text()` but not access it. When I call `obj._objs[0]`I get the LTTextLineHorizontal object, but still don't know how to access the text attribute and work on it.

If you want to work with the text, I would recommend extracting the text from the LT*` objects and store the result in a list or dict structure. That way you can manipulate the result without having to write the values to any `LT*` object.
