### ISSUE TITLE
I have some algorithms written for superscript and subscript support, but I need a bit of help

### ISSUE THREAD

**Issue by TercioOfParma** [pdfminer/pdfminer.six#376]
Hi,

I wrote up a couple of algorithms on paper to handle superscripts and subscripts, but I am having issues understanding the library such that I can put the solutions in the right place.

I think that the characters themselves are ascertained in PDFPageInterpreter, but I am not sure precisely which function. In order to detect and take super and subscripts into account, I need to know where precisely the characters are read and where I can get the cursor position. 

The cursor position is integral to the algorithm actually working, so some help getting the codebase would be appreciated.

Thanks.

**Comment by pietermarsman** [comment]
Hi @TercioOfParma, are you asking how to extract characters from a PDF using pdfminer.six? You could take a look at our [documentation](https://pdfminersix.readthedocs.io/en/latest/index.html) and try to reproduce some of the examples.

**Comment by TercioOfParma** [comment]
Don't worry, I implemented it on my own. I created the change such that LaTeX commands for these are replicated in the code.
