### ISSUE TITLE
PDFminer only works if PDF is first made searchable

### ISSUE THREAD

**Issue by b00kgrrl** [pdfminer/pdfminer.six#377]
I would like to extract text from PDF files using PDFminer and Jupyter Notebook. 

[Here](https://www.dropbox.com/s/6lmupe3dyunfgfk/test.pdf?dl=0) is an example of a PDF file from which I would like to extract text.  When I use the code posted [here](https://stackoverflow.com/questions/26494211/extracting-text-from-a-pdf-file-using-pdfminer-in-python), the output contains only the page one footer, while the rest of the document gets missed.

However, if I first use the [Nitro Pro](https://www.gonitro.com/) OCR functionality to manually make the file searchable, I am able to subsequently use the above Python code to extract all the text from the file.

I checked the PDFminer documentation to see if there is a parameter that I'm setting incorrectly, but I couldn't find anything on this issue. I would like to convert many files, so using the Nitro Pro tool manually is not feasible.

**Comment by jvalls-axa** [comment]
Hi @b00kgrrl 

Your sample only contains on line of text in first page that is the one pdfMiner gives you as output.

All pages in your sample only contains images but unfortunately pdfMiner is not an OCR tool.

**Comment by pietermarsman** [comment]
> However, if I first use the [Nitro Pro](https://www.gonitro.com/) OCR functionality to manually make the file searchable, I am able to subsequently use the above Python code to extract all the text from the file.

That is correct! Pdfminer.six directly looks into the sourcecode of the PDF and extracts text from that. It does not do any kind of OCR on images or scans.

**Comment by zoj613** [comment]
> > However, if I first use the [Nitro Pro](https://www.gonitro.com/) OCR functionality to manually make the file searchable, I am able to subsequently use the above Python code to extract all the text from the file.
> 
> That is correct! Pdfminer.six directly looks into the sourcecode of the PDF and extracts text from that. It does not do any kind of OCR on images or scans.

does it not at least let you extract the image data to use outside of pdfminer? If so then, how? I dont think I have seen any examples showing how to get the image data out of the pdf if it exists

**Comment by pietermarsman** [comment]
Hi @zoj613. Pdfminer.six can be used to extract image data. If you want extra documentation, please open a new issue.

**Comment by ya-stack** [comment]
How to make Custom PDF Searchable using Python for PDFMiner?
Any help would be highly appreciated.

Thanks in advance!
