### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by AlexandreGalois** [pdfminer/pdfminer.six#38]
I am using python 2.7.10. When running the following code I get a unicodedecodeerror

This is the code:

`
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
from StringIO import StringIO 

rsrcmgr = PDFResourceManager()
retstr = StringIO()
laparams = LAParams()
device = TextConverter(rsrcmgr, retstr, codec='utf-8', laparams=laparams)
fp = file('c:\users\public\data\pdfs\policy.pdf', 'rb')
interpreter = PDFPageInterpreter(rsrcmgr, device)
password = ""
maxpages = 1
caching = True
pagenos=set()

for page in PDFPage.get_pages(fp, pagenos, maxpages=maxpages,   password=password,caching=caching, check_extractable=True):
    interpreter.process_page(page)

text = retstr.getvalue()

fp.close()
device.close()
`

And this is the error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Public\Public Software\WinPython32\python-2.7.10\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 790, in runfile
    execfile(filename, namespace)
  File "C:\Users\Public\Public Software\WinPython32\python-2.7.10\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 77, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/Public/Public Software/WinPython32/python-2.7.10/Scripts/pdfextract.py", line 28, in <module>
    text = retstr.getvalue()
  File "C:\Users\Public\Public Software\WinPython32\python-2.7.10\lib\StringIO.py", line 272, in getvalue
    self.buf += ''.join(self.buflist)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)`

After some digging, turns out the problem is that in PDFConverter the following thing happens:

`class PDFConverter(PDFLayoutAnalyzer):

    def __init__(self, rsrcmgr, outfp, codec='utf-8', pageno=1, laparams=None):
        PDFLayoutAnalyzer.__init__(self, rsrcmgr, pageno=pageno, laparams=laparams)
        self.outfp = outfp
        self.codec = codec
        if hasattr(self.outfp, 'mode'):
            if 'b' in self.outfp.mode:
                self.outfp_binary = True
            else:
                self.outfp_binary = False
        else:
            import io
            if isinstance(self.outfp, io.BytesIO):
                self.outfp_binary = True
            elif isinstance(self.outfp, io.StringIO):
                self.outfp_binary = False
            else:
                try:                    
                    self.outfp.write(u"é)  
                    self.outfp_binary = False
                except TypeError:
                    self.outfp_binary = True
        return`

As I am using StringIO from StringIO; the buflist in my StringIO object ends up with the u'é' entry which is unicode type. Later in the code when it is writing from the PDF to this array it writes str types. This mixing causes StringIO to throw a UnicodeDecodeError when it tries to join them all (in the getvalues() call).

I'm not that pro with Python, I managed to get it working by replacing the particular line by:

self.outfp.write(u"é".encode(codec,'ignore'))

But maybe this defeats the purpose of the line (?). 

I found a post on StackOverflow with some information that I thought was relevant:

http://stackoverflow.com/questions/5701372/what-caused-this-traceback

**Comment by vstoykov** [comment]
Hello @AlexandreGalois, may I suggest you to edit your issue description in order code to be more readable. You can use
````
```
Some code here
```
````

Then in order to fix your code you can try to import `StringIO` from `io` module.
```
from io import StringIO
```

do not use `cStringIO` or `StringIO` modules, they are for Python 2.5 compatibility. From Python 2.6 and up `io` module is preferable (because this is the only module in Python3).

**Comment by goulu** [comment]
@AlexandreGalois is it ok ? Please reopen if not.

**Comment by michi88** [comment]
Ran into this issue as well.

When passing `io.StringIO` in python 2, self.outfp_binary is False but `text` in `def write_text` is `six.binary_type` and thus fails.

```python
class TextConverter(PDFConverter):

    def __init__(self, rsrcmgr, outfp, codec='utf-8', pageno=1, laparams=None,
                 showpageno=False, imagewriter=None):
        PDFConverter.__init__(self, rsrcmgr, outfp, codec=codec, pageno=pageno, laparams=laparams)
        self.showpageno = showpageno
        self.imagewriter = imagewriter
        return

    def write_text(self, text):
        text = utils.compatible_encode_method(text, self.codec, 'ignore')
        if six.PY3 and self.outfp_binary:
            text = text.encode()
        self.outfp.write(text)
        return

...
```

It only works with BytesIO.

`text` should probably be decoded when output is not `self.outfp_binary`.

Hack to get it working is:

```
def extract_text_from_pdf(pdf_file):
    out = io.BytesIO()
    pdfminer.high_level.extract_text_to_fp(pdf_file, out, codec='utf-8')
    out.seek(0)
    return out.read().decode('utf-8')
```
