### ISSUE TITLE
how to collect font list from pdf file

### ISSUE THREAD

**Issue by longbowking** [pdfminer/pdfminer.six#380]
`pdffonts` can collect all fonts in a pdf file, [Link](https://stackoverflow.com/questions/11820241/)

```bash
pdffonts bash-manpage.pdf 

  name                            type          encoding        emb sub uni object ID
  ------------------------------- ------------- --------------- --- --- --- ---------
  Times-Roman                     Type 1        Custom          no  no  no       8  0
  Times-Bold                      Type 1        Standard        no  no  no       9  0
  Helvetica                       Type 1        Custom          no  no  no      11  0
  Helvetica-Bold                  Type 1        Standard        no  no  no      30  0
```
Can we get pdf fonts with pdfminer ?

**Comment by pietermarsman** [comment]
Great question! I am not sure how to do it, but it should be possible with pdfminer.six. If anyone finds a solution, I am more than happy to add it to our documentation.

**Comment by jstockwin** [comment]
The following code should get the names for you. Note most of the code is fairly standard to just use PDFMiner.

Also note that a text box can have multiple fonts, and this gets them all. I've seen cases where e.g. bullet points are their own font at the start of a textbox.

The code can probably be improved to be more efficient, this is meant as an example only.

```
from pdfminer import converter, pdfdocument, pdfinterp, pdfpage, pdfparser
from pdfminer.layout import LTTextContainer, LAParams

path_to_file = "test.pdf"

fonts = set()

with open(path_to_file, "rb") as pdf_file:
    # Standard PDF miner style code to extract data from PDF
    parser = pdfparser.PDFParser(pdf_file)
    document = pdfdocument.PDFDocument(parser)
    resource_manager = pdfinterp.PDFResourceManager()
    device = converter.PDFPageAggregator(resource_manager, laparams=LAParams())
    interpreter = pdfinterp.PDFPageInterpreter(resource_manager, device)
    for page in pdfpage.PDFPage.create_pages(document):
        interpreter.process_page(page)
        results = device.get_result()

        # Get all the LTTextContainers
        elements = [
            element for element in results if isinstance(element, LTTextContainer)
        ]

        for element in elements:
            # An LTTextContainer element can be iterated through to give the LTTextLines
            # and the LTTextLines can be iterated through to get LTChars, which have
            # fontname.
            fonts |= set(
                [
                    character.fontname
                    for line in element
                    for character in line
                    if hasattr(character, "fontname")
                ]
            )
device.close()

print(fonts)

```

**Comment by pietermarsman** [comment]
I've used `high_level.extract_pages()` to minimize @jstockwin 's example: 

```
from pdfminer.high_level import extract_pages
from pdfminer.layout import LTTextContainer

done = set()
for page_layout in extract_pages("test.pdf"):
    for element in page_layout:
        if isinstance(element, LTTextContainer):
            for text_line in element:
                for character in text_line:
                    if hasattr(character, 'fontname') \
                            and character.fontname not in done:
                        done.add(character.fontname)
                        print(character.fontname)
```

As a side note: this output is different that `pdffonts`. This prints all the fonts that are used in characters, while `pdffonts` prints all the fonts (with addititional properties) that are defined in a PDF.

**Comment by jstockwin** [comment]
Closing this as I believe the question has been answered. Feel free to comment or re-open if you disagree.

**Comment by floyddcn** [comment]
> The following code should get the names for you. Note most of the code is fairly standard to just use PDFMiner.
> 
> Also note that a text box can have multiple fonts, and this gets them all. I've seen cases where e.g. bullet points are their own font at the start of a textbox.
> 
> The code can probably be improved to be more efficient, this is meant as an example only.
> 
> ```python
> from pdfminer import converter, pdfdocument, pdfinterp, pdfpage, pdfparser
> from pdfminer.layout import LTTextContainer, LAParams
> 
> path_to_file = "test.pdf"
> 
> fonts = set()
> 
> with open(path_to_file, "rb") as pdf_file:
>     # Standard PDF miner style code to extract data from PDF
>     parser = pdfparser.PDFParser(pdf_file)
>     document = pdfdocument.PDFDocument(parser)
>     resource_manager = pdfinterp.PDFResourceManager()
>     device = converter.PDFPageAggregator(resource_manager, laparams=LAParams())
>     interpreter = pdfinterp.PDFPageInterpreter(resource_manager, device)
>     for page in pdfpage.PDFPage.create_pages(document):
>         interpreter.process_page(page)
>         results = device.get_result()
> 
>         # Get all the LTTextContainers
>         elements = [
>             element for element in results if isinstance(element, LTTextContainer)
>         ]
> 
>         for element in elements:
>             # An LTTextContainer element can be iterated through to give the LTTextLines
>             # and the LTTextLines can be iterated through to get LTChars, which have
>             # fontname.
>             fonts |= set(
>                 [
>                     character.fontname
>                     for line in element
>                     for character in line
>                     if hasattr(character, "fontname")
>                 ]
>             )
> device.close()
> 
> print(fonts)
> ```

i tried the code above but failed to extract bold info in char fonts .here is my screenshot,i draw a yellow circle to the Bold ones.
![image](https://user-images.githubusercontent.com/48442748/150796397-dfab4834-3735-4980-a836-2ee7dc0fd903.png)
here is my pdf file
[](url
[600000_2018_n-15.pdf](https://github.com/pdfminer/pdfminer.six/files/7926035/600000_2018_n-15.pdf)
)
