### ISSUE TITLE
pdf2txt.py - Missed figure texts

### ISSUE THREAD

**Issue by jvalls-axa** [pdfminer/pdfminer.six#381]
**Describe the bug**
Looks like texts in figures are missed since release '20191107' because older versions properly provide text in figures.

**To Reproduce**

1. Using pdfMiner >= 20191107
2. Download [PDF](https://www.icann.org/en/system/files/files/participating-08nov13-en.pdf)
2. Execute `pdf2txt.py -p 9 -c utf-8 -t xml -o outPut.xml input.pdf`
3. outPut.xml has no text elements in figures of page 9

**Expected behavior**
outPut.xml should contain text in figures as `pdfminer.six==20191020` does

**Comment by jvalls-axa** [comment]
Tracking commits after 20191020 release I found this [commit](https://github.com/pdfminer/pdfminer.six/commit/bc034c8e59d90e9b2cb8697a1d2fe9a33401761e) making missed text figures

**Comment by pietermarsman** [comment]
Hi @jvalls-axa, thanks for raising the issue! 

Could you try adding `--all-texts` to the command? This is the `pdf2txt.py` flag that signals that pdfminer.six should also extract text from figures. For example: 

```shell script
pdf2txt.py -p 9 -c utf-8 -t xml -o outPut.xml --all-texts input.pdf
```

**Comment by jvalls-axa** [comment]
Hi @pietermarsman 

I tried --all-texts & -A (that is documented as default true) before opening the issue but unfortunately it doesn't work.

**Comment by pietermarsman** [comment]
To bad. I'll look in to this.

**Comment by pietermarsman** [comment]
I did some research. On bc034c8e59d90e9b2cb8697a1d2fe9a33401761e the default value in pdf2txt.py changed from `False` to `True`. Since the action is `"store_true"` you cannot really change the value anymore. 

Strangly enough, if the value is `False`, then the content of figures is printed. If the value is `True` the content of figures is analyzed, but not printed. I still need to figure out how that works.

**Comment by pietermarsman** [comment]
I figured out what's going wrong. It is actually a problem with the pdf you are sharing. The Figure has a bounding box that is much smaller than the text that is inside it. It is `(52, 649, 575.72, 691.02)` (x0, y0, x1, y1) while the text covers the whole page. 

This is only a problem when layout analysis is done. During layout analysis all the components of a PDF are reordered such that they likely form readable text. To do this, the algorithm often needs to find neighboring bounding boxes. To make this computationally feasible it uses a grid of 50 x 50 grid boxes within its parents bounding box, and assigns all the children components to a grid box if part of the child bounding box overlays with the grid bounding box. 

However, if the bounding box of the parent is wrong, none of the child bounding boxes gets assigned to any of the grid bounding boxes. And thus, no neighbor is ever found. Currently,  the `LTLayoutContainer.group_textlines()` does not deal with this case and returns and skips the text components without neighbors. 

This is a special case that we should deal with in `LTLayoutContainer.group_textlines()`.

**Comment by pietermarsman** [comment]
I've created a fix for this. @jvalls-axa Could you have a look at the changes in `LTLayoutContainer.group_textlines()` and verify that I did not introduce another bug?

**Comment by jvalls-axa** [comment]
Hi @pietermarsman  

Seems like all my test dataset works fine with your fix.

When will you release a new version ?? 😊

Thanks!
