### ISSUE TITLE
gh-pages missing

### ISSUE THREAD

**Issue by Nothing4You** [pdfminer/pdfminer.six#39]
Hey there,

in the github project description you're linking to https://goulu.github.io/pdfminer/, that page doesn't exist.

**Comment by goulu** [comment]
Right. https://euske.github.io/pdfminer/ is a bit old, we should make a newer page for the new "pdfminder" group owner

**Comment by pietermarsman** [comment]
This was fixed 2,5 years ago by 7c96fe29ed36b8e3b1eaf5e7a42b65c03d5a3a91
