### ISSUE TITLE
Allow calling high level functions with file-like objects

### ISSUE THREAD

**Issue by jstockwin** [pdfminer/pdfminer.six#392]
**Feature request**

Some of the functions (`extract_text` and `extract_pages`) in [high_level.py](https://github.com/pdfminer/pdfminer.six/blob/develop/pdfminer/high_level.py) take `pdf_file` as a parameter, the path to the pdf file. This means the PDF file must be on the hard drive.

It would be nicer if there were functions available which allowed any file-like object (like `extract_text_to_fp` does). This means I can still call the functions even if the PDF isn't on my hard drive.

I would guess we don't want breaking changes to the existing functions (?), so will create new `*_from_io` functions, and then the API for the existing ones will be unchanged.

**Comment by pietermarsman** [comment]
I thought you were going to do something like [this `read_csv()` method in pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). You can pass a path or a file-like object. So the user does not need to learn a new method if (s)he wants the same functionality.

**Comment by pietermarsman** [comment]
> I would guess we don't want breaking changes to the existing functions (?), so will create new `*_from_io functions`, and then the API for the existing ones will be unchanged.

No breaking changes is indeed what we want. But you can do it like the [`read_csv()`](I would guess we don't want breaking changes to the existing functions (?), so will create new *_from_io functions, and then the API for the existing ones will be unchanged.) method in pandas. It supports both paths and file-like objects with a single method.
