### ISSUE TITLE
Use black for code formatting?

### ISSUE THREAD

**Issue by jstockwin** [pdfminer/pdfminer.six#394]
Have you considered using [black](https://black.readthedocs.io/en/stable/) for your code formatting?

There are a few drawbacks:
- You'll have one commit which touches almost every file to refactor it to the new styling
- Perhaps you might not like some of the srtyling?

However:
- It's great as a contributor - I don't have to worry about code styling etc, whereas currently I have to infer the styles from the existing code.
- It forces everything to be consistent. I can see that there are lots of existing inconsistencies with e.g. whether you add whitespace around operators.

Happy to discuss further/submit a PR (or obviously just close this issue if you've considered it and decided you don't like it)

**Comment by pietermarsman** [comment]
We already enforce code style using flake8 (see #312, #316 and #345). 

If you want, you can use black as a pre-commit hook to fix flake8 before committing. I use PyCharm reformatting. You can do it the way you want, as long as you confirm to flake8 code style.

**Comment by pietermarsman** [comment]
Reopened this since black is more strict than PEP8 adherence and also it does the formatting automatically. Flake8 still adds value since it also checks for other things than code formatting.
