### ISSUE TITLE
TextConverter output wrong line with text

### ISSUE THREAD

**Issue by Tam678** [pdfminer/pdfminer.six#397]
Hi@pietermarsman,

I am trying to convert  a PDF to text and have come across a output problem. 
TextConverter generates the following:
Education Background
Work Experience
2010.09 -2014.07
Xian Engineer University
Art Design
Bachelor 
Degree 
2012.09 -2013.11

The result I excepted:
Education Background
2010.09 -2014.07
Xian Engineer University
Art Design
Bachelor 
Degree 
Work Experience
2012.09 -2013.11

Here is my code.
```
def pdf_to_detail(path):
    rsrcmgr = PDFResourceManager()		 
    retstr = StringIO()
    codec = 'utf-8'
    laparams = LAParams()		
    device = TextConverter(rsrcmgr, retstr, codec=codec, laparams=laparams)
    fp = open(path, 'rb')
    interpreter = PDFPageInterpreter(rsrcmgr, device)	       
    maxpages = 0
    pagenos=set()
    for page in PDFPage.get_pages(fp, pagenos, maxpages=maxpages, check_extractable=True):
        interpreter.process_page(page)
    fp.close()
    device.close()
    detail = retstr.getvalue()
    print(detail)
    return(detail)
```

the version of pdfminer.six is 20191110

[test (1).pdf](https://github.com/pdfminer/pdfminer.six/files/4341263/test.1.pdf)

**Comment by pietermarsman** [comment]
Hi @Tam678, thanks for your question. Could you try with the newest version of pdfminer.six and see if the problem persists? A lot of small things changes around the turn of the year.

**Comment by Tam678** [comment]
Hi @pietermarsman ,thanks for you help.I'm trying to use the newest version of pdfminer.six.
Before using the newest one,I've changed line_margin in LAParams().It works,but there still exited something contents incorrect.Anyway,thank you very much for your response！
