### ISSUE TITLE
Disabling boxes_flow results in text coming in reverse order

### ISSUE THREAD

**Issue by jstockwin** [pdfminer/pdfminer.six#398]
**Bug report**

[Example PDF](https://www.dropbox.com/s/iesuryj5ter1bax/centered_text_example.pdf?dl=0)

Code to reproduce:
```
from pdfminer.high_level import extract_text
from pdfminer.layout import LAParams

laparams = LAParams(boxes_flow=3, line_margin=0.001)
print(extract_text("test.pdf", laparams=laparams))
```
(Note that once #396 is merged we'll be able to do `boxes_flow=None`, I'm passing 3 simply to disable it)

Actual Output:
```
Text 4
Text 3
Long Text 1
Text 2
Text 1
```

Expected Output:
```
Text 1
Text 2
Long Text 1
Text 3
Text 4
```

**Comment by pietermarsman** [comment]
Interesting unexpected result. Let's look into this after #396 is merged. 

Maybe related: #384.
