### ISSUE TITLE
Can not extrat text from some chinese pdf document

### ISSUE THREAD

**Issue by yifei325325** [pdfminer/pdfminer.six#400]
**Bug report**

python version: 3.6.5
pdfminer.six verison: 20200124

i use the demo code from instructions like this:

```python
from io import StringIO
import os

from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfparser import PDFParser
from settings import BASE_DIR,OUTPUT_DIR,DATA_DIR

file = os.path.join(DATA_DIR,'CN102149977B-panasonic.pdf')
# file = os.path.join(DATA_DIR,'CN201920147158-一种短接装置、短接组合及PCB板-实用新型.pdf')

output_string = StringIO()
with open(file, 'rb') as in_file:
    parser = PDFParser(in_file)
    doc = PDFDocument(parser)

    rsrcmgr = PDFResourceManager()
    device = TextConverter(rsrcmgr, output_string, laparams=LAParams())
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    for page in PDFPage.create_pages(doc):
        interpreter.process_page(page)

print(output_string.getvalue())
```
when i print the result , what  unreadable, they are messy code. like many square with question mark in it.

But  they same code i try other doc. which was commented out , that print well.

for the test files  please see the attchment

[CN102149977B-panasonic.pdf](https://github.com/pdfminer/pdfminer.six/files/4352426/CN102149977B-panasonic.pdf)

[CN201920147158-一种短接装置、短接组合及PCB板-实用新型.pdf](https://github.com/pdfminer/pdfminer.six/files/4352392/CN201920147158-.PCB.-.pdf)

**Comment by yadavsandip32** [comment]
Try using 20181108 version, they probably work. New versions have some issues with them. I have posted a similar issue, but no response has been received by me. [https://github.com/pdfminer/pdfminer.six/issues/391](https://github.com/pdfminer/pdfminer.six/issues/39)1

**Comment by yifei325325** [comment]
Thanks for you suggestion, i 'll try .

**Comment by Tam678** [comment]
Hi,第一个pdf可能是图片格式的pdf,可以先把pdf转成图片再提取信息

**Comment by yifei325325** [comment]
> Hi,第一个pdf可能是图片格式的pdf,可以先把pdf转成图片再提取信息

具体要怎么操作？需要什么软件，悉听指教！

**Comment by Tam678** [comment]
都是用python的包，然后调用百度的OCR文字识别接口提取内容。
（指教谈不上哈，我也是刚入门，也是想多交流以便积累经验。

**Comment by yifei325325** [comment]
> 都是用python的包，然后调用百度的OCR文字识别接口提取内容。
> （指教谈不上哈，我也是刚入门，也是想多交流以便积累经验。

谢谢！我也是通过你的提示才发现那两篇pdf文档确实不同，一篇是word直接转pdf的，一篇是扫描版的，看来只能用OCR了。再次感谢！

**Comment by pietermarsman** [comment]
Can someone translate this to english? 

@Tam678, @yifei325325, can you continue the discussion in english? I am pretty sure that the majority of our contributors can speak better english than CJK.

**Comment by Tam678** [comment]
Hi!@pietermarsman ,sorry for that.
We are dissuing about the format

**Comment by Tam678** [comment]
@pietermarsman ,I 'm sorry for that happened.
We are discussing about the format about PDF.
It can't parse anything While dealing with pdf.The problem I thought was the format of pdf file.It looks like a picture pdf,so I turned the .pdf into .png.And it worked by using OCR to extract the .png file content.
English is not my native language; please excuse typing errors.：)

**Comment by yifei325325** [comment]
@pietermarsman 
Sorry about that , I'm sure he told you what we were talking about, and I'm just wondering if there's a easy way that can extract text directly from a scanned PDF?

**Comment by pietermarsman** [comment]
Hi @Tam678 and @yifei325325, the first document looks like a scanned PDF. Pdfminer.six is not able to extract text from images because it inspects the content of the PDF file directly without doing any kind of rendering. If you cannot copy-paste the text, pdfminer.six also cannot extract the text. 

For scanned document you need some kind of OCR. I think [tesseract](https://github.com/tesseract-ocr/tesseract) is a popular library for doing that.

**Comment by Tam678** [comment]
@pietermarsman ,thank you for your suggestion! I'll try.
