### ISSUE TITLE
word-splitting bug on last version of pdf2txt

### ISSUE THREAD

**Issue by marianorodriguez** [pdfminer/pdfminer.six#402]
Last version of pdfminer.six (20200124) seems to add some empty `<text> </text>` to pdf2txt.py output, splitting words into multiple parts and breaking the final result.

command used:
`python3 pdf2txt.py -p 1 -c utf-8 -t xml -o output.xml icann.pdf`
(python version 3.7.4)

current output with last version:
<img width="1143" alt="Screenshot 2020-03-24 at 10 54 32" src="https://user-images.githubusercontent.com/11478307/77412590-6097db00-6dbe-11ea-9430-d9d6b6468513.png">

but when i downgrade to 20181108, the same command gives this result:
<img width="1131" alt="Screenshot 2020-03-24 at 10 28 47" src="https://user-images.githubusercontent.com/11478307/77412679-7907f580-6dbe-11ea-9bda-eebfd2a69142.png">

[icann.pdf](https://github.com/pdfminer/pdfminer.six/files/4374521/icann.pdf)

**Comment by pietermarsman** [comment]
Hi @marianorodriguez, can you try adjusting the layout parameters to see if that changes things? 

For example: increase `--word_margin` from 0.1 to 0.2 (or higher). This should remove the spaces from the output.

**Comment by marianorodriguez** [comment]
Hi @pietermarsman,
That parameter solved my issue, thanks for your quick reply!

Feel free to close this issue, take care.
