### ISSUE TITLE
Unable to read pdf2txt.py samples/simple1.pdf on my Windows command prompt 

### ISSUE THREAD

**Issue by Kijimu7** [pdfminer/pdfminer.six#406]
**Bug report**

I have tried many things I can think of but I am not able to run the command. I was able to install the pdfminer using pip install pdfminer but I cannot run the command. 

My python version is 3.8.2, I am using Windows 10

I checked #355 and #365 

I tried windows  power shell but it didn't work
My pdf2txt.py is located on C:\Users\MYUSERNAME\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pdfminer-20191125\tools
and I tried the command python C:\Users\MYUSERNAME\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pdfminer-20191125\tools\pdf2txt.py\ simple1.pdf

And I got an error

`C:\Users\MYUSERNAME>python C:\Users\MYUSERNAME\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pdfminer-20191125\tools\pdf2txt.py simple1.pdf
Traceback (most recent call last):
  File "C:\Users\MYUSERNAME\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pdfminer-20191125\tools\pdf2txt.py", line 115, in <module>
    if __name__ == '__main__': sys.exit(main(sys.argv))
  File "C:\Users\MYUSERNAME\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pdfminer-20191125\tools\pdf2txt.py", line 104, in main
    with open(fname, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'simple1.pdf'`

What am I doing wrong?
How can get it to work?

**Comment by pietermarsman** [comment]
You need to replace `simple1.pdf` with a path to a pdf. You can find the simple1.pdf in the samples directory of this project (if you clone it). You can also use another pdf on your machine.

**Comment by Kijimu7** [comment]
@pietermarsman now I understand what I was doing wrong. Thank you for your reply.
