### ISSUE TITLE
Disabling boxes flow makes lines be in wrong order within text boxes

### ISSUE THREAD

**Issue by jstockwin** [pdfminer/pdfminer.six#411]
**Bug report**

When passing `boxes_flow` as `None`, we don't run the full advanced layout analysis, but rather the order of text boxes will depend on their position on the page only. This is intentional.

If we were passing boxes flow, we'd group the text boxes and then call `analyze` on each group ([here](https://github.com/pdfminer/pdfminer.six/blob/develop/pdfminer/layout.py#L811)). This filters down so that `analyze` is called on the text boxes themselves. When `boxes_flow=None`, we don't call `analyze` on the text boxes, which results in the lines coming in the wrong order as they don't get sorted.

Note that `boxes_flow` is not used in the `analyze` method of text boxes, it is only used for groups of text boxes (which we never have if boxes flow is disabled).

To fix this, we just need to make sure that `analyze` is always called on the text boxes, even if we don't group them.

[Example PDF](https://www.dropbox.com/s/jjhlbsynrnjuq6i/negative_line_margin_example.pdf?dl=0)

Example code:
```
from pdfminer.high_level import extract_pages
from pdfminer.layout import LAParams

la_params = LAParams(boxes_flow=None)

for page in extract_pages("example.pdf", laparams=la_params, caching=False):
    print("*****OUTPUT:*****")
    for element in page:
        print(element)
```

Example output:
```
*****OUTPUT:*****
<LTTextBoxHorizontal(-1) 58.100,343.402,106.178,406.702 'Text 3Text 2Text 1'>
```

Expected output:
```
*****OUTPUT:*****
<LTTextBoxHorizontal(-1) 58.100,343.402,106.178,406.702 'Text 1\nText 2\nText 3\n'>
```

**Comment by rcyost** [comment]
pdfminersix couldn't get the order correct until I passed None to boxes_flow, seems a bit buggy
