### ISSUE TITLE
pdfminer high_level module access issues

### ISSUE THREAD

**Issue by trmanish** [pdfminer/pdfminer.six#413]
Hi 

I am trying to extract a text from pdf. I am trying to use pdfminer in python API format. 

When I tried installing pdfminer via 

`pip install pdfminer.six`

I got the following in mac terminal: 

`Requirement already satisfied: pdfminer.six in /anaconda3/envs/ds/lib/python3.7/site-packages (20181108)
Requirement already satisfied: pycryptodome in /anaconda3/envs/ds/lib/python3.7/site-packages (from pdfminer.six) (3.9.7)
Requirement already satisfied: six in /anaconda3/envs/ds/lib/python3.7/site-packages (from pdfminer.six) (1.14.0)
Requirement already satisfied: sortedcontainers in /anaconda3/envs/ds/lib/python3.7/site-packages (from pdfminer.six) (2.1.0)`

Doing import pdfminer works. 

However when I try to do: 

from pdfminer import high_level as I need this module to use the extract_text function on a pdf, I get the following error: 

> Exception: Version mismatch: this is the 'cffi' package version 1.12.3, located in '/anaconda3/envs/ds/lib/python3.7/site-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.14.0, located in '/anaconda3/envs/ds/lib/python3.7/site-packages/_cffi_backend.cpython-37m-darwin.so'.  The two versions should be equal; check your installation.

Can someone help how to get the pdf extraction working using pdfminer via python functions

**Comment by cmdavis4** [comment]
You may want to try `pip install --upgrade pdfminer.six`, I was also having issues with the `high_level` module and updating the package to the most recent version resolved it for me.

**Comment by trmanish** [comment]
This broke my numpy. The issue with high_level got solved, but now it says no Module numpy when it is still there in my conda env.

**Comment by pietermarsman** [comment]
This is an issue with your installation, so closing this. Try uninstall and installing pdfminer.six / numpy / anaconda3.
