### ISSUE TITLE
Unfork this repository

### ISSUE THREAD

**Issue by jbarlow83** [pdfminer/pdfminer.six#415]
Contact GitHub support and ask them to "unfork" this repository, making it a primary repository.

That will enable code indexing, and reflects the fact that this is now the actively maintained version of pdfminer.six rather than euske/pdfminer.

**Comment by pietermarsman** [comment]
Hi @jbarlow83, 

Thanks for this reminder. I am going to contact github and see what they can do.

Pieter.

**Comment by pietermarsman** [comment]
Now we wait...

**Comment by pietermarsman** [comment]
Its done :D
