### ISSUE TITLE
Extracting Particular text fields from pdf files

### ISSUE THREAD

**Issue by trmanish** [pdfminer/pdfminer.six#416]
Hi 

I feel out of all the pdf to text extraction tools, pdfminer has lot of capabilities. 

However one big issue I find is that when I convert my pdf to text using pdfminer, the text gets all jumbled up and its difficult for me to extract the right text fields. 

For ex. here is a pdf I have. 

I want to extract all the Bold headings along with the value they have for it. 

Using pdfminer just jumbles it all up and becomes difficult to use a regular expression then to extract the headings with its values. 

![Screen Shot 2020-04-08 at 11 41 16 AM](https://user-images.githubusercontent.com/4309723/79057649-642dbd80-7c18-11ea-9b5d-858a871cfaee.png)

**Comment by qxnatalie** [comment]
It's better to paste all codes here.

**Comment by trmanish** [comment]
Hi 

So here is the code I tried. 

```
def pdf_extract():
    """ This function extracts the text from the pdf files
    
    """
    
    import glob
    
    for pdf_file in glob.glob(os.path.join(DATA_DIR,COMPANIES_LIST[0])+"/*.pdf"):   
        
        with open(pdf_file, 'rb') as f:
            pdfReader = pypdf.PdfFileReader(f)
            #Discerning the number of pages will allow us to parse through all the pages.
            num_pages = pdfReader.numPages
            count = 0
            
            text = ""

             #The while loop will read each page.
            while count < num_pages:
                pageObj = pdfReader.getPage(count)
                count +=1
                text += pageObj.extractText()
            
                #This if statement exists to check if the above library returned words. It's done because PyPDF2 cannot read scanned files.

                if text != "":
                    text = text

                #If the above returns as False, we run the OCR library textract to #convert scanned/image based PDF files into text.
                else:
                    text = textract.process(pdf_file, method='tesseract', language='eng')
                    
        break
                
                
    return text
```

I tried both pypdf2 and textract with pdfminer as the engine. 

I get text extracted but all jumbled up. So its difficult to find a regex patter in that then. 

I was hoping if pdfminer helps in being able to extract specific text from the pdf corresponding to those headers (Invoice Date, Invoice no. Delivery Charge etc). 

Or do u think if any OCR packages can help do that if I convert my pdf to an image format? 

Thank You. Been exploring a lot on this and haven't been able to get the right extraction so direction here would be helpful. 

Thank

**Comment by qxnatalie** [comment]
Hi, 


Thank you for the help. 


I am still working on that. If any new, I will let you know. 


Natalie




------------------ Original ------------------

**Comment by pietermarsman** [comment]
Hi @trmanish! Checkout [camelot](https://github.com/camelot-dev/camelot/blob/master/requirements.txt); a tool for table extraction based on pdfminer.six.
