### ISSUE TITLE
PDF Text Extraction Results Differ when running pdfminer on Mac vs. Ubuntu

### ISSUE THREAD

**Issue by benjaminEwhite** [pdfminer/pdfminer.six#418]
**Bug report**

- I'm using the following function `extract_text_from_report` to extracting text from [this Google Mobility Covid19 Report](https://www.gstatic.com/covid19/mobility/2020-03-29_US_Alabama_Mobility_Report_en.pdf)

  ```python
  import io

  import requests
  
  from pdfminer.pdfparser import PDFParser
  from pdfminer.pdfdocument import PDFDocument
  from pdfminer.converter import PDFPageAggregator
  from pdfminer.layout import LAParams, LTTextBox, LTTextLine
  from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
  from pdfminer.pdfpage import PDFPage

  def extract_text_from_report(url):
    extracted_text = ""
    response = requests.get(url)
    parser = PDFParser(io.BytesIO(response.content))
    password = ""
    document = PDFDocument(parser, password)
    rsrcmgr = PDFResourceManager()
    laparams = LAParams()
    device = PDFPageAggregator(rsrcmgr, laparams=laparams)
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    for page in PDFPage.create_pages(document):
        # As the interpreter processes the page stored in PDFDocument object
        interpreter.process_page(page)
        # The device renders the layout from interpreter
        layout = device.get_result()
        # Out of the many LT objects within layout, we are interested in LTTextBox
        # and LTTextLine
        for lt_obj in layout:
            if isinstance(lt_obj, LTTextBox) or isinstance(lt_obj, LTTextLine):
                extracted_text += lt_obj.get_text()
    return extracted_text
  ```
- I have code that loads the first page of this report and searches for the string "Parks", in order to get the score that is associated with that field:
     
<img width="1081" alt="Screen Shot 2020-04-13 at 9 39 12 PM" src="https://user-images.githubusercontent.com/960351/79177045-d09eed00-7dcf-11ea-8696-6db76474527c.png">

-  When running my script locally on Mac OSX 10.15.3 + Python 3.7.2, the extracted text includes 'Parks'. Parsing the page with `extract_text_from_report` above, I get
    ```
   report_string[1963:2100]
    --> 'a County\nRetail & recreation\nGrocery & pharmacy\nParks \n*\n-42%  compared to baseline\n-8%  compared to baseline\n-14%  compared to baseline\n'
    ```

- The bug appears when I run this same code in a Digital Ocean Droplet running Ubuntu and Python 3.7.5.  Getting to the same point in my code, and referring to the same original PDF url, when running in the Ubuntu environment, that same page does not appear as having "Parks" in it.  Running `extract_text_from_report` in this environment, I get
  ```
  report_string[1963:2100]
  --> 'a County\nRetail & recreation\nGrocery & pharmacy\n-42%  compared to baseline\n-8%  compared to baseline\n-14%  compared to baseline\n+80%\n+40%'
  ```

**Comment by shriya3099** [comment]
Facing the same issue. Could you please guide on how to solve it?

**Comment by pietermarsman** [comment]
The output can depend on the version of pdfminer.six since every update contains some bug-fixes for the layout algorithm. Are you using the same version?
