### ISSUE TITLE
How to extract phrases under subtitle with lots of academic pdfs

### ISSUE THREAD

**Issue by qxnatalie** [pdfminer/pdfminer.six#420]
The subtitle of **Keywords** is a necessary part of any academic journal. The words following the **Keywords** only need to be extracted.  Does anyone give me a hint? One example is as follows:

![image](https://user-images.githubusercontent.com/36719487/80403705-9e72ac80-88f2-11ea-8f6c-04c14a36ffe8.png)

**Comment by pietermarsman** [comment]
Hi @qxnatalie, you can use the pdf2txt.py command to extract the text from the first page of a pdf. Then, you need to do some post-processing to get the precise result you want.

Below is an example for a linux command that extract the text from page 1 and searches for lines with the word "keywords" in it. 

```bash
python tools/pdf2txt.py academic.pdf --page 1 | grep -i keywords
```

Also see the documentation: https://pdfminersix.readthedocs.io/en/latest/index.html
