### ISSUE TITLE
PDF Font Recoginition

### ISSUE THREAD

**Issue by vitalibertas** [pdfminer/pdfminer.six#422]
req = requests.get(pdf_url)
    content_type = req.headers['Content-Type']
    modified_date = req.headers['Last-Modified']
    content_buffer = BytesIO(req.content)

    if content_type == 'application/pdf':
        resource_manager = PDFResourceManager()
        fake_file_handle = StringIO()
        converter = TextConverter(resource_manager, fake_file_handle, codec='utf-8',
                                  laparams=LAParams(boxes_flow=-1.0, all_texts=True))
        page_interpreter = PDFPageInterpreter(resource_manager, converter)
        for page in PDFPage.get_pages(content_buffer, caching=False):
            page_interpreter.process_page(page)
        text = fake_file_handle.getvalue()
[CurrentBriefAgenda.pdf](https://github.com/pdfminer/pdfminer.six/files/4582535/CurrentBriefAgenda.pdf)
When trying to convert this PDF, the output gives unrecognized font characters:
(cid:38)(cid:44)(cid:55)(cid:60)(cid:3)(cid:38)(cid:50)(cid:56)(cid:49)(cid:38)(cid:44)(cid:47)(cid:3)(cid:36)(cid:42)(cid:40)(cid:49)(cid:39)(cid:36)
(cid:54)(cid:51)(cid:40)(cid:38)(cid:44)(cid:36)(cid:47)(cid:3)(cid:48)(cid:40)(cid:40)(cid:55)(cid:44)(cid:49)(cid:42)(cid:3)(cid:3)
(cid:37)(cid:60)(cid:3)(cid:40)(cid:47)(cid:40)(cid:38)(cid:5

**Comment by pietermarsman** [comment]
Hi @vitalibertas! Which characters do you expect instead? Is all of the output wrong, or just a part?

Having these (cid:*) in the output often happens when the unicode mapping for those characters are missing.

**Comment by vitalibertas** [comment]
That whole first page of the attachment is all CID and unrecognized. I would expect the text of that page to show. I’m getting much better results with just OCR’ing the page images with tesseract, wand, and pyocr.

**Comment by pietermarsman** [comment]
The unicode mapping appears to be missing. E.g. if you try to copy a line to a text editor, you notice that the pasted text is very different. This is a symptom of the same problem. With this pdf, pdfminer.six cannot do much more than outputting unrecognized characters.
