### ISSUE TITLE
Replacing CID with custom values / mapping

### ISSUE THREAD

**Issue by MAkcanca** [pdfminer/pdfminer.six#425]
I've been looking through the source code but decided to ask it before doing something hacky.
There are some characters appear as (CID:XXX) while parsing a PDF, which is understandable. But how can one replace these values with something else? Let's say I want to show A for CID:XXX and B for CID:XXY. 
How can I map this? I checked Cmapping but honestly couldn't understand it completely. 
Thanks!

**Comment by pietermarsman** [comment]
Hi @MAkcanca, 

As far as I know this is not possible with pdfminer.six. And I don't think we need to add this to pdfminer because you can do this with other tools. Just open the output file (programatically) and replace (cid:xxx) with the character you need.

E.g. if you work on a linux shell:

```shell
python tools/pdf2txt.py your.pdf | sed -e 's/(cid:xxx)/char/g'
```
