### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by corneliusroemer** [pdfminer/pdfminer.six#428]
**Feature request**

I did a performance comparison between PDFminer and PyPDF2. It turns out miner is 6 times slower at extracting text (3s vs 0.5s for 10 pages).

I used the high level extract_text().

Maybe timing could be optimized.

**Comment by pietermarsman** [comment]
Hi @corneliusroemer,

For future references, could you share the pdf you are using? 

At this point in time pdfminer.six does not really focus on speed. It focuses on extracting human-readable text. I'm confident that if you disable the pdfminer.six layout algorithm it will be just as fast as PyPDF2.

I'm closing this issue since speed is not a priority right now. Feel free to open another issue, or reopen this one, if pdfminer.six' speed is causing problems.

**Comment by corneliusroemer** [comment]
Hi @pietermarsman, here's the PDF type I'm using: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/2020-05-12-de.pdf?__blob=publicationFile

How do I disable the layout algorithm from the high-level extract_text() function?

**Comment by pietermarsman** [comment]
That's not possible with `extract_text()`... 

You can try this:

```python

def extract_text(pdf_file, password='', page_numbers=None, maxpages=0,
                 caching=True, codec='utf-8', laparams=None):
    """Parse and return the text contained in a PDF file.

    :param pdf_file: Either a file path or a file-like object for the PDF file
        to be worked on.
    :param password: For encrypted PDFs, the password to decrypt.
    :param page_numbers: List of zero-indexed page numbers to extract.
    :param maxpages: The maximum number of pages to parse
    :param caching: If resources should be cached
    :param codec: Text decoding codec
    :param laparams: An LAParams object from pdfminer.layout. If None, uses
        some default settings that often work well.
    :return: a string containing all of the text extracted.
    """
    # if laparams is None:
    #     laparams = LAParams()

    with open_filename(pdf_file, "rb") as fp, StringIO() as output_string:
        rsrcmgr = PDFResourceManager()
        device = TextConverter(rsrcmgr, output_string, codec=codec,
                               laparams=laparams)
        interpreter = PDFPageInterpreter(rsrcmgr, device)

        for page in PDFPage.get_pages(
                fp,
                page_numbers,
                maxpages=maxpages,
                password=password,
                caching=caching,
                check_extractable=True,
        ):
            interpreter.process_page(page)

        return output_string.getvalue()
```

**Comment by rcyost** [comment]
Hello, I am trying to use this package and it is so slow it does not work? 

Here is two cells of code to display that the pdf is found, and a generator object is created. 

But when I try to iterate using the generator, it just hangs ....

It never even iterates once. 

![image](https://user-images.githubusercontent.com/32645001/157303134-ecf7a1cb-aff1-44bf-988c-1179f7947618.png)

[I am using this pdf btw](https://assets.ey.com/content/dam/ey-sites/ey-com/en_gl/topics/tax/ey-2021-worldwide-vat-gst-sales-tax-guide-web.pdf)
