### ISSUE TITLE
The output of pdf2txt.py has incorrect order of the lines (python2 will generate correct output)

### ISSUE THREAD

**Issue by johnlinp** [pdfminer/pdfminer.six#435]
**Bug report**

*Reproduction steps*

1. Download the sample pdf: https://github.com/johnlinp/misc-demo/blob/master/pdfminer-six-python-versions/sample.pdf
1. Run `python3 /usr/local/bin/pdf2txt.py sample.pdf`

*Expect result*

In the original PDF file, this paragraph
```
內湖區之住宅區分佈於平緩地區與坡地間，主要沿內湖路、成
功路、民權東路及康寧路兩側分布，其中以第三種住宅區居多，位
於丘陵或坡地部分則為第二種住宅區。 
```
is between the list item `1、住宅區` and `2、商業區`.

Therefore, I expect that the result will be:
```
1、住宅區 
內湖區之住宅區分佈於平緩地區與坡地間，主要沿內湖路、成
功路、民權東路及康寧路兩側分布，其中以第三種住宅區居多，位
於丘陵或坡地部分則為第二種住宅區。 
2、商業區 
```

*Actual result*

The paragraph mentioned above doesn't appear between the list item `1、住宅區` and `2、商業區`.

It shows:
```
內湖區之住宅區分佈於平緩地區與坡地間，主要沿內湖路、成
功路、民權東路及康寧路兩側分布，其中以第三種住宅區居多，位
於丘陵或坡地部分則為第二種住宅區。 
1、住宅區 
2、商業區 
```

*Extra info*

If I run with `python2`, i.e. `python2 /usr/local/bin/pdf2txt.py sample.pdf`, the results will be correct.

Here are the complete results:
1. [Results via python2](https://github.com/johnlinp/misc-demo/blob/master/pdfminer-six-python-versions/results-via-python2.txt)
1. [Results via python3](https://github.com/johnlinp/misc-demo/blob/master/pdfminer-six-python-versions/results-via-python3.txt)

As you can see, the results via python2 is correct.

Therefore, I think it might be a bug since the inconsistency comes from the difference of python versions.

**Comment by pietermarsman** [comment]
Python2 is no longer supported, it should raise an error with the newest version. Which version are you using? 

You can get better output by increasing the line-margin. The layout algorithm uses sensible defaults but they don't always give you the perfect result.

Example:

```shell script
$ pdf2txt.py Downloads/sample.pdf --line-margin 5
三、原都市計畫情形 
（一）計畫人口 
本地區之主要計畫於民國 63 年 1 月 5 日公告實施，除陸續於各擬
訂細部計畫案中配合修訂主要計畫外，部份地區亦循個案變更程序修訂
主要計畫分區，合計現行計畫區規劃之住宅區、商業區與工業區及其他
計畫開發地區之可容納人口約為 308,000 人。 
（二）土地使用 
內湖區總面積約 3,157.90 公頃，其中住宅區面積為 381.32 公頃，
商業區面積為 37.35 公頃，工業區面積則為 222.73 公頃，其分布及詳
細面積詳見圖 2-2 及表 2-2。各使用分區之分佈情形如下： 
1、住宅區 
內湖區之住宅區分佈於平緩地區與坡地間，主要沿內湖路、成
功路、民權東路及康寧路兩側分布，其中以第三種住宅區居多，位
於丘陵或坡地部分則為第二種住宅區。 
2、商業區 
內湖區之商業使用係以地區型商業服務為主，現有商業區多集
中於內湖路一段、成功路四段及康寧路一帶，均為內湖地區既有商
圈並提供地區性之商業服務。 
3、工業區 
（1）傳統工業區：內湖區有二處工業區。一處為文湖街南側、
內湖路一段北側之北勢湖工業區，為第二種工業區；另一
處位於成美橋以東、成功路以西之新明路兩側均為第三種
工業區。 
（2）科技工業區：內湖區地理位置位於本市產業發展軸帶之中
心點，含括內湖科技園區科技工業區 A 及 B 區、大彎南段
科技工業區 C 及 D 區、及成功路以東、南湖大橋以西之蘆
11
```

**Comment by johnlinp** [comment]
Thank you for the suggestion. I'll try using `--line-margin`.
