### ISSUE TITLE
Command line tool pdf2txt.py not available after pip install 

### ISSUE THREAD

**Issue by paulrougieux** [pdfminer/pdfminer.six#439]
I installed pdfminer.six with pip3, as shown by 

```
pip3 install --user pdfminer.six
Requirement already satisfied: pdfminer.six in /home/paul/.local/lib/python3.7/site-packages (20200517)
```

But I don't have access to the command line utility because the pdf2txt.py is not in the local library as shown by : 

    find ~/.local/lib/python3.7/site-packages/ -name pdf2txt.py

For information other scripts are available in there such as:

    find ~/.local/lib/python3.7/site-packages/ -name pdfdocument.py
    /home/paul/.local/lib/python3.7/site-packages/pdfminer/pdfdocument.py

And the python import statement works in ipython3 :

    In [1]: import pdfminer
    In [2]: print(pdfminer.__version__)
    20200517

In case that is relevant, I'm using Debian 10 Buster.

**Comment by paulrougieux** [comment]
The utility is simply available directly (without python prefix) in bash as :

    $ pdf2txt.py --version
    pdfminer.six v20200517

**Comment by NickFabry** [comment]
To amplify what Paul Rougieux said - typically, the CLI tools are not installed in the same directory as the python libraries. For instance, on my machine, the pdfminer.six tools are installed in:

/Users/fabry/Library/Python/3.8/lib/python/site-packages

You can find this by opening up a python shell, and typing the following:

>>> import sys
>>> sys.path

Somewhere in that path is where your (depending on whether you installed it system-wide via aptitude or for your local user via pip --user or somesuch) libraries are installed. That's where python searches when you do, for example "import parrot".

However, that directory is *not* located on your shell path, and CLI tools associated with a package are not installed there either. In this case, the CLI tool part of pdfminer.six is:

% which pdf2txt.py                                                     4ms
/Users/fabry/Library/Python/3.8/bin/pdf2txt.py

So, you should be able to use the CLI part by typing % pdf2txt.py some_random.pdf > hopefully_useful.txt .

If it doesn't work, you probably need to adjust your shell's PATH to incorporate the bin directory for the tool.

Hope this helps.
