### ISSUE TITLE
how to extract all font files. Need an example

### ISSUE THREAD

**Issue by devtula** [pdfminer/pdfminer.six#444]
How to extract all font files? And any other not visible data.

**Comment by nate-bush** [comment]
You might consider using PyMuPDF to create font files from fonts embedded in a PDF. https://github.com/pymupdf/PyMuPDF/wiki/How-to-Extract-Fonts-from-a-PDF

**Comment by pietermarsman** [comment]
If they are embedded files, you can use the `--extract-embedded` flag on `dumppdf.py`. 

However, pdfminer.six is aimed at extracting human-readable text from PDF's, not font files. There are other tools that are better suited for this. For example, [MuPDF](https://mupdf.com/docs/manual-mutool-extract.html).
