### ISSUE TITLE
Failed to convert files with CID fonts.

### ISSUE THREAD

**Issue by gaojie058** [pdfminer/pdfminer.six#447]
**Bug report**
Hi developers! Thanks for providing this wonderful tool for us! I have found some issues when I was using this tool.

### Description
When I converted [this paper](https://www.dropbox.com/s/i1s58dw2icg0r26/test.pdf?dl=0) to txt, I followed all the steps you suggested but I still failed and got some "cid: xx" results. 

### Results

CHI 2020 Paper

CHI 2020, April 25–30, 2020, Honolulu, HI, USA

(cid:56)(cid:81)(cid:71)(cid:72)(cid:85)(cid:86)(cid:87)(cid:68)(cid:81)(cid:71)(cid:76)(cid:81)(cid:74)(cid:3)(cid:58)(cid:68)(cid:79)(cid:78)(cid:76)(cid:81)(cid:74)(cid:3)(cid:48)(cid:72)(cid:72)(cid:87)(cid:76)(cid:81)(cid:74)(cid:86)(cid:29)(cid:3)(cid:39)(cid:85)(cid:76)(cid:89)(cid:72)(cid:85)(cid:86)(cid:3)(cid:68)(cid:81)(cid:71)(cid:3)(cid:37)

### Steps
python3.8  pdf2txt.py  test.pdf

I don't know what happened. It looks like every step is correct, but I couldn't get the right texts. Would appreciate it if you can help me deal with this problem.

**Comment by pietermarsman** [comment]
Hi @gaojie058! Unfortunately there is little we can do to solve this. Most pdf's specify a unicode mapping for all each glyph in the font. If this unicode mapping is missing we cannot convert the glyphs to unicode. It is like the PDF only specifies how to draw a character, but it does not give a translation to which character it is. 

You can see that this is the case by copy pasting a word out of the pdf. The copied text is completely different. 

The best you can do with PDF's like this is to use an OCR tool. Different approach with different benefits and drawbacks.

**Comment by gaojie058** [comment]
Hi developers, I dealt with this problem finally. Your tool is great! Thanks 👍

**Comment by kyprifog** [comment]
@gaojie058 how did you deal with this problem?

**Comment by pietermarsman** [comment]
@gaojie058 also currious how you did it. Is there a way we can add your solution to pdfminer.six?

**Comment by Beants** [comment]
@gaojie058 also currious how you did it. Is there a way we can add your solution to pdfminer.six?

**Comment by cutright** [comment]
> You can see that this is the case by copy pasting a word out of the pdf. The copied text is completely different.


@pietermarsman I have a PDF that reports only CID characters with `pdfminer`, but I can copy and paste from macOS Preview to TextEdit just fine. This also works with Adobe Acrobat on MSW7 pasting into NotePad.

Does this mean that macOS Preview and Adobe both recognize the font and uses their own unicode map? Or they don't get the font from the PDF?

I'm still perusing the `pdfminer` code... followed the rabbit hole into `pdftypes.PDFStream` because the spec for each of the fonts in this PDF all have a `ToUnicode` key:
```
BaseFont: /'HQKDJO+Arial'
ToUnicode: <PDFStream(25): raw=1341, {'Filter': /'FlateDecode', 'Length': 1339}>
BaseFont: /'UHKJJE+Arial-ItalicMT'
ToUnicode: <PDFStream(53): raw=293, {'Filter': /'FlateDecode', 'Length': 291}>
BaseFont: /'BVSAIU+Arial,Bold'
ToUnicode: <PDFStream(29): raw=1201, {'Filter': /'FlateDecode', 'Length': 1199}>
BaseFont: /'IGFLXS+Arial,Italic'
ToUnicode: <PDFStream(27): raw=1421, {'Filter': /'FlateDecode', 'Length': 1419}>
```

But I guess having `ToUnicode` doesn't mean it has a valid unicode map?

**Comment by SOMJANG-42MARU** [comment]
@gaojie058 also currious how you did it. Is there a way we can add your solution to pdfminer.six?
