### ISSUE TITLE
how to get table

### ISSUE THREAD

**Issue by sight007** [pdfminer/pdfminer.six#457]
i just get the text of table,  how to get table's structure, or such as [[], [],,,,].......?

**Comment by pietermarsman** [comment]
Hi @sight007! Could you include the pdf and code you are using? That allows us to help you better.

**Comment by sight007** [comment]
![image](https://user-images.githubusercontent.com/22489763/87892155-ebd46500-ca6e-11ea-890d-626c53cdcfd1.png)

this is my pdf table sample,  i use code from docs,   the result is :

..........(other text).......
..........(other text).......
二十一、工程做法及选用图集
部位   图集  节点
xxxx xxxx  xxxx  
xxxx xxxx xxxx
..........(other text).......
..........(other text).......


these are mixing with other text,  i only want to get table's content and table's structure,  such as json, datefrme, [[],[],,,] or other data structure.  If it contains (x0, y0, x1, y1) of box,  that's better.

**Comment by sight007** [comment]
![1595229716(1)](https://user-images.githubusercontent.com/22489763/87914081-b6e20580-caa2-11ea-8436-908c93d8a3bd.jpg)

this's  a table sample of my pdf,  i use code from docs, the result is :

---(other text)----
---(other text)----
二十一、工程做法及选用图集
部位    图集   节点
xxxx     xxxx    xxxx
xxxx     xxxx    xxxx   
---(other text)----
---(other text)----

these are mixing with other text, i only want to get table's struct and (x0, y0, x1, y1)  of table's box.

**Comment by pietermarsman** [comment]
Hi @sight007,

Its not possible to get this output using pdfminer.six. A PDF does not have such a thing as a table. It has lines, curves and characters that are printed somewhere on the page. Pdfminer.six is designed to extract text  from this structure. You can also use it to extract the lines that compose the table, but not the actual table structure itself. 

If you want to extract tabular data from a PDF you should use a tool like [Camelot](https://camelot-py.readthedocs.io/en/master/).
