### ISSUE TITLE
How to count words under each heading?

### ISSUE THREAD

**Issue by igavronski** [pdfminer/pdfminer.six#460]
Hi,
I would like to count the words under each heading (such as those obtained with `dumppdf.py -T`).
Any ideas?
Thanks in advance.

**Comment by pietermarsman** [comment]
Hi @igavronski, you should give some more context. Please add an example PDF to this issue and give an example of the output that you would like to have.

**Comment by igavronski** [comment]
Hi @pietermarsman,

An example would be: [lorem.pdf](https://github.com/pdfminer/pdfminer.six/files/4971473/lorem.pdf)

An example output would be:
```
python pdfwc.py --indent lorem.pdf
This is the first heading 1: 50 words
    This is the first heading 2: 100 words
    This is the second heading 2: 150 words

python pdfwc.py --csv --levels --noheaders lorem.pdf
1,This is the first heading 1,50
2,This is the first heading 2,100
2,This is the second heading 2,150
```
Thanks!

**Comment by jstockwin** [comment]
@igavronski As far as I am aware, I don't think this functionality is provided as-is. However, since you can explicitly access all of the pdf elements, you can still use pdfminer.six to do this. The following script produces the correct output.

A note on LAParams -> I've chosen the `line_margin` such that the headings get split from the content under them, but the main blocks of content are still counted as one text box. The increased `word_margin` is because some of the words have slightly larger gaps between them, which was causing pdfminer.six to insert two spaces instead of one. This is specific to your example PDF.

```
from collections import defaultdict
from logging import currentframe

from pdfminer.high_level import extract_pages
from pdfminer.layout import LAParams, LTTextContainer

page = list(
    extract_pages("lorem.pdf", laparams=LAParams(line_margin=0.18, word_margin=0.25))
)[0]

counts = defaultdict(int)
current_heading = None

for idx, element in enumerate(page):
    if isinstance(element, LTTextContainer):
        # Check the size of the first character to see if it's a header
        first_line = list(element)[0]
        first_char = list(first_line)[0]
        is_heading = first_char.size >= 13

        if is_heading:
            current_heading = element.get_text().strip()
            continue

        if not current_heading:
            raise Exception("First element was not heading")

        text = element.get_text().strip()

        if text == "":
            # Empty elements - ignore
            continue

        counts[current_heading] += len(text.split(" "))

for heading, count in counts.items():
    print(f"{heading}: {count} words")

```

Output:

```
This is the first heading 1: 50 words
This is the first heading 2: 100 words
This is the second heading 2: 150 words
```

I hope that helps. Please do close the issue if it resolves your problem.

**Comment by igavronski** [comment]
I am sorry! I got no warning on this response. I will check as soon as possible and get back to you.

**Comment by igavronski** [comment]
@jstockwin -- In fact, your solution relies on font size. This is not possible for 95% of the papers in my library. I needed to walk through the bookmarks structure, which is what `dumppdf.py` does.
Any ideas?

**Comment by igavronski** [comment]
See:
```
dumppdf.py -T lorem.pdf
<outlines>
<outline level="1" title="b'This is the first heading 1 '">
<dest><list size="5">
<ref id="9" />
<literal>XYZ</literal>
<number>0</number>
<number>792</number>
<keyword>b'null'</keyword>
</list></dest>
<pageno>1</pageno>
</outline>
<outline level="2" title="b'This is the first heading 2 '">
<dest><list size="5">
<ref id="9" />
<literal>XYZ</literal>
<number>0</number>
<number>792</number>
<keyword>b'null'</keyword>
</list></dest>
<pageno>1</pageno>
</outline>
<outline level="2" title="b'This is the second heading 2'">
<dest><list size="5">
<ref id="9" />
<literal>XYZ</literal>
<number>0</number>
<number>792</number>
<keyword>b'null'</keyword>
</list></dest>
<pageno>1</pageno>
</outline>
</outlines>
```

**Comment by ChrizH** [comment]
@igavronski I have been working on a library ([pdfstructure](https://github.com/ChrizH/pdfstructure)) that adds dynamic structure detection on top of pdfminer.six. 

Pdfstructure is not relying on the bookmarks structure, but does a pre-analysis on most common fonts, style or character size. It categories then each paragraph into header or content and groups them into a nested tree resembling the original hierarchy. The resulting document tree keeps the pdf structure and can be easily traversed using utility methods from the library (more info on the readme).


The following snippet could solve your task ([test case](https://github.com/ChrizH/pdfstructure/blob/master/tests/test_custom_use_cases.py)):
```
from pathlib import Path

from pdfstructure.hierarchy.parser import HierarchyParser
from pdfstructure.hierarchy.traversal import traverse_inorder_sections_with_content
from pdfstructure.source import FileSource

def test_count_paragraph_words(self):
    parser = HierarchyParser()
    test_file = str(Path("resources/lorem.pdf"))
    document =parser.parse_pdf(FileSource(file_path=test_file))
  
    for level, title, content in traverse_inorder_sections_with_content(document):
      prefix = "".join(["\t" for i in range(level)])  # visualize nested relation
      print("{}{};\twords: {}".format(prefix, title, len(content.split())))
```

And it produces the output:

```
This is the first heading 1;	words: 50
	This is the first heading 2;	words: 100
	This is the second heading 2;	words: 150
```

_Note: The library is not released yet, but it is able to achieve useful results already._

**Comment by igavronski** [comment]
Hi @ChrizH,
I believe your library will work. Thanks for the code.
My PDF files are mostly academic papers with a 2-column layout, as you mention in your disclaimer... But let's give it a try.
Thanks in advance!
Iuri.

**Comment by ChrizH** [comment]
> Hi @ChrizH,
> I believe your library will work. Thanks for the code.
> My PDF files are mostly academic papers with a 2-column layout, as you mention in your disclaimer... But let's give it a try.
> Thanks in advance!
> Iuri.

Hi @igavronski, how was your experience using pdfstructure? 
I have pushed a new version that should work better with academic papers.
Best

**Comment by igavronski** [comment]
I haven't had the opportunity to test it. The academic year, as you might guess, is harder than usual.
Let me try that out and get back to you.

**Comment by igavronski** [comment]
@ChrizH ,

Your module works for the mock file I created (lorem.pdf), but not for a real paper. If you need a real test file, one example would be:
https://scholar.google.com.br/scholar?q=Goodstein+2016+Moral+Repair&hl=en&as_sdt=0&as_vis=1&oi=scholart

Let me know if your module can handle it in the future.

Best regards,

Iuri.
