### ISSUE TITLE
Minimum example for extracting LTChars and LTCurves

### ISSUE THREAD

**Issue by mhrmsn** [pdfminer/pdfminer.six#463]
I'm currently trying to analyze PDFs where I want to find certain shapes and letters/numbers in them. For this purpose, all I need are only the LTChar and LTCurve objects of the PDF document. I was thinking that for this purpose I do not require layout analysis or other functionality of the package.

What would be the fastest, straightforward way to obtain only LTChars and LTCurves from a PDF file?

**Comment by pietermarsman** [comment]
The method `extract_pages` gives you the pdfminer.six representation of the PDF. You can iterate over it to get all the characters or curves. 

Have a look at this tutorial: https://pdfminersix.readthedocs.io/en/latest/tutorial/extract_pages.html
