### ISSUE TITLE
When run on Windows a lot of tests fail with the error:  [Errno 13] Permission denied 

### ISSUE THREAD

**Issue by Ev2geny** [pdfminer/pdfminer.six#469]
**A description of the bug**
When run on Windows a lot of tests fail with the error:   ``[Errno 13] Permission denied ```. E.g.:

```
  File "C:\_code\py\2008_pdfminersix_pull\pdfminer.six\tools\dumppdf.py", line 325, in main
    outfp = open(args.outfile, 'w')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Ev2geny\\AppData\\Local\\Temp\\tmpv592ckiv'
``` 

The same tests run without error in Linux

**Steps to reproduce the bug.**

Just run tests from the ```tests``` folder

**Additional information**
Most likely it is related to the usage of the **NamedTemporaryFile** in test modules. 
As described [here](https://stackoverflow.com/a/23212515/4432107),  ```NamedTemporaryFile``` actually creates **and opens** the file for you. Unix allows you to open it second time, Windows (starting from NT) apparently not. 

But I can see in the code, that the usage of  **NamedTemporaryFile** in tests already opens the file, hence operational code does not work later (on Windows)

E.g.:

[tests/test_tools_dumppdf.py](https://github.com/pdfminer/pdfminer.six/blob/0b44f7771462363528c109f263276eb254c4fcd0/tests/test_tools_dumppdf.py#L9)
```py
def run(filename, options=None):
    absolute_path = absolute_sample_path(filename)
    with NamedTemporaryFile() as output_file: # Temporary file gets open already here in the testing code
        if options:
            s = 'dumppdf -o %s %s %s' % (output_file.name,
                                         options, absolute_path)
        else:
            s = 'dumppdf -o %s %s' % (output_file.name, absolute_path)  # File name of the temporary file gets then extracted
        dumppdf.main(s.split(' ')[1:]) # File name gets passed to the operational code
```

and then in the operational code

[tools/dumppdf.py](https://github.com/pdfminer/pdfminer.six/blob/0b44f7771462363528c109f263276eb254c4fcd0/tools/dumppdf.py#L325)
```py
outfp = open(args.outfile, 'w')  #and then attempt is done to open the file with the same name again, which is not working on Windows
```

Most likely solution is not to use ```NamedTemporaryFile``` to open the file but only to generate candidate name as  described [here](https://stackoverflow.com/a/26541521/4432107).

**Comment by Ev2geny** [comment]
At the end I seem to have found quite a simple solution. Just close temporary test file, before running the text. Like this:

```py
def run(filename, options=None):
    absolute_path = absolute_sample_path(filename)
    with NamedTemporaryFile() as output_file: # Temporary file gets open already here in the testing code
        if options:
            s = 'dumppdf -o %s %s %s' % (output_file.name,
                                         options, absolute_path)
        else:
            s = 'dumppdf -o %s %s' % (output_file.name, absolute_path)  # File name of the temporary file gets then extracted

        output_file.close() # !!! This is a fix. Just close temporary file before passing its name to an operational code
        dumppdf.main(s.split(' ')[1:]) # File name gets passed to the operational code
```

**Comment by pietermarsman** [comment]
This looks like a genuine issue with the tests. It doesn't need to actually open the file in this code, it just needs to generate a temporary file path _and_ remove it again at the end of the test. 

As a fix we could use a to-be created `TemporaryFilePath()` context manager that passes the path on `__enter__()` and deletes the file path again on `__exit__()`.

I don't like closing the `NamedTemporaryFile` inside the `with` statement, because the `with` statement is supposed to do that.
