### ISSUE TITLE
DOC: Is it possible to check if a PDF is a valid PDF/A-1 or PDF/A-2?

### ISSUE THREAD

**Issue by MartinThoma** [pdfminer/pdfminer.six#472]
Can I check with pdfminer.six if there is active content within the PDF?

**Comment by pietermarsman** [comment]
Hi, 

Very late reply. 

The thing is: pdfminer.six is a package for extracting text from a PDF. It is not aimed at validating the content of the PDF. So, no, you cannot use pdfminer.six to check if PDF is valid PDF/A-1 or PDF/A-2. The best pdfminer.six can do is extract the version from the header. See Section 3.4.1 from the PDF reference.
