### ISSUE TITLE
Cannot pass None as parameter for --boxes-flow

### ISSUE THREAD

**Issue by a-franck** [pdfminer/pdfminer.six#477]
I cannot pass the value None to the parameter --boxes-flow when executing pdf2txt.py from the command line:

pdf2txt.py: error: argument --boxes-flow/-F: invalid float value: 'None'

According to the help, this should be possible:

  --boxes-flow BOXES_FLOW, -F BOXES_FLOW
                        Specifies how much a horizontal and vertical position
                        of a text matters when determining the order of lines.
                        The value should be within the range of -1.0 (only
                        horizontal position matters) to +1.0 (only vertical
                        position matters). You can also pass `None` to disable
                        advanced layout analysis, and instead return text
                        based on the position of the bottom left corner of the
                        text box.

**Comment by jstockwin** [comment]
@a-franck thanks for reporting this. This was me not being careful enough when I enabled allowing boxes-flow to be `None`. I agree it's an issue and will fix it ASAP!
