### ISSUE TITLE
split a multi-page pdf file into multiple pdf files

### ISSUE THREAD

**Issue by luke4u** [pdfminer/pdfminer.six#478]
**Feature request**

- A description of the feature you would like to have
As the title implies, a feature to save a pdf file by page. Each page can be saved as a pdf file.

- If relevant, the context that you are in. What are you trying to achieve?
generic feature, no specific context needed. It would be very valuable in cases, such as when users are only interested in certain pages. Or when file conversion is wanted but converting a pdf file with too many pages is not effective. 

- If possible, an example of what you want to achieve. Include the PDF that you are working on. Include the output that you would like to have. 
For instance, split below pdf into pdfs per page. 
[AR19_MEDIA_Transcript_FINAL.pdf](https://github.com/pdfminer/pdfminer.six/files/5119931/AR19_MEDIA_Transcript_FINAL.pdf)

**Comment by jacobtylerwalls** [comment]
FYI I use PyPDF2 for this.

**Comment by BigAndini** [comment]
PyPDF2 does not support new encryptions. I got here through pdfplumber which has implemented pdfminer. It would be great to get a simple example on how to open a pdf file and not save the text itself, but the unencrypted pdf file or even the single pages of the pdf file in separate files.

**Comment by MartinThoma** [comment]
@BigAndini PyPDF2 recently added decryption support for new encryptions :-)

**Comment by pietermarsman** [comment]
pdfminer.six is for extracting text from a PDF, you cannot use it to split a PDF.
