### ISSUE TITLE
Out of the box Mandarin Functionality

### ISSUE THREAD

**Issue by tmgcassidy** [pdfminer/pdfminer.six#480]
**Feature request**

This is an amazing tool- but I cannot for the life of me figure out how to get the chinese language functionality set up, and there are no tutorials I can find

I am trying to scan chinese language PDFs and extract the characters the way PDFminer would do for an english language pdf

paragraph text looks like this when copied from the pdf: 
```
党的⼗七⼤报告提出，必须站在国家安全和发展战略全局的⾼度，统
筹经济建设和国防建设，⾛出⼀条中国特⾊军民融合式发展路⼦，在全⾯
建设⼩康社会进程中实现富国和强军的统⼀。实施军民融合发展战略，必
须以科学发展观为指导，分析研究当前我国军民融合发展现状和⾯临的主
要问题，明确推进我国军民融合发展的战略举措。
```

I want it to look like:
```
       党的⼗七⼤报告提出，必须站在国家安全和发展战略全局的⾼度，统筹经济建设和国防建设，⾛出⼀条中国特⾊军民融合式发展路⼦，在全⾯建设⼩康社会进程中实现富国和强军的统⼀。实施军民融合发展战略，必须以科学发展观为指导，分析研究当前我国军民融合发展现状和⾯临的主要问题，明确推进我国军民融合发展的战略举措。
```

**Comment by pietermarsman** [comment]
Hi, 

Could you describe in more detail what you want? 
- Include the example pdf. 
- Describe the difference in output you need.

**Comment by pietermarsman** [comment]
Ok. Thanks for getting back on this. 

I'm closing the issue because of lack of specific details.
