### ISSUE TITLE
Wrong conversion for a specific file

### ISSUE THREAD

**Issue by arvindpdmn** [pdfminer/pdfminer.six#481]
**Bug report**

Spaces between words are missing in HTML. Output is unreadable. See attachment of page 1 of HTML output. Conversion used the following code on PDF file [https://www.aclweb.org/anthology/E17-1087.pdf](https://www.aclweb.org/anthology/E17-1087.pdf):
```
        with open(html_fname, mode='wb') as fout:
            with open(pdf_fname, "rb") as pdfin:
                extract_text_to_fp(pdfin, fout, output_type = 'html', laparams = LAParams())
```

I did the same conversion online at [https://www.pdftohtml.net/](https://www.pdftohtml.net/) and I got correct output.

![Screenshot_2020-08-30 Screenshot](https://user-images.githubusercontent.com/5135463/91652479-60121780-eab5-11ea-8fa8-1dde9f4bb7d8.png)

**Comment by pietermarsman** [comment]
Try tweaking the [`LAParams`](https://pdfminersix.readthedocs.io/en/latest/reference/composable.html). E.g. lower the `word_margin` to get more words.
