### ISSUE TITLE
functions from pdfminer.high_level are not found

### ISSUE THREAD

**Issue by geoffwalmsley** [pdfminer/pdfminer.six#485]
Description:
Importing from pdfminer.high_level causes import errors. Specifically:

- extract_text and extract_pages fails
- extract_text_to_fp works

Reproduce:
```
pip install pdfminer.six
from pdfminer.high_level import extract_text
from pdfminer.high_level import extract_pages
```

Error output:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-23-b03587d9bc4a> in <module>
----> 1 from pdfminer.high_level import extract_text

ImportError: cannot import name 'extract_text' from 'pdfminer.high_level'

**Comment by Colanim** [comment]
Can you tell what the following code return for you ?

```python
import pdfminer
dir(pdfminer)
```

**Comment by geoffwalmsley** [comment]
Hi - thanks for getting back to me.

This what is in dir(pdfminer)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__',
'__name__', '__package__', '__path__', '__spec__', '__version__']

Thanks

**Comment by Colanim** [comment]
For me uninstalling and reinstalling fixed the problem.

```
pip uninstall pdfminer.six -y
pip install -u pdfminer.six
```

**Comment by geoffwalmsley** [comment]
This worked - also a couple of dependency issues I had to sort out. Thanks so much :)

**Comment by go-dustin** [comment]
I'm getting the same issue. I uninstalled and reinstalled and I still don't have any functions available. 

Successfully installed pdfminer.six-20200726

dir(pdfminer)
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__']
