### ISSUE TITLE
substituting the missing font

### ISSUE THREAD

**Issue by NeoWang9999** [pdfminer/pdfminer.six#496]
## Feature request
handle PDF file that does not contain any embedded font.

from [this](https://github.com/jsvine/pdfplumber/issues/269) issue.

## example PDF file
[Sponsorship Agreement Template (CN) 1-未改动.pdf](https://github.com/pdfminer/pdfminer.six/files/5205464/Sponsorship.Agreement.Template.CN.1-.pdf)

## example code

```
from pdfminer.pdfparser import PDFParser, PDFDocument
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import PDFPageAggregator
from pdfminer.layout import LTTextBoxHorizontal, LAParams
from pdfminer.pdfinterp import PDFTextExtractionNotAllowed


pageList = []
res = "" 
f = open(ftp_path, 'rb')
fp = PDFParser(f)
parser = fp
doc = PDFDocument()
parser.set_document(doc)
doc.set_parser(parser)
doc.initialize()
if not doc.is_extractable:
    raise PDFTextExtractionNotAllowed
else:
    rsrcmgr = PDFResourceManager()
    laparams = LAParams()
    device = PDFPageAggregator(rsrcmgr, laparams=laparams)
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    for page in doc.get_pages():
        page_res = ""
        interpreter.process_page(page)
        layout = device.get_result()
        for x in layout:
            if (isinstance(x, LTTextBoxHorizontal)):
                results = x.get_text()
                res = res + results
                page_res = page_res + results
        pageList.append(page_res)
return pageList, res
```
now the pageList is empty, because this PDF does not contain any embedded font.

## Environment

- pdfminer.six: [20200517]
- Python version: [3.7.7]
- OS: [Mac OS]

## other note

when i tried with pdfbox like:
```

p = pdfbox.PDFBox()
p.extract_text(input_path=f_path, console=False)

```
it worked fine and output the txt file. but I need the chars coordinate information.
pdfbox is able to extract could most likely because of it substituting the missing font.

**Comment by pietermarsman** [comment]
It works fine when I use the command-line interface:

```
$ python tools/pdf2txt.py ~/Downloads/Sponsorship.Agreement.Template.CN.1-.pdf -p 1          
1

舡产品发布会赞助协议

甲方,香港交易及结算所有限公司

地址,香港中环康乐广场8号交易广场2期8楼

乙方,深圳市金证优智科技有限公司

地址,深圳市南山区高新南五道金证科技大厦3楼
...
```

In your code fragment you never initialize `pageList` as a list. Could that have something to do with it?

**Comment by pietermarsman** [comment]
Closing this while awaiting response.
