### ISSUE TITLE
erro 

### ISSUE THREAD

**Issue by Arwa200** [pdfminer/pdfminer.six#501]
Hi, 
when I'm trying to run this tool, I got this error.. 

![Screen Shot 2020-09-15 at 10 10 06 AM](https://user-images.githubusercontent.com/42224049/93177710-e1b3a780-f73b-11ea-9b3b-3dd3017850f1.png)

Thank you

**Comment by pietermarsman** [comment]
Hi @Arwa200 

You can do `pdf2txt.py` instead of `python pdf2txt.py`. That should work if you installed pdfminer.six with pip. 


(Also note that we don't support python2 anymore since January. If you use python3 you get a slightly more robust pdfminer.six).

**Comment by Arwa200** [comment]
Hi 

`PIP pdf2txt.py`
it's successfully installed, but still got no result!

![Screen Shot 2020-09-29 at 1 44 04 PM](https://user-images.githubusercontent.com/42224049/94549028-4140a580-025a-11eb-99dc-4703726b3a8d.png)
