### ISSUE TITLE
Figure detected incorrect

### ISSUE THREAD

**Issue by Jessica870807** [pdfminer/pdfminer.six#502]
While using PDFminer at this type of PDF files to obtain items, whole pdf page is detected as Figure which is incorrect extraction. 

This type of File for instance:
[no1-1.pdf](https://github.com/pdfminer/pdfminer.six/files/5230236/no1-1.pdf)
[no3-1.pdf](https://github.com/pdfminer/pdfminer.six/files/5230247/no3-1.pdf)
[no5-1.pdf](https://github.com/pdfminer/pdfminer.six/files/5230250/no5-1.pdf)

**Comment by pietermarsman** [comment]
Hi @Jessica870807,

Thanks for sharing the issue. Can you add the code you are using to the description of this issue?

**Comment by Ev2geny** [comment]
I just noticed, that my Adobe Acrobat Reader DC version 2020.012.20043 Displays an error, when opening these files

_An error exists on this page. Acrobat may not display page correctly. Please contact the person who created the PDF document to correct the problem_

**Comment by pietermarsman** [comment]
I used `pdf2txt.py` to extract the text, and `dumppdf.py` to extract all the objects and the output looks just fine. @Jessica870807 can you be more specific about what is going wrong? Can you add a minimal reproducible example that shows the problem?

**Comment by Jessica870807** [comment]
Thank you! I’ve already solved the problem.
