### ISSUE TITLE
Drop Python 3.4/3.5 support

### ISSUE THREAD

**Issue by estshorter** [pdfminer/pdfminer.six#503]
**Feature request**

EOL of Python 3.4 and 3.5 are 2019/3 and 2020/9, respectively.
How about dropping support of these versions this October so that we can enjoy new features like f-strings?

**Comment by pietermarsman** [comment]
Yes, that's a great suggestion! Didn't know that python 3.5 is also already eol. This will also help with #362. 

Let's deprecate them for one release before actually removing them.
