### ISSUE TITLE
no module named 'pdfminor.settings'

### ISSUE THREAD

**Issue by gencee** [pdfminer/pdfminer.six#52]
Hey man! Thks for doing this. I downloaded the package and followed your instructions. Unfortunately when i try to scrap a pdf, I get an Import Error which says: "no module named 'pdfminor.settings'". I checked the folder pdfminor if the settings file was missing but it isn't. Any idea what the problem might be?
cheers, ed

**Comment by goulu** [comment]
Hey man ! You probably mixed up versions and paths with the original pdfminer from euske which had no settings ... You should install "pdfminer.six" XOR "pdfminer" ...

Please reopen in case it's a different problem.
