### ISSUE TITLE
convert object class

### ISSUE THREAD

**Issue by watanka** [pdfminer/pdfminer.six#521]
I'm not sure if you already have this feature or not, but I was wondering if you can convert(specify) pdf information object like layout.LTTextBoxHorizontal into LTTextLine or even LTChar object.

object class

LTTextBoxHorizontal -> LTTextLine or LTChar

Thank you very much

**Comment by pietermarsman** [comment]
Hi @watanka,

The `LTTextBoxHorizontal` is a grouping of one or more `LTTextLine`'s. Likewise `LTTextLine` is a grouping of one or more `LTChar`'s. So in a strict sense, converting them is not possible. However, you can create a list of all the `LTTextLine`'s or `LTChar`'s easily if that's what you want. 

Does that answer your question?

**Comment by watanka** [comment]
ooo sure it did. Thank you!
