### ISSUE TITLE
Required package "sortedcontainers" is not used

### ISSUE THREAD

**Issue by estshorter** [pdfminer/pdfminer.six#524]
**Bug report**
Pdfminer.six stopped importing and using `sortedcontainers` since 44b223cf0a3b29bc1f0c3ece71c483a22b71614d.
This package should be removed from `setup.py`.

https://github.com/pdfminer/pdfminer.six/blob/c8cceb7c58deec9e647be6d3957e03442770bdd0/setup.py#L18

**Comment by pietermarsman** [comment]
Good catch
