### ISSUE TITLE
🐛 LTChar direct child of LTPage : 'LTChar' object is not iterable

### ISSUE THREAD

**Issue by astariul** [pdfminer/pdfminer.six#526]
## File for reproducing the bug

[2.pdf](https://github.com/pdfminer/pdfminer.six/files/5399532/2.pdf)

## Description

When running the following code from the [official documentation](https://pdfminersix.readthedocs.io/en/latest/tutorial/extract_pages.html) on the linked file :

```python
from pdfminer.high_level import extract_pages
from pdfminer.layout import LTTextContainer, LTChar
for page_layout in extract_pages("test.pdf"):
    for element in page_layout:
        if isinstance(element, LTTextContainer):
            for text_line in element:
                for character in text_line:
                    if isinstance(character, LTChar):
                        print(character.fontname)
                        print(character.size)
```

I'm meeting the following error :

> Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
TypeError: 'LTChar' object is not iterable

---

**It appears to be because somehow, a `LTLine` object is being the direct child of `LTPage`.**

But from the documentation it seems not possible :

![image](https://user-images.githubusercontent.com/43774355/96409733-b2072c00-1220-11eb-8c34-b40a665d181a.png)

All `LTLine` should be a child of `LTTextBox`...

**Comment by pietermarsman** [comment]
Hi @Colanim, 

I cannot reproduce the issue. If I run your code with the _2.pdf_ I get the following output:

```
MJEENE+YGO12
5.9500000000000455
MJEENE+YGO12
5.9500000000000455
MJEENE+YGO12
5.9500000000000455
MJEENE+YGO12
5.9500000000000455
MJEENE+YGO12
...
```

What version of pdfminer.six are you using?

**Comment by Colanim** [comment]
I'm using version `20200726`.

After upgrading to `20201018`, I still can reproduce the error...

>MJEENE+YGO12
5.9500000000000455
MJEENE+YGO12
5.9500000000000455
MJEENE+YGO12
5.9500000000000455
MJEENE+YGO12
5.9500000000000455
MJEENE+YGO12
5.9500000000000455
[...]
MJEENE+YGO12
5.0
MJEEOF+YGO11
8.0
MJEEOF+YGO11
8.0
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
TypeError: 'LTChar' object is not iterable

---

Anything else I can do to help you reproduce the error ?

**Comment by MolinDU9527** [comment]
I had the same error. I am using 20201018

The error occurs in processing a complex pdf, include vertical Japanese.

**Comment by MolinDU9527** [comment]
I had the same error. problem comes from below
"for text_line in element:"  the child of a element may not be a text_line however the code take it for granted.
here is a modified one

if isinstance(element, LTTextContainer):
    for text_line in element:                   # this text_line may not be a true "text_line"
        if isinstance(text_line , LTTextLine): 
        for character in text_line:             # this character may not be a true "character "
            if isinstance(character, LTChar):
                print(character.fontname)
                print(character.size)

however, this still be far from enough, please assume actual case complex. ex: a LTTextBox under LTTextBox, etc.
so a iterative fuction + if / elif is ultimate solution (I am working on it)

**Comment by eisensafran** [comment]
I can reproduce this issue here.

Thanks for the heads-up @MolinDU9527, I followed your approach and it is sufficient for my needs. For an easier copy-paste here is the code with correct intendation: 

```
if isinstance(element, LTTextContainer):
    for text_line in element:  # this text_line may not be a true "text_line"
        if isinstance(text_line, LTTextLine):
            for character in text_line:  # this character may not be a true "character "
                if isinstance(character, LTChar):
                    print(character.size)
```
