### ISSUE TITLE
When's the next PyPI release?

### ISSUE THREAD

**Issue by sergei-maertens** [pdfminer/pdfminer.six#53]
Hi,

We're currently in the process of upgrading a codebase from Python 2 to 3, and running into the bug in https://github.com/pdfminer/pdfminer.six/issues/15

This has been fixed in master, and a RC with release date Jan. 19th was created. When can this be expected? For the time being, I'll run of a known-good commit, but I'd prefer to install from PyPI at all times.

**Comment by goulu** [comment]
right now : https://pypi.python.org/pypi/pdfminer.six/20170418 :-)

sorry for the delay ...

**Comment by sergei-maertens** [comment]
Thanks! Giving it a test run now.
