### ISSUE TITLE
Annotations not detected by pdfminer

### ISSUE THREAD

**Issue by Colanim** [pdfminer/pdfminer.six#531]
## Description

I annotated a PDF file using the library [`pdf_annotate`](https://github.com/plangrid/pdf-annotate/tree/master), and try to read it using `pdfminer`.

**But the annotations does not shows up.**

## To reproduce
[Original file](http://www.africau.edu/images/default/sample.pdf)  
[Annotated file](https://github.com/pdfminer/pdfminer.six/files/5419552/modified.2.pdf)

---

Running the following code :

```python
from pdfminer.high_level import extract_pages

page = list(extract_pages("file.pdf"))[0]

for elem in page:
    print(elem)
```

---

I run this code for both file, and in both case I have :

> <LTTextBoxHorizontal [...] ' A Simple PDF File \n'>
<LTTextBoxHorizontal [...] ' This is a small demonstration .pdf file - \n'>
<LTTextBoxHorizontal [...] ' just for use in the Virtual Mechanics tutorials.  [...]'>
<LTTextBoxHorizontal [...] ' And more text. And more text. And more text. [...]'>
<LTTextBoxHorizontal [...] ' And more text. And more text. And more text. [...]'>

**Comment by pietermarsman** [comment]
Hi @Colanim,

It looks like the annotation is places directly on top of the title. It does not remove the title (explaining why it still shows in the output) it just hides it. 

Annotations themselves are not extracted by pdfminer.six. In fact, pdfminer.six only converts the PDF objects to a python dictionary but does not use that at all. If you want, you can use pdfminer.six to extract these object. 

```
from pdfminer.converter import PDFPageAggregator
from pdfminer.pdfinterp import PDFResourceManager
from pdfminer.pdfpage import PDFPage
from pdfminer.utils import open_filename
from pdfminer.pdftypes import resolve1


with open_filename("/home/pieter/Downloads/modified.2.pdf", "rb") as fp:
    resource_manager = PDFResourceManager()
    device = PDFPageAggregator(resource_manager)
    for page in PDFPage.get_pages(fp):
        if page.annots is not None:
            for annotation in page.annots:
                print(resolve1(annotation))
```

It outputs:

```
{'AP': {'N': <PDFObjRef:14>}, 'BS': {'S': /'S', 'Type': /'Border', 'W': 1}, 'C': [1, 1, 1], 'CreationDate': b"D:20201022013451+00'00", 'F': 4, 'IC': [1, 1, 1], 'M': b"D:20201022013451+00'00", 'NM': b'1c10ec4d-abb6-415e-9abd-1b45b3cdc031', 'P': <PDFObjRef:5>, 'RD': [0.5, 0.5, 0.5, 0.5], 'Rect': [56.375, 715.691, 293.923, 744.691], 'Subtype': /'Square', 'Type': /'Annot'}
{'AP': {'N': <PDFObjRef:13>}, 'BS': {'S': /'S', 'Type': /'Border', 'W': 0}, 'C': [], 'Contents': b'I Modified this title', 'CreationDate': b"D:20201022013451+00'00", 'DA': b'0 0 0 rg /PDFANNOTATORFONT1 27. Tf', 'F': 4, 'M': b"D:20201022013451+00'00", 'NM': b'c5569e7a-b6dc-49e0-af25-8c44f534c6f8', 'P': <PDFObjRef:5>, 'Rect': [57.375, 716.691, 392.923, 843.691], 'Subtype': /'FreeText', 'Type': /'Annot'}
```

Does that answer your question? If so, can you close the issue?
