### ISSUE TITLE
Add Timeout option when processing PDF page 

### ISSUE THREAD

**Issue by EucliTs0** [pdfminer/pdfminer.six#532]
**Feature request**

Good morning,

There are some PDF documents, where it takes around 10-12 seconds to get the output. The issue comes when the PDF is not searchable and editable and in fact it is a 'PDF Image'. And for example, the resulting XML contains analysis regarding curves and lines.

I cannot add the PDF because it contains sensitive data, but I  **attach the XML output**.

Do you consider adding a Timeout option when processing a PDF page? And if it exceeds a certain threshold, you skip the page or break?

In our work, what we want to achieve is that if the time processing of a page with PDFMiner takes more than 10 seconds for example, we fall back to another service where we convert PDF to image and we continue with other processes after.

Thank you in advance.

[xml_output.zip](https://github.com/pdfminer/pdfminer.six/files/5428738/xml_output.zip)

**Comment by pietermarsman** [comment]
Hi @EucliTs0, 

In this case I would like to improve speed rather that adding a timeout option. But for a proper analysis and fix we need an example of the PDF, and you indicated that's not possible. 

If you need the timeout anyway, you can implement it yourself. A PDF is structured in pages, and pdfminer.six also runs analysis per page. So you can loop over the pages and quit processing if it takes to long. E.g. combine the code from this [SO post](https://stackoverflow.com/questions/14920384/stop-code-after-time-period) with the code to loop over pages:

```
   from pdfminer.high_level import extract_pages
   for page_layout in extract_pages("test.pdf"):
       for element in page_layout:
           print(element)
```

Does this answer your question?

**Comment by EucliTs0** [comment]
Hello @pietermarsman ,
Thank you for your answer :+1:
