### ISSUE TITLE
Can internal links be extracted?

### ISSUE THREAD

**Issue by markfirmware** [pdfminer/pdfminer.six#536]
On page 154:
https://infocenter.nordicsemi.com/pdf/nRF51_RM_v3.0.1.pdf#page=154

there is a link from RXD to:

https://infocenter.nordicsemi.com/pdf/nRF51_RM_v3.0.1.pdf#%5B%7B%22num%22%3A2105%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C56.692%2C610.554%2Cnull%5D

How can all of these internal links be extracted?

Thanks, Mark

**Comment by pietermarsman** [comment]
Hi @markfirmware,

This information is stored in so-called annotations. You can extract them with the following code:

```python
from pdfminer.converter import PDFPageAggregator
from pdfminer.layout import LAParams
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.pdfpage import PDFPage
from pdfminer.pdftypes import resolve1
from pdfminer.utils import open_filename

with open_filename('nRF51_RM_v3.0.1.pdf', "rb") as fp:
    resource_manager = PDFResourceManager()
    device = PDFPageAggregator(resource_manager, laparams=LAParams())
    interpreter = PDFPageInterpreter(resource_manager, device)
    for page in PDFPage.get_pages(fp, [153]):
        for annotation_ref in resolve1(page.annots):
            annotation = resolve1(annotation_ref)
            if annotation['Subtype'].name == 'Link':
                action = resolve1(annotation['A'])
                print(action['D'])
```

If you want to know more about this, read section 8.4.5 about "Annotation Types" in the [pdf reference manual. ](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdf_reference_archive/pdf_reference_1-7.pdf). You are probably most interested in the Link Annotation. 

Can you close this issue if you consider your question answered.

**Comment by markfirmware** [comment]
How do I extract the text under the rectangle of the annotation?

**Comment by chandansp27** [comment]
Hello,

I am also finding it difficult to extract the hyperlinks from a pdf, any insights on how to get the text the hyperlink leads to would be really great.

The PDF which I am working on: https://cdsco.gov.in/opencms/resources/UploadCDSCOWeb/2022/drug_rules/Drugs%20Rules,%201945%20(1).pdf
