### ISSUE TITLE
ImportError: cannot import name 'LITERALS_JBIG2_DECODE'

### ISSUE THREAD

**Issue by LianaN** [pdfminer/pdfminer.six#542]
**Bug report**

I get the following error when running `from pdfminer.high_level import extract_pages`:

```
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pdfminer/high_level.py in <module>
      7 from .converter import XMLConverter, HTMLConverter, TextConverter, \
      8     PDFPageAggregator
----> 9 from .image import ImageWriter
     10 from .layout import LAParams
     11 from .pdfdevice import TagExtractor

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pdfminer/image.py in <module>
      8 from .pdfcolor import LITERAL_DEVICE_GRAY
      9 from .pdfcolor import LITERAL_DEVICE_RGB
---> 10 from .pdftypes import LITERALS_DCT_DECODE, LITERALS_JBIG2_DECODE
     11 
     12 

ImportError: cannot import name 'LITERALS_JBIG2_DECODE'
```

_Environment:_

Jupyter Notebook, Python 3.6

**Comment by pietermarsman** [comment]
Hi @LianaN,

I cannot replicate this issue. It is probably an issue with your local setup. 

Which pdfminer.six version are you using? 

Can you remove all pdfminer.six from your system and install it only once. Import errors like these sometimes happen when you mix the original pdfminer with pdfminer.six installations.

**Comment by ldc-lewisc** [comment]
@milanjelisavcic Just went through this myself and resolved. 

I expect the issue is that pdfminer (not pdfminer.six) still exists in your package store, looks like it could be a anaconda issue.
Delete pdfminer and pdfminer.six by deleting the folders manually, then reinstalling pdfminer.six using pip resolves the issue.

**Comment by pietermarsman** [comment]
That is indeed what I expect as well.
