### ISSUE TITLE
**Order of th text is mixed up and finding them in wrong places:**

### ISSUE THREAD

**Issue by uday-allu** [pdfminer/pdfminer.six#557]
Order of th text is mixed up and finding them in wrong places:

<img width="1147" alt="Screenshot 2020-12-02 at 4 11 05 PM" src="https://user-images.githubusercontent.com/71138720/100862284-01e04080-34b9-11eb-9974-016d94b638e3.png">

**I'm using the  following code:**
```
output_string = StringIO()
with open('/Users/udayallu/similarity_search_training/Pol_ProcHdbk1_23.pdf', 'rb') as in_file:
    parser = PDFParser(in_file)
    doc = PDFDocument(parser)
    rsrcmgr = PDFResourceManager()
    device = TextConverter(rsrcmgr, output_string, laparams=LAParams())
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    for page in PDFPage.create_pages(doc):
        interpreter.process_page(page)

print(output_string.getvalue())
```

OS: Mac os
python versions: 3.7
**Below is the pdf file:**

[Pol_ProcHdbk1_23.pdf](https://github.com/pdfminer/pdfminer.six/files/5628647/Pol_ProcHdbk1_23.pdf)

_Originally posted by @uday-allu in https://github.com/pdfminer/pdfminer.six/issues/138#issuecomment-737148670_

**Comment by pietermarsman** [comment]
Hi! 

I'm getting this output:

```
EMPLOYMENT 

directly impacted. The determination of when any of these events has occurred rests solely with 
the administration of the University. To view the entire Staff Reduction in Workforce Policy, 
please click here. For information on additional HR policies, please refer to the online University 
wide policy site at:  http://www.udayton.edu/policies/hr. 

Section 2 

Separation from Service 

Non-faculty employees of the University of Dayton are employed with an “at will” status. 

Employees are not employed for any definite term and either party for any reason, with or 
without cause, may terminate the employment relationship at any time. Only the President of the 
University (or the board of trustees) has authority to enter into any Agreement for employment 
for any specified period of time or to make any agreement contrary to the foregoing. 

Voluntary 

Employee Responsibility: 

 Upon resignation, all employees are requested to submit a written letter of resignation to
their immediate supervisor and the Office of Human Resources prior to their last day of
employment.

 Exempt Positions - at least four working weeks of notice prior to the date of separation

 Nonexempt Positions - at least two working weeks of notice prior to the date of

from service.

separation from service.

 The employee is asked to schedule a personal exit interview with his/her Human

Resources Generalist and complete an Exit Interview Questionnaire prior to leaving the
University.

o The terminating employee will need to bring the exit interview questionnaire to
the exit interview or mail the form to the following address: Office of Human
Resources, University of Dayton, 300 College Park, Dayton, Ohio 45469-1614,
Attn: Staffing Department.

Supervisor Responsibility: 

 Upon receiving written notification that an employee is leaving, the supervisor is

responsible for promptly completing the Personnel Action Form (PAF).

o Personal Action Form (PAF) and resignation letter are forwarded to the Office of

Human Resources to start the exit process.

 Before the employee separates from the University, the supervisor is responsible for
completing the Employee Separation Checklist (pdf), which requires collection of
University property, identification card, etc., and forwarding the completed form, along
with the separating employees ID card, to the Office of Human Resources as the final
step in the separation process.

Human Resources Responsibility: 

17 


```

That looks pretty good to me. Could you clarify what you would like to have improved?

**Comment by uday-allu** [comment]
Hi,
 with the above mentioned code i ran and some first paragraph is missing from the output. Below mentioned is the missing text in my output .

EMPLOYMENT 
directly impacted. The determination of when any of these events has occurred rests solely with 
the administration of the University. To view the entire Staff Reduction in Workforce Policy, 
please click here. For information on additional HR policies, please refer to the online University 
wide policy site at:  http://www.udayton.edu/policies/hr.

**Comment by pietermarsman** [comment]
Which version of pdfminer.six are you using?

**Comment by uday-allu** [comment]
20201018

**Comment by Hund** [comment]
I just installed `pdfminer.six-20201018` and `sortedcontainers-2.4.0`. I also have this issue:

**PDF-document:**

>This chapter provides just enough information to edit a file with Vim. Not
well or fast, but you can edit. Take some time to practice with these
commands, they form the base for what follows.

**Output:**

>This chapter provides just enough information to edit a file with Vim.
Take some time to practice with these
well or fast, but you can edit.
commands, they form the base for what follows.
>
>Not

It's from the document "[VIM USER MANUAL](https://www.vi-improved.org/vimusermanual.pdf)" by Bram Moolenaar.

**Comment by AnasAG** [comment]
Similar issue, both in LTR and RTL (Arabic) languages.

**Comment by MyEvilpumpkin** [comment]
Hi!

Try this: `laparams=LAParams(boxes_flow=None)`
This fix helped me restore order.

**Comment by ZafarShadman09** [comment]
`laparams=LAParams(boxes_flow=None)`

This doesn't work

**Comment by pietermarsman** [comment]
Closed because I cannot reproduce the original issue.
