### ISSUE TITLE
Conversion to xml missing text information

### ISSUE THREAD

**Issue by abdul-2106** [pdfminer/pdfminer.six#56]
@goulu : Thanks for this awesome package. It works like a charm. It actually resolves [this issue](https://github.com/jaepil/pdfminer3k/issues/5) which I was facing while using `pdfminer3k`.

I have ran into an issue with [this pdf file](https://github.com/pdfminer/pdfminer.six/files/931888/2b.pdf). I am trying to get an xml output from it by running `pdf2txt.py -A -o output.xml -t xml 2b.pdf`. But the output xml just contains the following and misses all the text information:

![capture](https://cloud.githubusercontent.com/assets/9295108/25164536/37887870-24ef-11e7-9ec8-2b476236a179.JPG)

Interestingly, when I convert this file to xml using `pdfminer3k` it gives a "list index out of range" error at [this line](https://github.com/jaepil/pdfminer3k/blob/master/pdfminer/pdfparser.py#L399). And if I change the code at that line to the following then it works.
```
if x:
  try:
    objid1 = x[-2]
    genno = x[-1]
  except:
    return None
```

Can you please help?

**Comment by goulu** [comment]
problem reproduced in tests, but copying suggested solution from pdfminer3k (which diverged a lot...) doesn't help. (code never enters the objid1!=objid section) https://github.com/pdfminer/pdfminer.six/commit/82af7f0aaca9091ab4891439e0638626e9b76af2

No clue why this pdf is special ...

**Comment by abdul-2106** [comment]
Just FYI, this pdf passes in the original `pdfminer`.

**Comment by abdul-2106** [comment]
It seems like this issue is fixed in one of the recent releases. Hence, closing the issue.
