### ISSUE TITLE
dumppdf.py error extracting ToC

### ISSUE THREAD

**Issue by homofortis** [pdfminer/pdfminer.six#560]
```
./bin/dumppdf.py --extract-toc ~/Downloads/2011.09926.pdf 
<outlines>
Traceback (most recent call last):
  File "./bin/dumppdf.py", line 372, in <module>
    sys.exit(main())
  File "./bin/dumppdf.py", line 352, in main
    dumpoutline(
  File "./bin/dumppdf.py", line 155, in dumpoutline
    pageno = pages[dest[0].objid]
AttributeError: 'int' object has no attribute 'objid'
```
[2011.09926.pdf](https://arxiv.org/pdf/2011.09926.pdf)

same issue (but closed?!?):
[dumppdf.py unable to extract ToC](https://github.com/pdfminer/pdfminer.six/issues/180)

**Comment by pietermarsman** [comment]
I can replicate this with:

```
 python tools/dumppdf.py --extract-toc ~/Downloads/2011.09926.pdf
```

**Comment by estshorter** [comment]
I'm not familiar with PDF specification, but could fix the issue by changing 
https://github.com/pdfminer/pdfminer.six/blob/22f90521b823ac5a22785d1439a64c7bdf2c2c6d/tools/dumppdf.py#L138
to the following.
``` python
        if isinstance(dest, str) or isinstance(dest, bytes):
```
Also, 
https://github.com/pdfminer/pdfminer.six/blob/22f90521b823ac5a22785d1439a64c7bdf2c2c6d/tools/dumppdf.py#L164
should be the following to make the variable `s` a `str` type.
``` python
            s = e(title)
```
