### ISSUE TITLE
Remove unnecessary "return" statements throughout pdfminer

### ISSUE THREAD

**Issue by adrianholovaty** [pdfminer/pdfminer.six#561]
Hello — thanks for keeping pdfminer going with this fork!

I've noticed many of the functions/methods within pdfminer have unnecessary `return` statements. See https://github.com/pdfminer/pdfminer.six/blob/develop/pdfminer/converter.py for example.

PEP 8 doesn't explicitly say anything about this, but my own two cents are that these statements are utterly unnecessary.

[I made a pull request addressing this](https://github.com/euske/pdfminer/pull/62) back in 2014 (for the original pdfminer), but the maintainer didn't like the idea. Perhaps now is a better time to make this change, now that this fork has different maintainers?

Let me know if you agree this is worth doing, and I'll put a pull request together.

**Comment by pietermarsman** [comment]
Yes, I also think empty return statements are useless. 

@jstockwin @side2k any objections?

**Comment by jstockwin** [comment]
I agree, the empty return statements can go.

**Comment by side2k** [comment]
Agree too!
