### ISSUE TITLE
pdfminer reorders some columns

### ISSUE THREAD

**Issue by puraminy** [pdfminer/pdfminer.six#564]
[Human-Behavior-Inspired-Machine-Reading-Comprehens.pdf](https://github.com/pdfminer/pdfminer.six/files/5744669/Human-Behavior-Inspired-Machine-Reading-Comprehens.pdf)
This is my code to retrieve the text of a pdf.

 ```
  text = ""
    with open(file, 'rb') as in_file:
        parser = PDFParser(in_file)
        doc = PDFDocument(parser)
        if not doc.is_extractable:
            show_err("The Pdf file doesn't allow text extraction")
            return ""
        rsrcmgr = PDFResourceManager()
        laparams = LAParams()
        device = PDFPageAggregator(rsrcmgr, laparams=laparams)
        interpreter = PDFPageInterpreter(rsrcmgr, device)
  
        for page in PDFPage.create_pages(doc):
            interpreter.process_page(page)
            layout = device.get_result()
            for element in layout:
                # if isinstance(element, LTFigure):
                if isinstance(element, LTTextBox):
                    p = element.get_text().strip()
                    ... 
```
However, as I traced the code it reorders some columns. I attached the problematic pdf. It prints the column containing the section **5.3 Lexical features** after section **5.4 Matching**
[Uploading Human-Behavior-Inspired-Machine-Reading-Comprehens.pdf…]()

**Comment by pietermarsman** [comment]
Hi @puraminy,

The basic problem is that PDF is unaware of the algorithm. Pdfminer.six layout algorithm is solely based on the positioning of the individual characters. By default pdfminer.six groups all the paragraphs into boxes and then tries to order them from top-to-bottom from left-to-right. 

You you can trick the algorithm into parsing the columns better by merging all the lines in a column into one box. This is done by increasing the `--line-margin`. The downside is that the enters between paragraphs are lost. The upside is that the colums are ordered in the correct order. 

```
python tools/pdf2txt.py ~/Downloads/Human-Behavior-Inspired-Machine-Reading-Comprehens.pdf -p 7 --line-margin 2
```
