### ISSUE TITLE
Words are concatenated in PDFMiner's output

### ISSUE THREAD

**Issue by EucliTs0** [pdfminer/pdfminer.six#565]
Hello,

We are facing some issues in some PDF files, when we extract the content. Some words are concatenated, whereas in PDF it is obvious that there is whitespace among them.

For example, we could get:
`2018MME CORINNE BERTHIER4 RUE DU TEST75013 PARIS69043` instead of:
`2018 MME CORINNE BERTHIER 4 RUE DU TEST 75013 PARIS 69043`

PDFMiner.six version:
`python /home/dtsolakidis/anaconda3/bin/pdf2txt.py --version`
pdfminer.six v20201018

Just with cmd, can be confirmed:
`python /home/dtsolakidis/anaconda3/bin/pdf2txt.py ca801e38-ee3b-4e58-8a1e-ce0d8f0e02be-Anonym.pdf -S -t text  --maxpages 1 -o tax_output`

I attach a PDF, to reproduce the output.
[ca801e38-ee3b-4e58-8a1e-ce0d8f0e02be-Anonym.pdf](https://github.com/pdfminer/pdfminer.six/files/5748250/ca801e38-ee3b-4e58-8a1e-ce0d8f0e02be-Anonym.pdf)

We appreciate if you have some insights.
Inform me if you need some more details.

Thank you and Happy New Year!

**Comment by EucliTs0** [comment]
up up! did someone investigated?

**Comment by rain01** [comment]
Try playing around with `word_margin` in `LAParams`. That helped me. I'm not sure how to add it in command line though

**Comment by EucliTs0** [comment]
@rain01 Thank you for the response. Have you tried it on this specific pdf? Or in another one?
Could you please share the value of word_margin you used?

Thanks!

**Comment by EucliTs0** [comment]
We solved the current issue by setting:
 `LAParams(all_texts=True)`

I think it can be closed.
