### ISSUE TITLE
STSong-light font not recognized

### ISSUE THREAD

**Issue by tscrosb** [pdfminer/pdfminer.six#568]
### Bug report

Cannot recognize STSong-light

When using pdfminer, only the text that is not in STSong-light can be extracted.

I am using this pdf:

https://drive.google.com/file/d/16e1MNaLJ-GJpu-avKZNB9I_zQpV_8eJj/view?usp=sharing

I am running this code:
```
from io import StringIO

from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfparser import PDFParser

output_string = StringIO()
with open('800_20201031_DPD01030.pdf', 'rb') as in_file:
    parser = PDFParser(in_file)
    doc = PDFDocument(parser)
    rsrcmgr = PDFResourceManager()
    device = TextConverter(rsrcmgr, output_string, laparams=LAParams())
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    for page in PDFPage.create_pages(doc):
        interpreter.process_page(page)

print(output_string.getvalue())
```
**OUTPUT:**

```
TOTAL NO OF WITHDRAWALS:

TOTAL NO OF DEPOSIT:

Account Total Summary

TOTAL:
TOTAL:

TOTAL:

AS AT:

BAL.:
```

**EXPECTED OUTPUT:**

```
null

1

TOTAL NO OF WITHDRAWALS:

TOTAL NO OF DEPOSIT:

Account Total Summary

TOTAL:
TOTAL:

TOTAL:

AS AT:

BAL.:
```

**Comment by pietermarsman** [comment]
PDF stores information about the font-type and the unicode mapping separately. So the font is unrelated to the text that pdfminer.six extracts. Probably the font has a missing or errorneous `ToUnicode` mapping and that is why the font cannot be extracted. 

If this is still an issue, could you share the PDF in a permanent way? I can't access the drive doc.
