### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Blabla2017** [pdfminer/pdfminer.six#57]
Hi,

I am using Python 3.6 and I cannot set up Pdfminer. six.
While doing pdf2txt.py samples/simple1.pdf, an error appears : 
ModuleNotFoundError: No module named 'pdfminer.settings'

Has anyone run into the same problem?

Thank you very much in advance for your help!

**Comment by goulu** [comment]
same as https://github.com/pdfminer/pdfminer.six/issues/52 : you probably mixed up pdfminer.six with the original pdfminer (which had no settings module).

Please make sure you uninstall the pdfminer package and install pdfminer.six instead

**Comment by Blabla2017** [comment]
thank you very much !

2017-04-20 11:50 GMT+02:00 Goulu <notifications@github.com>:

**Comment by huyle93** [comment]
@goulu I am currently having a very similar issue. I have check my pip (pip freeze), i don't have the old pdfminer, only the pdfminer.six. However, i still get the same issue when running pdf2txt.py (env: python\r: No such file or directory). I also has a script file in anaconda that has (from pdfminer.converter import TextConverter), it gives an error of (ModuleNotFoundError: No module named 'pdfminer'). I am using python 3.6.3 via virtualenv. 
Please help!
