### ISSUE TITLE
Cannot import name 'extract_text' from 'pdfminer.high_level'

### ISSUE THREAD

**Issue by malhartakle** [pdfminer/pdfminer.six#570]
I am facing the error " ImportError: cannot import name 'extract_text' from 'pdfminer.high_level' (C:\Users\User\anaconda3\lib\site-packages\pdfminer\high_level.py) ".
Few minutes ago, it was work well and suddenly started this issue when i tried running it again.
I am using Jupyter notebook with Anaconda.

**Comment by nickswaya** [comment]
are you specifically importing the high level part? I had the same error until I changed 
import pdfminer 
to
import pdfminer.high_level

**Comment by malhartakle** [comment]
Yes.
The error got resolved when I installed the library from console again.
Thanks for your reply :)

Regards,
Malhar

**Comment by MohdHashim980** [comment]
I am facing the error "ImportError: cannot import name 'open_filename' from 'pdfminer.utils'  "

**Comment by pietermarsman** [comment]
@MohdHashim980  You probably have multiple versions of pdfminer (the original) and pdfminer.six installed. Make sure that only pdfminer.six is installed in your python environment.

**Comment by spielhoelle** [comment]
I faced a similar problem `cannot import name 'open_filename' from 'pdfminer.utils'` when using the [langchain cookbook](https://github.com/langchain-ai/langchain/blob/master/cookbook/Semi_structured_multi_modal_RAG_LLaMA2.ipynb?ref=blog.langchain.dev). Problem was python v.3.11x. I downgraded my env to 3.8.18 and it worked

**Comment by IgorGanapolsky** [comment]
Is there a solution?  I am facing the same from [OpenAI cookbook](https://github.com/openai/openai-cookbook/blob/main/examples/Parse_PDF_docs_for_RAG.ipynb)

**Comment by gSayak** [comment]
Hey I am facing this issue 
```
  File "/root/resume-validator/resume/app.py", line 11, in <module>
    from pdfminer.high_level import extract_text
  File "/root/resume-validator/resume/venv/lib/python3.6/site-packages/pdfminer/__init__.py", line 1, in <module>
    from importlib.metadata import version, PackageNotFoundError
ModuleNotFoundError: No module named 'importlib.metadata'
```
I tried installing the importlib-metadata explicitly but it does not seem to work..
Was working fine when I was using a conda env but the moment I switched to a normal venv it throws this error
