### ISSUE TITLE
MTxx glyph names

### ISSUE THREAD

**Issue by mfluhr** [pdfminer/pdfminer.six#571]
Hi!
I was using the 'python-pdfminer' package on Ubuntu 18.04 to convert french visual approach charts (PDF files) and extract the airfield coordinates and altitudes from each PDFfile. Since 20.04, the package has been updated and the result is now different.

Debugging the issue further, I found out that it was caused by commit f0392f8 (https://github.com/pdfminer/pdfminer.six/commit/f0392f804971e1d1f1de8cf66f70dfb09a373241) which completely reworked the 'name2unicode' implementation to follow the Adobe specification:
Inside the PDF chart document, there are several glyphs with a 'MT' prefix, and those are now considered invalid.

I am definitely not a PDF expert, so I won't be able to judge if the original PDF encoder produced valid data, but according to several posting that I found, it looks like this glyph naming scheme is "MT" followed by the ASCII code of the character.
For further details on this, please see https://manuals.setasign.com/setapdf-extractor-manual/hints/ and  https://stackoverflow.com/questions/35069066/extracting-text-from-pdf-with-itextsharp-is-not-working-for-some-pdf.

**Comment by mfluhr** [comment]
The original documents can be downloaded here: 
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_31_DEC_2020/Atlas-VAC/UK/VACProduitPartieframeset.htm

**Comment by pietermarsman** [comment]
I can't access your PDF anymore. 

We did some additional work ([here](https://github.com/pdfminer/pdfminer.six/commit/782368b9112c93783bcceb94fe0dcafbb2e52b7f) and [here](https://github.com/pdfminer/pdfminer.six/commit/9406040d8e4d627dab3d53ab88b16be43f20bcf1)) on `name2unicode` after the initial change. Let me know if the issue still persists.
