### ISSUE TITLE
Cannot get proper text order from PDF.

### ISSUE THREAD

**Issue by swiftwarrior** [pdfminer/pdfminer.six#577]
When using the following code:
```
resource_manager = PDFResourceManager()
fake_file_handle = io.StringIO()
converter = TextConverter(resource_manager, fake_file_handle, laparams=LAParams(detect_vertical=False, boxes_flow=-1))
page_interpreter = PDFPageInterpreter(resource_manager, converter)

with open('20018011.pdf', 'rb') as fh:

    for page in PDFPage.get_pages(fh,
                                  caching=True,
                                  check_extractable=False):
        page_interpreter.process_page(page)

    text = fake_file_handle.getvalue()

# close open handles
converter.close()
fake_file_handle.close()

print(text)
```
I get the following text order:

> AllianceBernstein Holding l.P.
> units (AB) [ST]
> 
> FIlINg STATuS: New
> DESCRIPTION: Purchased 20,000 shares.
> 
> SP
> 
> Apple Inc. (AAPl) [OP]
> 
> P
> 
> P
> 
> 12/22/2020 12/22/2020
> 
> $500,001 -
> $1,000,000
> 
> 12/22/2020 12/22/2020
> 
> $250,001 -
> $500,000

When I would expect it to look something like:
> SP
> AllianceBernstein Holding l.P.
> units (AB) [ST]
> 
> P
> 12/22/2020 12/22/2020
> 
> $500,001 -
> $1,000,000
> FIlINg STATuS: New
> DESCRIPTION: Purchased 20,000 shares.
> 
> SP
> Apple Inc. (AAPl) [OP]
> 
> 
> P
> 12/22/2020 12/22/2020
> 
> $250,001 -
> $500,000
> FIlINg STATuS: New
> DESCRIPTION: Purchased 100 call options with a strike price of $100 and an expiration date of 1/21/22.

Any help would be greatly appreciate.  Link to PDF: https://disclosures-clerk.house.gov/public_disc/ptr-pdfs/2021/20018011.pdf

**Comment by OJFord** [comment]
Thanks for this, I've encountered a similar issue with a PDF I can't share, so I couldn't really open a very good issue. (I've also only _just_ convinced myself that it wasn't the fault of my own code 😄.)

My case is similar in that it's a table where in some cases one of the cells overflows onto a second line, and that second line turns up in the parsed text at the bottom of the page - after the rest of the table rows.

**Comment by swiftwarrior** [comment]
Yes sir.  I am only partially convinced it isn't my code.  But I figure if it is me the worst that happens is some tells me I am a buffoon and points me in the right direction.  In the meantime, I changed my code to incorporate pytesseract.  It sacrifices a lot on the performance (must save pdfs to disk as images and then analyze them to get the text).  But after messing around with the configurations, I was able to at least get an accurate parsing off all fields I required in a regular enough pattern to use regular expressions.

**Comment by OJFord** [comment]
Ha! I also tried tesseract, via ocrmypdf (esseentially the same just handled the PDF -> image bit for me too).

I gave up on it though, everything in the right order of course, but it would misread numbers, which is worse for my use case than the ordering problem. (I tried 'best' data, and also the legacy/LSTM mixed data, so that I could use the old (or both) engine(s) as only the old one supports user patterns/words.)

I don't really know much about the structure of PDFs, but I do wonder if it's possible we might do better inspecting the layout (with a knowledge of it for the specific PDFs we're handling) and extracting text object by object (or however it works) rather than using a generic 'extract text'. Obviously a lot more work though, I haven't really looked into that yet, just thought it's a possibility.

**Comment by ryanmusic** [comment]
I encountered the similar issue of getting returned text in wrong order. Using Python 3.7 will get incorrect order, but using Python 2.7 will make things fine.

**Comment by raylutz** [comment]
The issue I have been encountering seems related to this bug report. I find that particularly with the last page of the set, things are in the wrong order. pdfminer works great for getting the columns lined up but this is killing me. 

[2020 General - Results - 201 - 202 - 203 - Unit 2.pdf](https://github.com/pdfminer/pdfminer.six/files/6138451/2020.General.-.Results.-.201.-.202.-.203.-.Unit.2.pdf)
[2020 General - Results - 201 - 202 - 203 - Unit 2_from_pdf_miner.pdf.txt](https://github.com/pdfminer/pdfminer.six/files/6138453/2020.General.-.Results.-.201.-.202.-.203.-.Unit.2_from_pdf_miner.pdf.txt)

I have a brute strength conversion that simply goes through the XML and puts it out, but it does not line up columns nearly as well, when that is needed. It is the last little bit of the file that fails:

My brute strength code does this (blank lines suppressed):

 Volusia Forever 
            Yes (For Bonds)                                  26 
            No (Against Bonds)                               20 
            Over Votes                                       0 
            Under Votes                                      2 
            -------------------------- 
            Total Votes                                      48 
          


            WE, THE UNDERSIGNED, DO HEREBY CERTIFY THAT THE ABOVE 
            RESULTS ARE A TRUE AND ACCURATE ACCOUNT OF ALL BALLOTS
            COUNTED AND THAT ALL COUNTERS WERE ZERO (0) WHEN THE 
            POLLS OPENED AND THAT THE ELECTION WAS HELD IN 
            ACCORDANCE WITH THE LAWS OF THE STATE OF FLORIDA. 
snip...

pdfminer does the following:

 
WE, THE UNDERSIGNED, DO HEREBY CERTIFY THAT THE ABOVE 
RESULTS ARE A TRUE AND ACCURATE ACCOUNT OF ALL BALLOTS 
COUNTED AND THAT ALL COUNTERS WERE ZERO (0) WHEN THE 
POLLS OPENED AND THAT THE ELECTION WAS HELD IN 
ACCORDANCE WITH THE LAWS OF THE STATE OF FLORIDA. 
______________________________ 

Volusia Forever 
Yes (For Bonds)                                  26 
No (Against Bonds)                               20 
Over Votes                                       0 
Under Votes                                      2 
-------------------------- 
Total Votes                                      48 

 
snip...

**Comment by ZafarShadman09** [comment]
Similar issues has been encountered by me also. Is there any solution now?

**Comment by pietermarsman** [comment]
@swiftwarrior have you tried tuning the layout parameters?

Read [this documentation](https://pdfminersix.readthedocs.io/en/latest/topic/converting_pdf_to_text.html) to understand how it works and how to tune it.
