### ISSUE TITLE
Extracting hierarchical data with line wraps

### ISSUE THREAD

**Issue by trevorpan** [pdfminer/pdfminer.six#582]
Hi, 

This is an astonishing package. 

Was actually manually selecting text and inserting into a `.sql` file. At about line 1200 I said, "man, this is rough." So I hunted around and found this package. Have worked on it the past 3 days. It'll be super helpful as this pdf is nearly 200 pages long.

You can see here that:
```
00 00 00 Procurement and Contracting
                 Requirements
```
the above wraps and `Requirements` gets separated by quite a few records.

[MasterFormat-2016-1.pdf](https://github.com/pdfminer/pdfminer.six/files/5979351/MasterFormat-2016-1.pdf)

The end goal is to extract hierarchical data and sort it by `text.size`. These will then be printed to a `.sql` file which will be used to insert a db table. These data will then populate html selects. There's a sub issue on this, which is each record needs to have an upper record - or `lvl` above: `INSERT INTO master_formats (lvl_1, lvl_2, lvl_3, lvl_4, lvl_5) VALUES ('NULL', 'NULL', `'**This upper level is necessary to dynamically populate the html selects**',` '00 01 07 
', 'NULL');`

```
from io import StringIO
output_string = StringIO()
from pdfminer.high_level import extract_pages
from pdfminer.layout import LTTextContainer, LTChar, LAParams

LAParams(line_overlap=20,char_margin=2.0,line_margin=5,word_margin=.01,boxes_flow=-1,detect_vertical=False,all_texts=True)

def switch_lvl(firstChar, characters):

    switch = {
        'lvl_1': characters if firstChar == 20 else 'NULL',
        'lvl_2': characters if firstChar == 14 else 'NULL',
        'lvl_3': characters if firstChar == 12 else 'NULL',
        'lvl_4': characters if firstChar == 11 else 'NULL',
        'lvl_5': characters if firstChar == 10 else 'NULL',
    }
    
    record = list(switch.values())
    
    filedata = ('INSERT INTO master_formats (lvl_1, lvl_2, lvl_3, lvl_4, lvl_5)' + ' VALUES (\'' + "', '".join(record) + '\');')

    with open('/path-to-file/insert_master_format.sql') as fileobj:
        text = fileobj.read()
    
    with open('/path-to-file/insert_master_format.sql', 'a') as file:
        if not text.endswith('\n'):
            file.write('\n')
        file.write(filedata) 
        file.close()
             

for page_layout in extract_pages("/path-to-file/MasterFormat-2016-1.pdf"):
    for element in page_layout:
        if isinstance(element, LTTextContainer):
            for text_line in element:              
                
                characters = (text_line.get_text())
                
                for character in text_line:
                    if isinstance(character, LTChar):
              
                        firstChar = round(character.size)
                      
                        switch_lvl(firstChar, characters)
                    
                        break
```
1) If anyone has a tip on getting past the line break issue that would be awesome. As you can see from the printed file not only the large text gets separated, but the smaller lower levels do too.
2) I'm just not certain how to approach checking for the level above a given level and inserting the nearest upper `lvl`'s data.

A big thank you ~

**Comment by pietermarsman** [comment]
I recommend reading the [docs](https://pdfminersix.readthedocs.io/en/latest/topic/converting_pdf_to_text.html) on how the layout algorithm works. Probably you can tune the parameters such that the output is the way you want it to be.
