### ISSUE TITLE
Page number offset in document outline

### ISSUE THREAD

**Issue by ethanabrooks** [pdfminer/pdfminer.six#586]
Hi, I am using PDFMiner to extract the outline from a PDF document. I have noticed that the page numbers that I am extracting appear to be off by a constant. Here is my code:
```python
import re
import sys

from pdfminer.pdfdocument import PDFDocument, PDFNoOutlines
from pdfminer.pdfparser import PDFParser
from pdfminer.pdftypes import PDFObjRef


def get_outline():
    pattern = re.compile(r".*:Bookmark (\d+):.*")  # Will this work for all PDFs?

    with open(sys.argv[1], "rb") as f:
        doc = PDFDocument(PDFParser(f))
        try:
            outlines = doc.get_outlines()
        except PDFNoOutlines:
            return

        title: str
        action: PDFObjRef
        for (_, title, _, action, se) in outlines:
            if action is None:
                continue
            resolved = action.resolve(default=dict())
            try:
                destination_field = resolved["D"]  # "D" for destination
            except KeyError:
                continue
            if isinstance(destination_field, list):
                # This seems to happen when the link goes to a specific place in a page, not a whole page. In
                # all the examples I looked at, this happened in long-form paragraphs (not flowcharts).
                continue
            match = pattern.search(destination_field.decode())
            if match:
                page = int(match.group(1))
                yield page, title
```
I have found that the offset varies from document to document. For this document, the offset is 2: [document.pdf](https://github.com/pdfminer/pdfminer.six/files/6025470/cancer.pdf)

You will notice that while my code identifies "Workup, Primary Tx, and Pathologic Dx (TEST-1)" as page 4, it is actually on page 6 in the PDF document. 

I was hoping you could give me some insight as to why this is. I have looked over section 8.2.2 of the [PDF reference](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference.pdf) but I didn't find an explanation.

Maybe this isn't a bug and I am just misinterpreting the output. Also, if you have any suggestions for making the code more robust to different PDF documents, please let me know. I'll note that we are not interested in outline items that point to the middle of a page.

**Comment by ethanabrooks** [comment]
I did find a section in the PDF reference (section F.3.1) on something called the "Page Offset Hint Table." I am wondering if this is the cause of the problem, and if so, can I access that table using PDFMiner?

**Comment by pietermarsman** [comment]
Your code looks good, as far as I could understand it in a short period of time. 

You might also want to read the related sections of the PDF Reference: 
- 8.2.1 on destinations.
- 3.6.1 about the document catalog (for named references)
- G.5 an example of an outline

I would expect you to use the "Dest" entry, to get a reference to the page the outline is pointing to. Not to use the "A" entry. The "D" entry of the "A" entry is a destination, but the "Dest" entry is also a destination and probably a more direct approach.

**Comment by ethanabrooks** [comment]
Thanks for the response! This project is no longer active for me, but this is good to know for future reference.
