### ISSUE TITLE
Get PDF Page rotation

### ISSUE THREAD

**Issue by adityayardi1** [pdfminer/pdfminer.six#587]
Can we extract the angle of rotation of PDF Page using pdfminer?
I know we can rotate, but didn't get any code as to how we can detect the angle of orientation.

**Comment by tacerdi** [comment]
You can get the rotation by calling the .rotate attribute of PDFPage instance.

```
for page in PDFPage.create_pages(doc):
    interpreter.process_page(page)
    r = page.rotate
```
