### ISSUE TITLE
question: How to both check number of pages and contents of pages?

### ISSUE THREAD

**Issue by jugmac00** [pdfminer/pdfminer.six#591]
Hi, I hope it is ok to ask question here.

I am migrating from `PyPDF2` to `pdfminer.six`.

I am currently rewriting a couple of tests...

my test with `PyPDF2` was... 

```
    pdf = PdfFileReader(rv_as_file)

    assert pdf.getNumPages() == 2

    page1 = pdf.getPage(0)
    assert "some text" in page1.extractText()

    page2 = pdf.getPage(1)
    assert "some other text" in page2.extractText()
```

my first attempt to do the same with `pdfminer.six` is ...

```
    assert len(list(extract_pages(rv_as_file))) == 2

    assert "some text" in extract_text(
        pdf_file=rv_as_file, page_numbers=[0]
    )
    assert "some other text" in extract_text(
        pdf_file=rv_as_file, page_numbers=[1]
    )
```

While this works, now I have to parse the PDF file three times instead of one time.

I have not found a way to get all text from the `LTPage` objects, which `extract_pages` return.

Is there a better way or is this the way to go?

Thanks a lot for your work! Great library!

**Comment by pietermarsman** [comment]
Use the composable api. 

See [this SO post](https://stackoverflow.com/a/61855361/4054971) for an example. 

You can also use a combination of `extract_pages()` and the `TextConverter()`.
