### ISSUE TITLE
Speedup asciihexdecode

### ISSUE THREAD

**Issue by ciupicri** [pdfminer/pdfminer.six#603]
Speedup the `asciihexdecode` implementation. I already have the code.

**Comment by pietermarsman** [comment]
@ciupicri did you had any problems with the speed of this? If so, can you share the PDF.

**Comment by pietermarsman** [comment]
It is only called 3 times during the entire test suite so I doubt that it has a large impact on the overall performance. If the impact is low, readability and changeability should be preferred over performance.

**Comment by ciupicri** [comment]
No problems, I've only noticed that code and thought that it could be improved a bit.
