### ISSUE TITLE
Y coordinates wrong for certain PDFs leading to highlighting wrong areas in the PDF

### ISSUE THREAD

**Issue by sreeni5493** [pdfminer/pdfminer.six#619]
I am using pdfplumber which is built on top of pdfminer.six

But the issue is the coordinates coming from pdfminer.six. 

Here is the pdf
[v2.pdf](https://github.com/pdfminer/pdfminer.six/files/6450348/v2.pdf)

The characters when highlighted appear like this. There is a huge offset in y direction.

![chars](https://user-images.githubusercontent.com/15212113/117624010-11636400-b192-11eb-822f-96336291331e.png)

**Comment by jabzer-research** [comment]
With the method get_bbox() from the Document in the [konfuzio sdk ](https://github.com/konfuzio-ai/document-ai-python-sdk) you can easily access the correct information of each character in your document.
It includes the character itself and the bounding box.
```
# pip install konfuzio_sdk
# in working directory
# konfuzio_sdk init
from konfuzio_sdk.data import Project
my_project = Project()
document = my_project.documents[0]
character_info = document.get_bbox()
```
The output is something like:
`{'character_id': {'bottom': 243.0, 'line_number': 2, 'page_number': 1, 'text': 'I', 'top': 228.0, 'x0': 568.0, 'x1': 573.4285714285714, ... }`

For more info check our [website](https://konfuzio.com/en/)

**Comment by pietermarsman** [comment]
Can you share the code that you are using to create this image?

**Comment by johandebeurs** [comment]
Also seeing this issue when using pdfplumber https://github.com/jsvine/pdfplumber/issues/538 (that apparently depends on this lib for extraction). y coords are way off, x coords are correct. Extracting from bank statements so unfortunately not shareable directly.
A couple of anecdotal observations
- When selecting text in the PDF in Preview/MacOS, line heights are much larger than expected.
- When extracting characters, many have negative y-coordinates

**Comment by pettzilla1** [comment]
From my experience with these types of docs they can sometimes be put together weirdly which can cause issues for extraction, there could also be issues if there are relative areas of the document then some parts would be scaled to screen size so a fixed pixel size would’nt work

**Comment by johandebeurs** [comment]
Ack. My solution here was to convert source PDFs to images, rerun OCR using appropriate tessaract settings and then process with pdfminer. This resolved the two issues identified in my previous comment.
