### ISSUE TITLE
PyCrypto and windows

### ISSUE THREAD

**Issue by mplessard** [pdfminer/pdfminer.six#62]
I've tried to install pdfminer with pip on windows, but I was getting an error over wheels bundle on pyCrypto. The problem was solved when changing a line in the setup file, `requires = ['six', 'pycrypto']` to `requires = ['six', 'pycryptodome']`. 

I think it would be nice to detect if it's on windows to set `requires` correctly.

**Comment by mpasternak** [comment]
Hi, it's in my branch already https://github.com/pdfminer/pdfminer.six/pull/63

**Comment by goulu** [comment]
Merged. Thank you !
