### ISSUE TITLE
PDFNoOutlines error

### ISSUE THREAD

**Issue by yassinekdi** [pdfminer/pdfminer.six#622]
**Bug report**
Hello,
Thank you for this useful package. I want to get the outlines from PDFs but it doesn't work in some cases (such as those :[Hu_2012.pdf](https://github.com/pdfminer/pdfminer.six/files/6510450/Hu_2012.pdf), [Yen2002.pdf](https://github.com/pdfminer/pdfminer.six/files/6510451/Yen2002.pdf)), and I get the PDFNoOutlines error (line 726 in pdfdocument.py). I've tried to go through the code but it was a bit hard to solve it.
Here is my code : 

```
doc_ = BytesIO(open(path, "rb").read())
parser_pdf = PDFParser(doc_)
doc_pdf = PDFDocument(parser_pdf)
outlines =list(doc_pdf.get_outlines())

```
This same code worked fine with other PDFs. Any idea how I can solve this problem ?

Thanks!

**Comment by ggdupont** [comment]
Not all pdf have outlines (it is absent from the file). This is the case of the two you linked.

**Comment by pietermarsman** [comment]
See 3.6.1 (Document Catalog) of the PDF Reference: the outlines entry is optional. Your PDF's don't have one.
