### ISSUE TITLE
Extracting Stroke Dasharray in LTCurve

### ISSUE THREAD

**Issue by TimMcCauley** [pdfminer/pdfminer.six#630]
Thank you for maintaining this wonderful library. Currently I am mining pdf files consisting of curves which either have a stroke dash-array or with just a normal stroke (see image attached). From what I can discover in the [source code](https://github.com/pdfminer/pdfminer.six/blob/22f90521b823ac5a22785d1439a64c7bdf2c2c6d/pdfminer/layout.py#L192) this information is not parsed in the mining process. 
<img width="789" alt="Screenshot 2021-06-12 at 21 49 25" src="https://user-images.githubusercontent.com/10322094/121788063-96470080-cbca-11eb-8086-cf35022b6c91.png">. My question is if I am missing something very obvious that could help me determine this differentiation? If this is a feature that currently does not exist, would you be interested in a PR?

**Comment by JulianFeinauer** [comment]
I also need this feature : )

**Comment by pietermarsman** [comment]
For this we need to extract the "Line Dash Pattern" from the graphics state as mentioned in Section 4.3.2 "Details of Graphics State Parameters" in the pdf reference.
