### ISSUE TITLE
Write or manipulate pdfs

### ISSUE THREAD

**Issue by padmalcom** [pdfminer/pdfminer.six#633]
**Feature request**
Hi first of all thanks for the great library! I'm currently writing a tool to translate pdfs. My idea was to identify text blocks (which works pretty well in pdfminer), modify these blocks (modify text and font or remove and add) and write the pdf. Are there any plans to implement writing pdfs documents?

**Comment by pietermarsman** [comment]
Nope. 

Pdfminer.six is a library for extracting texts in human readable order from a pdf. It does not contain any functionality for modifying a PDF.
