### ISSUE TITLE
No content detected on some pdf files

### ISSUE THREAD

**Issue by sthenault** [pdfminer/pdfminer.six#636]
For instance, run pdf2txt.py on
[zen_of_python_corrupted.pdf](https://github.com/pdfminer/pdfminer.six/files/6749286/zen_of_python_corrupted.pdf)
You will see no content while readers like evince does open them nicely.

**Comment by pietermarsman** [comment]
I can reproduce this

````shell
$ python tools/pdf2txt.py ~/Downloads/zen_of_python_corrupted.pdf 

```
