### ISSUE TITLE
Page creation fails because of wrong case

### ISSUE THREAD

**Issue by sergei-maertens** [pdfminer/pdfminer.six#64]
I've got a PDF (can't share it because of sensitive information) that fails during page creation via `pdfminer.pdfpage.PDFPage.create_pages` because it returns an empty iterable, relevant code with my patch:

```python
    @classmethod
    def create_pages(klass, document, debug=0):
        def search(obj, parent):
            if isinstance(obj, int):
                objid = obj
                tree = dict_value(document.getobj(objid)).copy()
            else:
                objid = obj.objid
                tree = dict_value(obj).copy()
            for (k, v) in parent.iteritems():
                if k in klass.INHERITABLE_ATTRS and k not in tree:
                    tree[k] = v
            # FIXME: wrong case?
            tree_type = tree.get('Type', tree.get('type'))
            if tree_type is LITERAL_PAGES and 'Kids' in tree:
                if 1 <= debug:
                    print >>sys.stderr, 'Pages: Kids=%r' % tree['Kids']
                for c in list_value(tree['Kids']):
                    for x in search(c, tree):
                        yield x
            elif tree_type is LITERAL_PAGE:
                if 1 <= debug:
                    print >>sys.stderr, 'Page: %r' % tree
                yield (objid, tree)
        pages = False
        if 'Pages' in document.catalog:
            for (objid, tree) in search(document.catalog['Pages'], document.catalog):
                yield klass(document, objid, tree)
                pages = True
        if not pages:
            # fallback when /Pages is missing.
            for xref in document.xrefs:
                for objid in xref.get_objids():
                    try:
                        obj = document.getobj(objid)
                        if isinstance(obj, dict) and obj.get('Type') is LITERAL_PAGE:
                            yield klass(document, objid, obj)
                    except PDFObjectNotFound:
                        pass
        return
```

The relevant bit is `tree_type = tree.get('Type', tree.get('type'))` - the actual PDF stream has a lowercase `/type` instead of the expected `/Type`, causing the generator to never `yield`, which in turn causes `StopIteration` in pdfquery.

According to the spec (1.7, page 57-58), this is valid and `/Type` is a different name object than `/type`. However, in this case, the meaning is the same, and probably the PDF generator is the 'offending' root cause here.

1. Would a patch like this where capitalized object is checked first with fallback to lowercase be acceptable?
2. If not, what would be the best way to handle this?

**Comment by sergei-maertens** [comment]
@goulu have you had any chance to take a look at this?

**Comment by goulu** [comment]
hi @sergei-maertens . yes but had no time yet to investigate ... I prefer PRs ...

**Comment by sergei-maertens** [comment]
@goulu I completely understand, I didn't make a PR (yet) since I'm not sure the proposed approach is acceptable, essentially the last two questions in my original description are key to how to proceed :)
