### ISSUE TITLE
Limit number of objects per page.

### ISSUE THREAD

**Issue by rmbittmann** [pdfminer/pdfminer.six#646]
**Feature request**

Thanks for your suggestion on improving pdfminer.six. To helps us discuss and
implement this request, please make sure to include the following information:

- A description of the feature you would like to have
_I would like to have an option to limit the number of objects processed in a page._

- If relevant, the context that you are in. What are you trying to achieve?
_Some documents may have very complex pages with a large number of objects (millions). The complex pages are not always the focus of the pdf document parsed but these pages consume a lot of resources. This feature aims at limiting the maximum resources a single page in a pdf document may consume._

- If possible, an example of what you want to achieve. Include the PDF that
  you are working on. Include the output that you would like to have. 
_The attached file takes about 12x longer to process than if limiting the number of objects per page to 1000._
[ef1710en.pdf](https://github.com/pdfminer/pdfminer.six/files/6842469/ef1710en.pdf)

**Comment by pietermarsman** [comment]
Thanks for suggesting.

But this will not be supported in the high-level api. If you need this feature, implementing your own interpreter is the way to go.
