### ISSUE TITLE
jbig2 extractor does not seem to be working correctly

### ISSUE THREAD

**Issue by fgregg** [pdfminer/pdfminer.six#652]
The jb2 file that is extracted from a pdf with jbig2 encoded images does not seem correct. This includes the sample file

```bash
> pd2txt.py --output-dir=. samples/contrib/pdf-with-jbig2.pdf
> ls *.jb2
XIPLAYER0.jb2
> jbig2dec -t pbm XIPLAYER0.jb2
jbig2dec WARNING OOB obtained when decoding symbol instance T coordinate (segment 0x03)
jbig2dec WARNING failed to decode text region image data (segment 0x03)
jbig2dec WARNING failed to decode; treating as end of file (segment 0x03)
> pnmtopng XIPLAYER0.pbm > XIPLAYER0.png
```
This produces a blank PNG file: [XIPLAYER0.png](https://user-images.githubusercontent.com/536941/127749247-e478597f-d14e-4ae1-a4c2-75f7ec3c90d8.png)

The original pdf file is okay, and we can extract the image using pdfimages.

```bash
> pdfimages -jbig2 samples/contrib/pdf-with-jbig2.pdf XIPLAYER0
> ls XIPLAYER0-000.*
XIPLAYER0-000.jb2e  XIPLAYER0-000.jb2g
> jbig2dec XIPLAYER0-000.jb2g XIPLAYER0-000.jb2e -t pnm
> pnmtopng XIPLAYER0-000.pbm > XIPLAYER0-000.png
```
![XIPLAYER0-000](https://user-images.githubusercontent.com/536941/127749553-4f60bd7b-cb37-4600-aa11-534a6f5d2d02.png)

This problem is not due to a mistranslation of @side2k's original PR. 

I checked out [their original Python 2.7 branch](https://github.com/side2k/pdfminer/tree/jbig2), and the jb2 file that they produce is exactly the same as what's on the HEAD of pdfminer.six's `develop` branch.

**Comment by fgregg** [comment]
unfortunately, pdfimages (as part of poppler) is [licensed under GPL 3](https://gitlab.freedesktop.org/poppler/poppler/-/blob/master/COPYING3), so we cannot read and translate their code and maintain this projects's MIT license

**Comment by fgregg** [comment]
comparing the output of pdfimages, it looks like `XIPLAYER0-000.jb2e` and `XIPLAYER0-000.jb2g` are direct extractions from the pdf. This would be simple to reproduce. 

For jbig2 images, we would produce two files, a jb2g and jb2e. Then a user could use jbig2dec to convert these files, together, into pbm or png file.

Obviously, it would be better if pdfminer could output a single jb2 file, but I don't know how to construct a valid file. 

It seems better to output two files that *can* be used, versus one file that is invalid, as is the status quo.

Thoughts @pietermarsman?

**Comment by fgregg** [comment]
i ended up figuring out how to put everything together in a single jb2 file, and have submitted a pull request. #653

**Comment by pietermarsman** [comment]
@fgregg Thanks for figuring this out! Will review / merge the PR.
