### ISSUE TITLE
Add DjVuXML converter

### ISSUE THREAD

**Issue by hason** [pdfminer/pdfminer.six#666]
DjVuXML describs the metadata, hyperlinks, and hidden text associated with the DjVu/PDF file.  DjVuXML file is used for the text layer in  https://github.com/internetarchive/bookreader

**Comment by pietermarsman** [comment]
Hi @hason, 

Could you describe in more detail what this entails? How would the output look? What should be included or excluded? What is the specification to output should adhere to.

**Comment by pietermarsman** [comment]
Closing because lack of response.
