### ISSUE TITLE
Re-add 'python-sortedcontainers' to dependency in PKGBUILD or other fix (for ocrmypdf)

### ISSUE THREAD

**Issue by moritz1000** [pdfminer/pdfminer.six#669]
Hello,

I tried to install [ocrmypdf ](https://aur.archlinux.org/packages/ocrmypdf/) from the Arch User Repository.
I got [some erros](https://aur.archlinux.org/packages/ocrmypdf/#comment-823497) after the installation.

The point is that [one comment ](https://aur.archlinux.org/packages/ocrmypdf/#comment-820963) proposed the following thing as a solution:

___
**This looks like a problem with the pdfminer package**.

The latest version of the Arch package removed the dependency on `python-sortedcontainers`. Upstream does not actually need sortedcontainers and has [removed the dependency](https://github.com/pdfminer/pdfminer.six/pull/525) #525 , but that change has not been tagged in a release yet. **So the Arch `python-pdfminer` needs to either incorporate that unreleased patch, or re-add the `python-sortedcontainers` dependency in their PKGBUILD.**

In the meantime, downgrading to `python-pdfminer` version 20201018-2 will fix the problem.

___

I am just a passing this information along and I don't have the technical expertise to comment on this issue. I am just a simple user who wants to use `ocrmyopdf` without having to downgrade `python-pdfminer`.

**Comment by pietermarsman** [comment]
The removal of sortedcontainers is now part of the release on pypi. I guess that fixes the issue.
