### ISSUE TITLE
(cid:57) .(cid:53)(cid:9)(cid:23)(cid:108)(cid:10)贰拾陆元整 (cid:9)(cid:105)(cid:108)

### ISSUE THREAD

**Issue by yts2020** [pdfminer/pdfminer.six#670]
When I run pdf2txt, I found a few chiese success. but more message is  cid:xxxx
![Uploading Selection_102.png…]()

**Comment by yts2020** [comment]
![Selection_102](https://user-images.githubusercontent.com/74759700/134890415-44ded585-0437-4a72-9d70-150282383b8d.png)

**Comment by serdarakyol** [comment]
I just have the same problem with Turkish and English. The code as below;
```
from pdfminer.high_level import extract_text
  
pdf='/home/ak/Desktop/ml-translation2/data/PGS_EYLUL_2021_ipad.pdf'
text = extract_text(pdf, page_numbers=[11])
print(text)
```
The output is like that
![1](https://user-images.githubusercontent.com/36725883/144896113-6be49b2a-5abb-4830-8fce-20aaf660fc56.png)

**Comment by serdarakyol** [comment]
I just have the same problem with Turkish and English. The code as below;
```
from pdfminer.high_level import extract_text
  
pdf='PGS_EYLUL_2021_ipad.pdf'
text = extract_text(pdf, page_numbers=[11])
print(text)
```
The output is like that
![1](https://user-images.githubusercontent.com/36725883/144896113-6be49b2a-5abb-4830-8fce-20aaf660fc56.png)

Original PDF in that [LINK](https://cdnp.flypgs.com/files/PGS-MAG/PGS_EYLUL_2021_ipad.pdf)

**Comment by Klefo0** [comment]
Maybe you guy can check this [746](https://github.com/pdfminer/pdfminer.six/issues/746) issue

**Comment by pietermarsman** [comment]
@yts2020 can you share the PDF? The link is broken.

**Comment by pietermarsman** [comment]
Closing because no response
