### ISSUE TITLE
warnings.warn is inappropriate for notifying PDF input issues

### ISSUE THREAD

**Issue by htInEdin** [pdfminer/pdfminer.six#671]
**PDF issues should be reported using `logging.Logger.warning`, not `warnings.warn`**

In several places, PDF input issues are notified by raising `warnings.warn`.  But the [guidance from the Python documentation](https://docs.python.org/3/howto/logging.html) says this about the proper use of `warnings.warn`:
  > `warnings.warn()` in library code if the issue is avoidable and the client application should be modified to eliminate the warning
  > `logging.warning()` if there is nothing the client application can do about the situation, but the event should still be noted

An issues in the PDF is not a problem with pdfminer code, so the issue is _not_ avoidable.

The only two uses of warnings.warn involve the Exceptions `PDFNoValidXRefWarning` and  `PDFTextExtractionNotAllowedWarning`, both of which relate to properties of the input PDF, and so per the above should be signalled using `logging.Logger.warning`.

For example, running pdf2txt.py on the attached file will produce
```
.../pdfminer/pdfpage.py:140: PDFTextExtractionNotAllowedWarning: The PDF <_io.BufferedReader name='20190819160107-20190819182107-00456_27700.pdf'> contains a metadata field indicating that it should not allow text extraction. Ignoring this field and proceeding.
  warnings.warn(warning_msg, PDFTextExtractionNotAllowedWarning)
```

[20190819160107-20190819182107-00456_27700.pdf](https://github.com/pdfminer/pdfminer.six/files/7260222/20190819160107-20190819182107-00456_27700.pdf)

**Comment by pietermarsman** [comment]
Agreed!
