### ISSUE TITLE
Save control point information on LTCurve

### ISSUE THREAD

**Issue by axelskyttner** [pdfminer/pdfminer.six#672]
**Feature request**
Save control point information on bezier curves during parsing (as suggested by @jsvine in https://github.com/pdfminer/pdfminer.six/pull/530#issuecomment-774742279).

**Description**
I need to render bezier curves in pdfs with different levels of resolutions and what jsvine suggests in PR-comment would solve my problem.
> (Relatedly: Are the maintainers open to adding a .path attribute (which would contain the full path-command information that .paint_path is using) to LTCurve objects? That would allow users to reproduce the Beziér curves themselves — currently not possible because the command types themselves (m/l/h/c/v/y) are not accessible through .pts. If that sounds like a good idea, I can submit a separate PR once this one is resolved.)

Since I could not find any discussion regarding jsvine's suggestion I made this issue. Maybe there already exists an issue for this?

## Example of use case
Example, [this file](https://github.com/pdfminer/pdfminer.six/files/7265454/circle.pdf) contains a simple circle. Using a function like _cubic_bezier_ below, I would like to be able to render points on the circle. Moreover, I need to be able to generate the points with different levels of resolution (e.g.res=5, res=10 and res=100) so the original control points needs to be saved on the curve object somehow.
```py
def cubic_bezier(p0, p1, p2, p3, res=10):
    pts = []
    for i in range(0, res):
        t = i / res
        pt = pow(1-t, 3) * p0 + 3 * pow((1-t), 2)*t*p1 + 3 * (1-t) * pow(t,2)* p2 + pow(t, 3) * p3 
        pts.append(pt)
    return pts
```
![image](https://user-images.githubusercontent.com/12814340/135589700-33e62acf-9d4b-480c-967c-032e64e9637d.png)
_Image of rendered points from bezier curve in pdf file_

**Comment by JulianFeinauer** [comment]
I need this feature too. Is someone working on it? Otherwise i can also offer to work on a PR?

**Comment by pietermarsman** [comment]
@JulianFeinauer PR is more than welcome here!
