### ISSUE TITLE
reading order is not quite right formultiple columns in one page

### ISSUE THREAD

**Issue by wanghaisheng** [pdfminer/pdfminer.six#698]
[example pdf](https://py-pdf-parser.readthedocs.io/en/latest/_downloads/f3865276d3ed7f8ffcdbb9930dd9ed01/columns.pdf)

```
['Column 1 Title', 'Column 2 Title', 'Here is some column 1 text.', 'Here is some column 2 text.', 'Col 1 left', 'Col 1 right', 'Col 2 left', 'Col 2 right']
```
what i want is 
```
['Column 1 Title', 'Here is some column 1 text.', 'Col 1 left', 'Col 1 right', 'Column 2 Title', 'Here is some column 2 text.', 'Col 2 left', 'Col 2 right']
```

**Comment by pietermarsman** [comment]
You can fix this by changing the parameters of the layout algorithm. 

Read [this section of the documentation](https://pdfminersix.readthedocs.io/en/latest/topic/converting_pdf_to_text.html) to understand how the algorithm works, and how to tune it.
