### ISSUE TITLE
encodingdb.name2unicode(name: str) -> str  can't handle type1 font diff like: 2, /'MT110', /'MT50',...

### ISSUE THREAD

**Issue by dzhang228** [pdfminer/pdfminer.six#699]
the current version of encodingdb.name2unicode(name: str) -> str  can't handle type1 font diff like: 2, /'MT110', /'MT50',...
It'll decode the diff as cid3, cid 4., ...

Compared with a previous version that can handle the diff properly, an option is missing:

the early version has option:

# before the function:
STRIP_NAME = re.compile(r'[0-9]+')                # option copied from pdfminer-20191125,   

# inside the function:
        else:                             # option copied from pdfminer-20191125,   
            m = STRIP_NAME.search(name)
            if not m:
                raise KeyError(name)
            return chr(int(m.group(0))) 

After adding the above code to the function, the diff are properly decoded.

**Comment by pietermarsman** [comment]
@dzhang228 Thanks for raising this issue. 

I'm trying to understand what you are saying, but I can't figure it out. 

Do you have an example PDF that shows this issue? 

And do you happen to know where the type1 font diff you are referring to is documented?
