### ISSUE TITLE
color space

### ISSUE THREAD

**Issue by khivraj-jangid** [pdfminer/pdfminer.six#709]
can any one share details regarding color space
1-> ['/ICCBased', IndirectObject(12, 0)]
2->['/Indexed', IndirectObject(12, 0), 234, IndirectObject(14, 0)]

I required details like-
i->whats the meaning of ICCBased/Indexed
ii->whats the meaning of IndirectObject
iii->why there only 2 values are given
iv->How to convert it in html color format(like rgb,hex)

some samples of colorspace=
['/ICCBased', IndirectObject(12, 0)]
['/ICCBased', IndirectObject(13, 0)]
['/Indexed', IndirectObject(12, 0), 234, IndirectObject(14, 0)]
['/Indexed', IndirectObject(11, 0), 0, IndirectObject(22, 0)]
['/Indexed', IndirectObject(11, 0), 253, IndirectObject(30, 0)]

**Comment by pietermarsman** [comment]
Checkout the [PDF Reference](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdf_reference_archive/pdf_reference_1-7.pdf). 

Section 4.5.2 is about color families, also about `ICCBased`. 

Section 3.2.9 is about indirect objects.

**Comment by khivraj-jangid** [comment]
@pietermarsman Thanks for document. It is helpfull to me for knowledge regarding pdf.

But I did not get solution on my requirement.
I required conversion process for convert colorspace- ['/ICCBased', IndirectObject(13, 0)]
['/Indexed', IndirectObject(12, 0), 234, IndirectObject(14, 0)] to html rgb/cmyk.
If any formula or function is available for that please provide me.

Thanks for help.

**Comment by pietermarsman** [comment]
Can you share the pdf and a minimal reproducible example that you use to get this result?

**Comment by khivraj-jangid** [comment]
[test.pdf](https://github.com/pdfminer/pdfminer.six/files/8030431/test.pdf)

page['/Resources']['/XObject']['/{objectName}']['/ColorSpace']

page is pdf page object, objectName is for type of object Imo or text

check for /ColorSpace type of /ICCBased or /Indexed
eg.:
['/ICCBased', IndirectObject(12, 0)]
['/Indexed', IndirectObject(12, 0), 234, IndirectObject(14, 0)]

(I want to know the flow or formulas or functions to convert it into RGB or CMYK type)

Thanks in Advanced

**Comment by pietermarsman** [comment]
Can you share the code for a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example)?
