### ISSUE TITLE
[Question] How to convert color to color name?

### ISSUE THREAD

**Issue by aurora1625** [pdfminer/pdfminer.six#710]
Hi, I am trying to use the package to recognize character color, so that I can combine it with character font name and font size to "guess" whether it is a header or a regular paragraph in PDF file. 

I have extracted the number `[0.322 0.335 0.356]` of `non_stroking_color` and inside the PDF file it is **green** color. 

I have read almost all the issues about color in the Issues, but can't figure out how to convert the color triplet to color name?

Thank you!

**Comment by pietermarsman** [comment]
Not a pdfminer.six question so closing this question.

I think you'll find [this SO post](https://stackoverflow.com/questions/9694165/convert-rgb-color-to-english-color-name-like-green-with-python) interesting. It is about converting rgb values to a color name.

**Comment by aurora1625** [comment]
Hi @pietermarsman Thank you for replying. I knew this is not a pdfminer.six issue, but could you share what color space does these three number belong to? I have looked at more results, in other pages, these exact three numbers are actually in black color. Or these triplets just indicates that there are some colors, and they are different. 

I am fine with just identifying those colors are different using the triplets, by the way. Just being curious. 

Thanks again for the work, great job~

**Comment by pietermarsman** [comment]
I guess it is some greyish color and that the scale is from zero to one. Since all of the values are approx 0.33, that would make it light gray.
