### ISSUE TITLE
Installation failure on Windows WSL debian

### ISSUE THREAD

**Issue by volezheng** [pdfminer/pdfminer.six#712]
**Bug report**

Thanks for finding the bug! To help us fix it, please make sure that you 
include the following information:

- A description of the bug
- Steps to reproduce the bug. Try to minimize the number of steps needed. 
  Include the command and/or script that you use. Also include the PDF that 
  you use.
$ pip install pdfminer.six
- If relevant, include the output and/or error stacktrace. 

Collecting pdfminer.six
  Using cached https://files.pythonhosted.org/packages/93/f3/4fec7dabe8802ebec46141345bf714cd1fc7d93cb74ddde917e4b6d97d88/pdfminer.six-20201018-py3-none-any.whl
Collecting chardet; python_version > "3.0" (from pdfminer.six)
  Using cached https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl
Collecting cryptography (from pdfminer.six)
  Using cached https://files.pythonhosted.org/packages/08/31/c43f1e45b4a5ebac13ff038a3f167ba3c7432f6dc8683ea504f5af9265eb/cryptography-3.2.1-cp35-abi3-manylinux1_x86_64.whl
Collecting sortedcontainers (from pdfminer.six)
  Using cached https://files.pythonhosted.org/packages/32/46/9cb0e58b2deb7f82b84065f37f3bffeb12413f947f9388e4cac22c4621ce/sortedcontainers-2.4.0-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography->pdfminer.six)
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography->pdfminer.six)
  Using cached https://files.pythonhosted.org/packages/00/9e/92de7e1217ccc3d5f352ba21e52398372525765b2e0c4530e6eb2ba9282a/cffi-1.15.0.tar.gz
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography->pdfminer.six)
  Using cached https://files.pythonhosted.org/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl
Building wheels for collected packages: cffi
  Running setup.py bdist_wheel for cffi: started
  Running setup.py bdist_wheel for cffi: finished with status 'error'
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xmzw8qx3/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpd5mu91tlpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/cffi
  copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/verifier.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/lock.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/error.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/api.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/model.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/cparser.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/recompiler.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/__init__.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/commontypes.py -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/_embedding.h -> build/lib.linux-x86_64-3.5/cffi
  copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.5/cffi
  running build_ext
  building '_cffi_backend' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/c
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-5Cvh2K/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.5m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.5/c/_cffi_backend.o
  c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
   #include <ffi.h>
                   ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Running setup.py clean for cffi
Failed to build cffi
Installing collected packages: chardet, six, pycparser, cffi, cryptography, sortedcontainers, pdfminer.six
  Running setup.py install for cffi: started
    Running setup.py install for cffi: finished with status 'error'
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xmzw8qx3/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1j2ios6s-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/verifier.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/lock.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/error.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/api.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/model.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/cparser.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/recompiler.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/__init__.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/commontypes.py -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/_embedding.h -> build/lib.linux-x86_64-3.5/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.5/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/c
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-5Cvh2K/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.5m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.5/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------

**Comment by pietermarsman** [comment]
[Install libffi](https://stackoverflow.com/questions/31508612/pip-install-unable-to-find-ffi-h-even-though-it-recognizes-libffi).

[It is a requirement for cryptography](https://cryptography.io/en/latest/installation/#debian-ubuntu), one of pdfminer.six dependencies.
