### ISSUE TITLE
extract_text has much fewer options than extract_text_to_fp

### ISSUE THREAD

**Issue by kno10** [pdfminer/pdfminer.six#715]
extract_text_to_fp has options such as "rotate" to help with rotated pages.

As workaround I used `extract_text_to_fp` along with `io.StringIO`, and it worked as desired.

I'd suggest to add these missing options to the easier wrapper, too.

**Comment by pietermarsman** [comment]
All parameters that are missing from `extract_text()` are specific to `extract_text_to_fp()`:

- `outfp` is the file that the output is written to, `extract_text()` just returns the text.
- `ouput_type` for `extract_text()` is always text.
- `scale` only applies to html, not to text.
- `rotation` only applies to html, not to text. 
- `layoutmode` only applies to html.
- `outputdir` is for extracting image, not text.
- `strip_control` is for xml, not text.
- `debug` can be handled by any piece of code, it just changes the logging level.

**Comment by kno10** [comment]
I am extracting text only, not html.
Yet, `rotation` was exactly what I needed.
Maybe check again, please.

**Comment by pietermarsman** [comment]
What happens if you use `extract_text()` with `LAParams.detect_vertical = True` ?

**Comment by kno10** [comment]
IIRC I get each letter on a separate row, so that did not work.
