### ISSUE TITLE
combining LTTextLines with similar y0 before sorting

### ISSUE THREAD

**Issue by kielni** [pdfminer/pdfminer.six#718]
When I call `.get_text()` on an `LTTextBox`, sometimes the text is output in the wrong order compared to what it looks like visually. I can't share the PDF, but hopefully I can explain the issue.

I put a print in [layout.py when it creates an LTTextLine](https://github.com/pdfminer/pdfminer.six/blob/develop/pdfminer/layout.py#L788). The text comes out the PDF like this:

```
line	y0=483.912 y1=491.712 x0=213.800 x1=345.887	2,721,610.000 kWh x 0.01100
line	y0=474.762 y1=482.562 x0=213.800 x1=345.887	5,663,000.000 kWh x 0.00412
line	y0=465.912 y1=473.712 x0=209.500 x1=345.887	28,518,000.000 kWh x 0.00092
line	y0=457.012 y1=464.812 x0=209.500 x1=345.887	10,231,000.000 kWh x 0.00050
line	y0=439.162 y1=446.962 x0=260.600 x1=345.587	1 MTR x 106.70000
line	y0=483.015 y1=491.712 x0=18.000 x1=147.854	NV Greenenergy Rider-option 2 Ftch 
line	y0=474.065 y1=482.762 x0=18.000 x1=146.555	NV Greenenergy Rider-option 2 Bldr 
line	y0=465.115 y1=473.812 x0=18.000 x1=141.816	NV Greenenergy Rider-option 2 T2 
line	y0=456.165 y1=464.862 x0=18.000 x1=148.751	NV Greenenergy Rider-option 2 Turq 
line	y0=412.262 y1=420.062 x0=18.000 x1=98.937	Local Government Fee
line	y0=403.362 y1=411.162 x0=18.000 x1=334.734	Local Government Fee 5%
line	y0=394.512 y1=402.312 x0=18.000 x1=334.734	Local Government Fee 5%
line	y0=385.362 y1=393.162 x0=18.000 x1=334.734	Local Government Fee 5%
line	y0=376.512 y1=384.312 x0=18.000 x1=334.734	Local Government Fee 5%
line	y0=367.612 y1=375.412 x0=18.000 x1=334.734	Local Government Fee 5%
line	y0=358.762 y1=366.562 x0=18.000 x1=343.584	Power Factor Adjustment 100%
line	y0=500.765 y1=509.462 x0=372.950 x1=405.972	3,356.01 
line	y0=491.830 y1=500.527 x0=372.950 x1=405.972	5,235.38 
line	y0=482.895 y1=491.592 x0=368.600 x1=405.973	29,937.71 
```

The example I will describe in more detail is a line that should look like this:

```
NV Greenenergy Rider-option 2 Ftch 2,721,610.000 kWh x 0.01100 29,937.71
```
but calling `get_text()` on the `LTTextBox` produces 

```
2,721,610.000 kWh x 0.01100
NV Greenenergy Rider-option 2 Ftch 
29,937.71 
```

This is because the content is in three different places in the doc, and pdfminer creates three separate LTTextLine objects:

&lt;LTTextLineHorizontal  18.000,  **483.015**,  147.854,  491.712 'NV Greenenergy Rider-option 2 Ftch '&gt;
&lt;LTTextLineHorizontal 213.800,  **483.912**,  345.887,  491.712 '2,721,610.000 kWh x 0.01100'&gt;
&lt;LTTextLineHorizontal 368.600,  **482.895**,  405.973,  491.592 '29,937.71 '&gt;

For output, it [sorts by -y0](https://github.com/pdfminer/pdfminer.six/blob/develop/pdfminer/layout.py#L957) (bolded above). The bounding boxes of these are slightly different, so this produces an incorrect order.

But the difference in y0 for these three object is insignificant (0.12), both visually and compared to the next visual line / group: 

&lt;LTTextLineHorizontal  18.000,  **474.065**,  146.555,  482.762 'NV Greenenergy Rider-option 2 Bldr '&gt;
&lt;LTTextLineHorizontal 213.800,  **474.762**,  345.887,  482.562 '5,663,000.000 kWh x 0.00412'&gt;
&lt;LTTextLineHorizontal 368.600,  **473.960**,  405.973,  482.657 '23,376.86 '&gt;

The difference in y0 between these two groups is > 8. Also, the tiny amount of difference in y0 means these should be on the same line, not [separated by newlines](https://github.com/pdfminer/pdfminer.six/blob/develop/pdfminer/layout.py#L499).

I am working around this in by code by doing this instead of calling `get_text()` on the `LTTextBox`:

  - group LTTextLine objects that are within 5 `y0` into one line (hardcoded for my application; should this be `line_margin`?) ; remove newlines
  - sort LTTextLine objects in each line by `x0`, for correct left to right order

Should pdfminer be doing this to more accurately represent the text? If not, is there a place in the documentation where I can add this?

**Comment by pietermarsman** [comment]
You should be able to solve this issue by tuning the layout parameters.

My suggestion is to decrease the (minimum) `line_overlap` parameter, and to increase the `char_margin` parameter.

**Comment by JohnBurant** [comment]
Sorry for going back on a closed issue, but I don't think this is quite correct and I have an alternative suggestion that might result in an added feature (for which I could submit a PR).

As I read the code, tuning the layout parameters like this should work if the not-exactly-vertically-aligned LTText objects are sequential in the PDF file but not if the flow of the characters in the PDF file doesn't match left-to-right across the full page. Once group_objects hits a new LTText object that doesn't match the alignment criteria for the LTTextLine object it is building, it commences building a new LTTextLine object and can never join the LTText objects we'd like to have joined.

Obviously I'm not working with @kielni's file, but this file is an example that I've run into that may be like @kielni's issue: 

https://assets.publishing.service.gov.uk/media/5a97c960ed915d57d1335b35/2405244-17_23-01-18.pdf. 

The "line" that visually reads  "Respondent:         Zoe Mann" is split into two LTTextLineHorizontal objects and flow into two separate LTTextBox objects after running with all sorts of parameters choices.

There are multiple ways to solve this. One way is to add an option that eliminates the left/right/center alignment checks in find_neighbors. My code that does this is:

from math import inf
def find_neighbors(
      self, plane: Plane[LTComponentT], ratio: float, check_alignment: bool=True) -> List[LTTextLine]:
      """
      Finds neighboring LTTextLineHorizontals in the plane.

      Returns a list of other LTTestLineHorizontals in the plane which are
      close to self. "Close" can be controlled by ratio. The returned objects
      will be the same height as self, and also either left-, right-, or
      centrally-aligned.
      """
      d = ratio * self.height
      hpad = inf
      if check_alignment: hpad = 0
      objs = plane.find((self.x0 - hpad, self.y0 - d, self.x1 + hpad, self.y1 + d))
      return [
          obj
          for obj in objs
          if (
              isinstance(obj, LTTextLineHorizontal)
              and self._is_same_height_as(obj, tolerance=d)
              and (not check_alignment
                  or self._is_left_aligned_with(obj, tolerance=d)
                  or self._is_right_aligned_with(obj, tolerance=d)
                  or self._is_centrally_aligned_with(obj, tolerance=d)
              )
          )
      ] 

In addition, this has the benefit of grouping other sets of lines that don't match the alignment criteria, e.g. where we have a numbered list with text indentation aligning on words not on the number but a short stub in the last line, see item number 4 in this file: https://assets.publishing.service.gov.uk/media/615ec62fe90e07197b571b7d/Mr_D_Latymer_v_Rock_Plumbing_Heating_and_Electrical_Limited_2601456.2021_DJ.pdf

Eliminating the alignment checks obviously doesn't make sense for cases where you want to resolve different text boxes horizontally, but there are use cases that are exclusively oriented to horizontal lines (like mine) where this works, so having it as an option is useful.

**Comment by pietermarsman** [comment]
Hi @JohnBurant,

Indeed, it depends on the exact locations of the text if changing the layout parameters work or not. The layout algorithm is a best-effort approach and does not support all ways in which humans read text. 

If you need help, could you open a new issue? That helps to keep discussions on point.
