### ISSUE TITLE
pdfminer extracting text incorrectly

### ISSUE THREAD

**Issue by IrinaMax** [pdfminer/pdfminer.six#719]
I am using pdfminer.six==20211012 to working with invoice misspelling detection.
The invoice file has clearly misspelled 'INOVICE' word in the center of the page and pdfminer translated it as 'invoice'.
I do NOT need this correction because I am loosing misspelled information which lead to fraud invoice.
Unfortunately I can not share the pdf file.

the code is
```python
import pdfminer.high_level 

def extract_text_pdf(pdf_path): 
    lst=pdfminer.high_level.extract_text(pdf_path, password='', page_numbers=None, maxpages=0, caching=True, codec='utf-8', laparams=None) 
    return lst 
pdfOut = extract_text_pdf(path7) 
pdfOut
```

and output begining with corrected word 'INVOICE\n\nFROM:\n\nC2B AGENCY LLC\n\nEIN: 37-1824524\n601 Brickell Key Drive Suite 901\nMiami - FL 33131\nUSA\nFone: +5511 4371-0014\npaulo_ogawa@c2bagencia.com\n\nBILL TO:\n...........

But the first word was misspelled as 'INOVICE' and I do not need this correction during extraction.
I would like to keep exact explicit words as it is.
Is it any possible way to get exact text?
Thank you.

**Comment by IrinaMax** [comment]
![image](https://user-images.githubusercontent.com/16123495/155102863-d061ef73-c2e2-404e-9338-8ae7e766b6e8.png)

**Comment by IrinaMax** [comment]
![image](https://user-images.githubusercontent.com/16123495/155102995-de02f1fd-87c7-41ed-a42b-f78abc082d5e.png)

**Comment by pietermarsman** [comment]
pdfminer.six does not do any spelling correction and will never do so. 

I'm in the blue as of what might cause this issue and without the PDF itself we can't offer any help.

**Comment by IrinaMax** [comment]
Then it is definitely bug because pdfminer.six extracted 'INOVICE'  absolutely incorrect.

**Comment by IrinaMax** [comment]
I just found out this INOVICE word is actually image on the top of pdf, so I guess pdfminer did good job to extract pdf but can not see the image on the top. Thanks for collaborating.
