### ISSUE TITLE
PDF to HTML conversion issues

### ISSUE THREAD

**Issue by botzill** [pdfminer/pdfminer.six#72]
Hi,

I'm trying to convert a simple PDF to HTML using:
`pdf2txt.py test.pdf -t html -o test.html`

Here is the test PDF file:
[test.pdf](https://github.com/pdfminer/pdfminer.six/files/1075377/test.pdf)

and here is the output html:
<img width="627" alt="screen shot 2017-06-14 at 8 17 58 pm" src="https://user-images.githubusercontent.com/4686040/27145489-aed0986a-513e-11e7-8be0-c5391dbdf216.png">

html source:
```html
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head><body>
<span style="position:absolute; border: gray 1px solid; left:0px; top:50px; width:595px; height:842px;"></span>
<div style="position:absolute; top:50px;"><a name="1">Page 1</a></div>
<div style="position:absolute; border: textbox 1px solid; writing-mode:lr-tb; left:72px; top:118px; width:448px; height:45px;"><span style="font-family: ; font-size:16px">The Portable Document Format (PDF) is the world’s leading language for describing <br>the printed page</span><span style="font-family: ; font-size:15px"> <br></span><span style="font-family: ; font-size:15px">	<br></span></div><span style="position:absolute; border: black 1px solid; left:72px; top:121px; width:445px; height:13px;"></span>
<span style="position:absolute; border: black 1px solid; left:72px; top:135px; width:86px; height:13px;"></span>
<div style="position:absolute; top:0px;">Page: <a href="#1">1</a></div>
</body></html>
```

Now, the problem is that `width` of the line is incorrectly computed making it to wrap differently then the original doc. This can lead to smth like this:
<img width="575" alt="screen shot 2017-06-14 at 8 21 36 pm" src="https://user-images.githubusercontent.com/4686040/27145648-32c8d2f4-513f-11e7-847b-5ad94cd636cb.png">

Is there a fix for this issue? If not can you guide me where to look so that I can make a PR with the fix?

I think this tool may be helpful for what we need and in this case we can contribute to it.

Thx a lot!

**Comment by botzill** [comment]
I did some investigations about this issue and found out why I had such results. According to PDF specifications:

> **User Space**
>To avoid the device-dependent effects of specifying objects in device space, PDF
defines a device-independent coordinate system that always bears the same relationship
to the current page, regardless of the output device on which printing or
displaying occurs. This device-independent coordinate system is called user
space. 
>The user space coordinate system is initialized to a default state for each page of a
document. The CropBox entry in the page dictionary specifies the rectangle of
user space corresponding to the visible area of the intended output medium (display
window or printed page). The positive x axis extends horizontally to the
right and the positive y axis vertically upward, as in standard mathematical practice
(subject to alteration by the Rotate entry in the page dictionary). The length
of a unit along both the x and y axes is set by the UserUnit entry (PDF 1.6) in the
page dictionary (see Table 3.27). If that entry is not present or supported, the default
value of 1⁄72 inch is used. This coordinate system is called **default user space**. 

So, in my case I'm using PDF-1.3 and there is no **UserUnit** defined which mean that default value is **1pt** but in the output HTML **px** is used. I did some tests and the output is better.

Is there any reason why it was implemented like this?

**Comment by pietermarsman** [comment]
You could use the exact layout mode (using `--layoutmode exact`). This does not group character elements into larger structures, but puts them on their precise location. 

<img width="479" alt="Schermafbeelding 2019-10-25 om 20 56 59" src="https://user-images.githubusercontent.com/3833456/67596936-34722280-f76a-11e9-9c0a-b891d89d173a.png">

I did some testing and found that for your pdf it works well if all the bounding boxes use points (i.e. 1/72 of an inch) and all the font-sizes are in px (1 px is a barely visible line). I also needed to change the font-family from VZWISY+Georgia to Georgia. 

<img width="656" alt="Schermafbeelding 2019-10-25 om 21 06 36" src="https://user-images.githubusercontent.com/3833456/67597508-adbe4500-f76b-11e9-9055-0ce6279782df.png">

I'm not sure if this is a coincidence or not.

**Comment by pietermarsman** [comment]
This issue is partially fixed by #348. 

The core of this issue is that the weight of the characters is not computed correctly. This causes a mismatch between the bounding boxes and the actual text. This problem is solved by #348.

There is also a side issue: the font name from the `test.pdf` is `b'VZWISY+Georgia'`, and this cannot be interpreted by the browser as being Georgia. I've created #349 for this.

**Comment by pietermarsman** [comment]
@botzill do you have time for a review? Could you checkout #348 and #357.

**Comment by pietermarsman** [comment]
FYI, it currently looks like this if you have the Georgia font: 

![Screenshot from 2020-01-16 22-35-24](https://user-images.githubusercontent.com/3833456/72564877-01df4e00-38b1-11ea-8811-8ebdfcd2766c.png)
