### ISSUE TITLE
Formated Text returned by element.get_text() 

### ISSUE THREAD

**Issue by Mohmmde1** [pdfminer/pdfminer.six#721]
**Feature request**

Is it possible to extend the ability to extract text from LTTextContainer, like instead of returning just a string that contain a text, it can return objects  like bulleted lists, numbered lists, headers, and etc. Which will make it easier to use.

For example, I ran into a problem because of this, you can check my question in [stackoverflow](https://stackoverflow.com/questions/71210635/how-to-extract-bullet-points-number-list-in-general-the-layout-of-the-page-fro)

**Comment by pietermarsman** [comment]
Can you give a reproducible example that shows how the output is different from what you need? At least include command/code you are using and the PDF is question.

**Comment by pietermarsman** [comment]
Closing because no response.
