### ISSUE TITLE
Add the test suite to the sdist which is distributed at PyPI

### ISSUE THREAD

**Issue by knobix** [pdfminer/pdfminer.six#722]
**Feature request**

Would it be possible to package the `tests/` and `sample/` directories to the `sdist`, which is distributed at PyPI, as well?  

That would enable downstream (e.g. distro packagers) to run the test suite at their end and check it against Python packages that are installed in their local/stage environments.

**Comment by pietermarsman** [comment]
It is not a very common thing to do (from all pdfminer.six dependencies, only mypy does this) but it is a possibility. 

I do like to keep the build as small as possible, and the sample directory is pretty big. 

Do you have a specific use-case in mind? Do you have examples of other python projects that do this?

**Comment by knobix** [comment]
> I do like to keep the build as small as possible, and the sample directory is pretty big.

Ah, I see, in this respect, it's understandable that the overall size of the sdist should be kept small. 
 
> Do you have a specific use-case in mind? Do you have examples of other python projects that do this?

My usecase would be to check pdfminer.six against local packages of its dependencies (chardet, cryptography) that are available in a distro repository at a time along with supported Python versions.

As far I know there's `OCRmyPDF` which adds a set of sample PDFs to its sdist along with the test suite.

I understand if implementing a small set of unit tests would mean too much effort.  In that case this issue can be closed.

**Comment by pietermarsman** [comment]
In that case I suggest you create your own small set of unit tests and maintain them. I think you could do it by creating a python package that depends on pdfminer.six, and then do what you need to do.
