### ISSUE TITLE
Install the supplied console scripts without the ".py" file extension

### ISSUE THREAD

**Issue by knobix** [pdfminer/pdfminer.six#724]
**Feature request**

Would it be possible to install the two console scripts `pdf2txt.py` and `dumppdf.py` without their `.py` file extension?

Most Python packages, that I'm aware of, provide their console scripts without the `.py` extension.

**Comment by pietermarsman** [comment]
Yes, that would be nices. 

Docs: https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html

**Comment by hholst80** [comment]
This is how the flask script works:

```python
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from flask.cli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

However I would say that this is non-optimal. Better:

```sh
#!/bin/sh
exec python3 -m flask -- "$@"
```

**Comment by pietermarsman** [comment]
I realized that this is not as easy as I thought. The console script needs to be in the pdfminer package, but it is not. It is in the tools/ directory.

Maybe we should move the content of tools/ to the package as well and just keep some aliases there to not have any breaking changes?

**Comment by hholst80** [comment]
Create a __main__.py in the library ping @pietermarsman 

when the package is invoved as a program __main__.py will be executed (after __init__.py if I remember correctly)
