### ISSUE TITLE
Support, how do I use crop box?

### ISSUE THREAD

**Issue by Vricken** [pdfminer/pdfminer.six#725]
How do I use PDFminer in python to crop a page using crop box and save the cropped page in a new pdf?

**Comment by GitHubRulesOK** [comment]
The crop box and media box are often one and the same thus generally nothing is drown outside of either one the cropbox is more often found in scanned images to reduce the noisy areas

from the coode
```
mediabox: the physical size of the page.
--
cropbox: the crop rectangle of the page.
```
however its not needed in miner as you need the whole media box see https://github.com/euske/pdfminer/issues/72#issuecomment-62001947

**Comment by JKsang** [comment]
> 裁剪框和媒体框通常是一个且相同的，因此通常不会在任何一个之外绘制任何内容。裁剪框更常见于扫描图像中以减少噪声区域，它需要在标题和脚线之外，因此包括所有可见或不可见的边缘数据。
> 
> 从代码
> 
> ```
> mediabox: the physical size of the page.
> --
> cropbox: the crop rectangle of the page.
> ```
> 
> 但是它在矿工中不需要，因为您需要整个媒体框，请参阅[euske/pdfminer#72（评论）](https://github.com/euske/pdfminer/issues/72#issuecomment-62001947)

Thanks a lot! However, i found '(cid: xxxx)' in text results parsed from the pdf file, how to fix this problem?

**Comment by pietermarsman** [comment]
This is not possible with pdfminer.six. It only focusses on extracting information, not on transforming pdfs.
