### ISSUE TITLE
extract_pages() stalls on this pdf

### ISSUE THREAD

**Issue by rcyost** [pdfminer/pdfminer.six#726]
Here are two cells of code to display that the pdf is found, and a generator object is created. 

But when I try to iterate using the generator, it just hangs.

![image](https://user-images.githubusercontent.com/32645001/157303134-ecf7a1cb-aff1-44bf-988c-1179f7947618.png)

Please download the file from below page and try to extract pages. 

[This 2021 report stalls.](https://assets.ey.com/content/dam/ey-sites/ey-com/en_gl/topics/tax/ey-2021-worldwide-vat-gst-sales-tax-guide-web.pdf)

[This 2017 report works fine. The 2018 and 2019 reports work ok too.](https://assets.ey.com/content/dam/ey-sites/ey-com/en_gl/topics/tax/guides/worldwide-vat-gst-and-sales-tax-guide-2017.pdf)

This package works on the same report for years 2017, 2018, and 2019. But it hangs on report 2021 for some reason. I've tried passing in page numbers to see if it will even load one, but with no luck.

Can someone please try to download the file and reproduce the hanging?

Thank you.

**Comment by pietermarsman** [comment]
It is a very large PDF. If you print the pages you will see it is iterating through all of them. It takes roughly a minute on my machine.

**Comment by rcyost** [comment]
The other PDF's are the same size? It clearly doesn't work on this PDF for me and I cannot figure out why.

**Comment by pietermarsman** [comment]
You print `pages`, that variable is not defined in your screenshot. Maybe that is causing the issue? 

I use this code: 

```python
import time

from pdfminer.high_level import extract_pages

t0 = time.time()
filing_file = "/home/pieter/Downloads/ey-2021-worldwide-vat-gst-sales-tax-guide-web.pdf"
for p in extract_pages(filing_file):
    print(time.time() - t0, p)
```

The output is: 

```
5.809478998184204 <LTPage(1) 0.000,0.000,419.528,595.276 rotate=0>
5.920790672302246 <LTPage(2) 0.000,0.000,419.528,595.276 rotate=0>
5.938417196273804 <LTPage(3) 0.000,0.000,419.528,595.276 rotate=0>
6.070339679718018 <LTPage(4) 0.000,0.000,419.528,595.276 rotate=0>
6.210592985153198 <LTPage(5) 0.000,0.000,419.528,595.276 rotate=0>
6.366324424743652 <LTPage(6) 0.000,0.000,419.528,595.276 rotate=0>
6.534945726394653 <LTPage(7) 0.000,0.000,419.528,595.276 rotate=0>
```

It starts processing after 6 seconds, and completes 5-10 pages per second. 

With the other pdf (_worldwide-vat-gst-and-sales-tax-guide-2017.pdf_) it is taking much less time.

```
0.08515739440917969 <LTPage(1) 0.000,0.000,306.000,648.000 rotate=0>
0.23123383522033691 <LTPage(2) 0.000,0.000,306.000,648.000 rotate=0>
0.25427937507629395 <LTPage(3) 0.000,0.000,306.000,648.000 rotate=0>
0.33780860900878906 <LTPage(4) 0.000,0.000,306.000,648.000 rotate=0>
0.43613195419311523 <LTPage(5) 0.000,0.000,306.000,648.000 rotate=0>
0.5293810367584229 <LTPage(6) 0.000,0.000,306.000,648.000 rotate=0>
0.5470430850982666 <LTPage(7) 0.000,0.000,306.000,648.000 rotate=0>
0.6076619625091553 <LTPage(8) 0.000,0.000,306.000,648.000 rotate=0>
```

In any case, pdfminer.six is not stalling. Maybe it takes some time to process these (very big) PDF's but it is not broke.
