### ISSUE TITLE
Remove usage of if __name__ == "__main__" from all source files

### ISSUE THREAD

**Issue by pietermarsman** [pdfminer/pdfminer.six#736]
See #735.

Do this 6 months after is has been deprecated.

**Comment by hholst80** [comment]
So the __main__ code should be moved over to `__main__.py` files? Good first issue for anyone that would like to get involved!

**Comment by pietermarsman** [comment]
Currently we use the _tools_ directory for all the commands. But I expect most commands can just be removed since they are for testing purposes only. 

Indeed, good first issue.
