### ISSUE TITLE
Problem with uploaded package on PyPi

### ISSUE THREAD

**Issue by vstoykov** [pdfminer/pdfminer.six#74]
When I install pdfminer from PyPi the source is different than downloaded from github for the same tag.

One example is logging. More especially this change https://github.com/pdfminer/pdfminer.six/commit/1d54ecd31c49886fd43279f6ee2cc8674eaf2d8e which should be present from version 20160614 (one year ago). After that version there are two new versions. 

When I download the package from PyPi  forfor version 20170419 (https://pypi.python.org/packages/43/71/b592b9b384c9bc4429e9a35cc9d61a5eb7fabef2208140c30550a474defe/pdfminer.six-20170419.tar.gz#md5=c43b443ad759441adb07fde5f1ca3435) this change is not there. But when I download the archive from Github for that tag (https://github.com/pdfminer/pdfminer.six/archive/20170419.zip) everything is there.

Now I'm forced to workaround the installation in requirements.txt by adding:

    https://github.com/pdfminer/pdfminer.six/archive/20170419.zip#egg=pdfminer.six==20170419

Which is not ideal.

I'm wondering what may be the issue with the package in PyPi?

**Comment by MartinThoma** [comment]
The package on PyPI is not recent. For example, https://github.com/pdfminer/pdfminer.six/commit/4e59fb66de9d44f31937e1b849feb66886f672e4 is not applied to it.

**Comment by vstoykov** [comment]
@MartinThoma I'm not talking about how recent  is the version uploaded in PyPi. It's normal for one project to have unreleased changes which are only in master (as the commit you mention).

The main problem is that the same version `201704019` which you can obtain by downloading from PyPi or downloading directly from Github by tag (not master branch) is with different code.
Tagged version in Github must be the same as the version on PyPi (or vice versa).

**Comment by goulu** [comment]
Well, I don't know what happened, I usually upload the PyPi packages from my PC just after pushing to GitHub ... Sorry about that. Will upload a new version on Pypi in a few minutes...
