### ISSUE TITLE
Text extraction is not gives all text properly in Hindi Font.

### ISSUE THREAD

**Issue by khivraj-jangid** [pdfminer/pdfminer.six#740]
Hi @pietermarsman 

There is a issue with text while extract from Hindi fonts.
If text is like "हृदय" in PDF, then text extract like "दय"
In Line object its gives output -[<LTTextLineHorizontal 36.503,727.106,85.789,752.115 '\x00दय\n'>]
and Line.get_text() gives output - "दय"
Its not able to read 1st text - "हृ"

I observe that - If text is combine of 2 hindi characters to 1 character then pdfminer.six fails to extract that text. 

This issue is with multiple text which is used in Hindi fonts- the list is below:
हृ , क्त, द्ध, प्र, ष्य, क्र, च्छि, क्त, म्प, भ्रू , स्त, ट्रु, ध्य, न्तः, 

Please find the below attachments so you can get clear with bug:

1- Original PDF
[hindi_heart.pdf](https://github.com/pdfminer/pdfminer.six/files/8347609/hindi_heart.pdf)

2- text copied from 1st page of Original-PDF
[text_copied_from_pdf.docx](https://github.com/pdfminer/pdfminer.six/files/8347617/text_copied_from_pdf.docx)

3- Font files
[fonts.zip](https://github.com/pdfminer/pdfminer.six/files/8347635/fonts.zip)

4- Text extract using pdfminer text extraction
[text_extract_using_pdfminer.docx](https://github.com/pdfminer/pdfminer.six/files/8347641/text_extract_using_pdfminer.docx)

5- Screens
![Screenshot](https://user-images.githubusercontent.com/98871422/160059228-e3dd7c69-3cfa-47f1-b6c3-176780ef3fc5.png)
hot after create HTML using pdfminer.six services.
Note: also check in screenshot - Line (यह लेख शरीर के एक अंग के बारे में है। अन्य प्रयोगों के लिए , हृदय ( बहुविकल्पी ) देखें।) is gives rotational values, but its not a rotated text.

Let me inform once you clear about this bug or if you required any more details regarding same.

Thanks in advanced.

**Comment by pietermarsman** [comment]
How did you copy the text from the PDF? I get completely different output when I copy the text. 

- When I copy the title (the bold text above the line) I get `दय` instead of your `हृदय`
- When I copy the first two characters below the line I get `मु` instead of your `मुक्त`

Coincidentally the characters that are missing are also the ones that you report are wrong in the output of pdfminer.six. 

So really curious to know your exact procedure of getting the text in the word doc.

**Comment by pietermarsman** [comment]
Closing because no response.

**Comment by KunalGehlot** [comment]
A quick note: It might also be the problem of how the Language font itself behaves.
(Hindi does not have a consistent implementation across platforms and even fonts)

The way Hindi characters work is that there can be "half" of one character, which can be combined with a "full" character to create a mixed character. (I have seen this problem in MS Word as well.)

Looking at this issue, I see a similar pattern where the half characters that were combined (`हृ` in `हृदय`) and (`क्त` in `मुक्त`) are causing an issue at the system.

Hence neither @pietermarsman can copy, nor pdfminer can read.
(I can copy the full text `हृदय` in Adobe Acrobat but when I open the pdf in Mac's preview app, it only copies `दय`)
