### ISSUE TITLE
The Reading order doesnot generalize well to multicolumn documents. Which algorithm is used to determine the Reading Order?

### ISSUE THREAD

**Issue by Kishangupta1** [pdfminer/pdfminer.six#753]
**Feature request**

Thanks for your suggestion on improving pdfminer.six. To helps us discuss and
implement this request, please make sure to include the following information:

- A description of the feature you would like to have
- If relevant, the context that you are in. What are you trying to achieve?
- If possible, an example of what you want to achieve. Include the PDF that
  you are working on. Include the output that you would like to have.

**Comment by pietermarsman** [comment]
It is a custom algorithm. It takes into account the distance between characters, words, lines and paragraphs. It is in layout.py. 

Feel free to implement your own `PDFDevice` (the thing that "prints" the PDF to text, html, xml, or any output) and perhaps we can integrate it in pdfminer.six if it works well.
