### ISSUE TITLE
Feature request: ability to extract a portion of a page as image

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [pdfminer/pdfminer.six#759]
Hi, I'm not really sure if this qualifies more as a feature request or as a question.

I got interested in pdfminer because I want to contribute to a downstream project : [pdfannots](https://github.com/0xabu/pdfannots/) (python script that extracts pdf annotation to markdown).

I decided to reach out to you at the end of [this issue thread](https://github.com/0xabu/pdfannots/issues/52#issuecomment-1126972031)

My goal is to implement a way to extract rectangular selection annotation from a pdf as images in my markdown files.

However, after reading your docs I can't be certain that this is not already possible, because "image" in this topic always mean "image inside the pdf" instead of "rendering the pdf as image".

I really hope that here is the correct place to ask this : could you tell me if it's possible to turn a specific location of a pdf page to an image? And if not, can you consider implementing this? Or can you recommend another method?

Thanks a lot!

**Comment by pettzilla1** [comment]
It may be hard to find a way of doing this that is compatible with keeping the package MIT unless the functionality was optional on install as pretty much all of the Python packages that convert a page to an image are dependent on copy left licences.

**Comment by pietermarsman** [comment]
Currently it is not possible to convert (a portion of) a PDF to images with pdfminer.six. 

Perhaps you could use [py-pdf-parser](https://py-pdf-parser.readthedocs.io/en/latest/overview.html#visualisation-tool) made by @jstockwin. Or use it as inspiration.

**Comment by thiswillbeyourgithub** [comment]
Thank you both for the quick answer and the suggestion. I'll think about it more.
