### ISSUE TITLE
Problems trying to parse CID to Unicode, getting a lot of (cid:xxx)

### ISSUE THREAD

**Issue by hullyang** [pdfminer/pdfminer.six#764]
Hi guys, I'm trying to extract texts from the attached pdf, and found weird problems to parse CID to Unicode:
[002893_2017-08-15_华通热力：首次公开发行股票招股说明书.pdf](https://github.com/pdfminer/pdfminer.six/files/8836606/002893_2017-08-15_.pdf)

The problems include:
1. CIDSystemInfo is not ASCII.  For example, at page 1, cid_registry = ''ÿ$\x00è\x19''

2. The ToUnicode map embeded in pdf file doesn't match the CIDs, causing a lot of PDFUnicodeNotDefined exceptions.

3. I tried to use [https://github.com/adobe-type-tools/mapping-resources-pdf/tree/master/pdf2unicode](url) as external ToUnicode map, but CIDs in the pdf seems don't follow standard mapping relationship. The resulting unicodes completely don't match the actual displayed characters.

Does anyone know the cause and solution? Really appreciate your help ! Thanks a lot:)

**Comment by pietermarsman** [comment]
Your PDF has a missing or wrong "ToUnicode" mapping for its glyphs.

A PDF has a separate representations for how to draw glyphs (e.g. the font) and what their meaning is in terms of unicode. You see the glyphs and if you copy-paste the text you get the unicode.

However, your PDF has a missing or wrong unicode mapping. If you copy-paste from the PDF directly you will get gibberish. Pdfminer.six is doing the same thing, but automated, and gets the same result (=gibberish).

Not much we can do (sadly) to improve the results.

**Comment by LY1806620741** [comment]
I encountered the same problem. Can I use OCR to reconstruct the character mapping? I'm trying to understand the underlying structure of pdfminer but it's a bit complicated for me, can you give me some advice?
