### ISSUE TITLE
A subscript-able extract_page() function.

### ISSUE THREAD

**Issue by realaltffour** [pdfminer/pdfminer.six#765]
**Feature request**

Sometimes it is a necessity to access layouts of other pages when parsing for complex applications. For example, I am currently working on [wsgen.db](https://codeberg.org/ayham/wsgen.db), a project for parsing questions from examination papers. A situation that can arise, although rare, is questions spanning multiple pages. In these cases, I do not see any other simple solution other than retrieving the next-page, something like ```extract_pages()[pageNo+1]```.

Context aside, it should be simple to add a (new?) function which gives the option to store the entirety of the pdf rather than yielding back, which is currently the functionality of ```extract_pages()```. Results are stored and returned by the ```extract_page()``` function. This makes it easy to do stuff like ```extract_page()[startPage:]```, currently impossible without weird while/for-if loops.

As I have already said, it _should_ be simple. In my situation, I was able to get-by by locally overriding the extract pages function like-so:

```python
def extract_pages(
        pdf_file: FileOrName,
        password: str = "",
        page_numbers: Optional[Container[int]] = None,
        maxpages: int = 0,
        caching: bool = True,
        laparams: Optional[LAParams] = None,
        ):
    laparams = LAParams()
    results = []

    with open_filename(pdf_file, "rb") as fp:
        fp = cast(BinaryIO, fp)  # we opened in binary mode
        resource_manager = PDFResourceManager(caching=caching)
        device = PDFPageAggregator(resource_manager, laparams=laparams)
        interpreter = PDFPageInterpreter(resource_manager, device)
        for page in PDFPage.get_pages(
            fp, page_numbers, maxpages=maxpages, password=password, caching=caching
        ):
            interpreter.process_page(page)
            layout = device.get_result()
            results.append(layout)

    return results
```

I am opening this issue to get some feedback, as I am willing to write a pull-request for this feature.
If a new function is to be added, what would it be named?
Is there a use for the current `extract_pages()` function? Less Memory usage?

**Comment by pietermarsman** [comment]
If you want to have all pages you can use:

```python
pages = list(extract_pages(filename))
```
