### ISSUE TITLE
fontname of TrueType(Arial, TimesNewRoman) is unknown

### ISSUE THREAD

**Issue by sobuen** [pdfminer/pdfminer.six#767]
**Bug report**

In the following [pdf file](https://github.com/pdfminer/pdfminer.six/files/8985522/C019_ASME00_Manipulator_calibration.pdf) the fontname of particuler fonts were not recognized and treated as "unknown". 

Due to the error, every single letter was got one by one and not treated as a chunk, and the bbox, width, height, etc. of the letters in those fonts were recorded as "0". 
The location of the letters were also in error (Multiple latters ,for instance in the same sentence, had almost the same x value).

The fonts in trouble are the following;
```pdf
<<
/Type /Font
/Subtype /TrueType
/Name /F2
/BaseFont /Arial
/Encoding /WinAnsiEncoding
>>
:
<<
/Type /Font
/Subtype /TrueType
/Name /F3
/BaseFont /TimesNewRoman#2CBold
/Encoding /WinAnsiEncoding
>>
:
```

These fonts are recognized by adobe reader, chrome/edge, etc.

The result of debug shows that "Arial" or "TimesNewRoman" were not in FONT_METRICS.
Also, we found that there was no FontDescriptor in the "spec" and "descriptor" was empty.
We think that is the reason why the fontname is "unknown."

```
(SHA-1: 86e34873e4daeb7329aa7420208e82f8d41e38b6)

interpreter.process_page(page)
-> self.render_contents(page.resources, page.contents, ctm=ctm) : pdfinterp.py l.991
-> self.init_resources(resources) : pdfinterp.py l.1008
-> self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec) : pdfinterp.py l.1008
-> font = PDFTrueTypeFont(self, spec) : pdfinterp.py l.219
-> (descriptor, int_widths) = FontMetricsDB.get_metrics(self.basefont) : pdffont.py l.990
-> return FONT_METRICS[fontname] : pdffont.py l.103
```

```python
# (pdffont.py, PDFType1Font class, l.989~998)

try:
    (descriptor, int_widths) = FontMetricsDB.get_metrics(self.basefont)
    widths = cast(Dict[str, float], int_widths)  # implicit int->float
except KeyError:
    descriptor = dict_value(spec.get("FontDescriptor", {}))
    firstchar = int_value(spec.get("FirstChar", 0))
    # lastchar = int_value(spec.get('LastChar', 255))
    width_list = list_value(spec.get("Widths", [0] * 256))
    widths = {i + firstchar: w for (i, w) in enumerate(width_list)}
PDFSimpleFont.__init__(self, descriptor, widths, spec)
```

```python
# (pdffont.py, PDFFont class, l.859)

self.fontname = resolve1(descriptor.get("FontName", "unknown"))
```

How can we deal with this case?

**Comment by pietermarsman** [comment]
Is this summary correct: the layout algorithm fails because each `LTChar` has zero width and height. The zero width and height is there because the base font (arial) is not in the font metrics. We should include arial in the font metrics. 

If so, I agree! 

According to [Section 5.5.1 of the PDF Reference](https://ghostscript.com/~robin/pdf_reference17.pdf) the base font Arial is an alias of Helvetica. So a simple copy-paste in font_metrics.py should do the trick.

**Comment by sobuen** [comment]
@pietermarsman 
Many thanks for your perfect comment! 
It worked! 
By adding the followings to the end of the fontmetrics.py, unknown fonts disappeared and the fonts are recognized as correct ones (at the moment put as an alias)

```python
FONT_METRICS["Arial"] = FONT_METRICS["Helvetica"]
FONT_METRICS["Arial,Italic"] = FONT_METRICS["Helvetica-Oblique"]
FONT_METRICS["Arial,Bold"] = FONT_METRICS["Helvetica-Bold"]
FONT_METRICS["Arial,BoldItalic"] = FONT_METRICS["Helvetica-BoldOblique"]
FONT_METRICS["CourierNew"] = FONT_METRICS["Courier"]
FONT_METRICS["CourierNew,Italic"] = FONT_METRICS["Courier-Oblique"]
FONT_METRICS["CourierNew,Bold"] = FONT_METRICS["Courier-Bold"]
FONT_METRICS["CourierNew,BoldItalic"] = FONT_METRICS["Courier-BoldOblique"]
FONT_METRICS["TimesNewRoman"] = FONT_METRICS["Times-Roman"]
FONT_METRICS["TimesNewRoman,Italic"] = FONT_METRICS["Times-Italic"]
FONT_METRICS["TimesNewRoman,Bold"] = FONT_METRICS["Times-Bold"]
FONT_METRICS["TimesNewRoman,BoldItalic"] = FONT_METRICS["Times-BoldItalic"]
```

We were able to take the Arial and the TimesNewRoman characters from the file that mattered and problem solved. (confirmed that your tip worked with "Arial", "Arial,Bold", "TimesNewRoman", "TimesNewRoman,Italic", "TimesNewRoman,Bold" , while the "Arial,Italic", "Arial,BoldItalic", "TimesNewRoman,BoldItalic", "CourierNew*" not yet confirmed)

Thanks again!

In case above change works for you, I'd PR it, what would you say? ( I'm asking your approval as "CourierNew" etc. has not been confirmed on our side as mentioned above)

**Comment by pietermarsman** [comment]
@sobuen  I would love to see a PR for this! :)
