### ISSUE TITLE
high_level.py extract_text function fix

### ISSUE THREAD

**Issue by sky0193** [pdfminer/pdfminer.six#770]
**Bug report**

Thanks for finding the bug! To help us fix it, please make sure that you 
include the following information:

- A description of the bug
- Steps to reproduce the bug. Try to minimize the number of steps needed. 
  Include the command and/or script that you use. Also include the PDF that 
  you use.
- If relevant, include the output and/or error stacktrace. 

file: `high_level.py`
function: 

```
def extract_text(pdf_file, password='', page_numbers=None, maxpages=0,
                 caching=True, codec='utf-8', laparams=None):
```

line:

```
 device = TextConverter(rsrcmgr, output_string, codec=codec,
                               laparams=laparams)
```

causes Error

```
__init__() got an unexpected keyword argument 'codec'
```

as TextConverter dont have `codec` as keyword.

```
class TextConverter(PDFConverter):

    def __init__(self, rsrcmgr, outfp, pageno=1, laparams=None,
                 showpageno=False, imagewriter=None):
```

## Steps to reproduce

```
from pdfminer.high_level import extract_text

filename = 'resources/pdf_files/Die_vier_Jahreszeiten.pdf'

text = extract_text(filename)

print(text)
```

**Comment by pietermarsman** [comment]
You are have multiple pdfminer versions installed. Or some other installation issue. 

The TextConverter class has a codec argument for over 12 years now. 

See: https://github.com/pdfminer/pdfminer.six/blame/33d7dde4d1a5684759070115d0495c48ba8f886d/pdfminer/converter.py
