### ISSUE TITLE
Extraxt pdf to txt

### ISSUE THREAD

**Issue by Pilli68** [pdfminer/pdfminer.six#780]
Hello everyone , I am new to Github. So I need your help/suggestions/inputs/advice.
Here I attached my pdf file. i want to convert each and everything in pdf into text without header data .footer data. Kindly request you please do needful action.
Note: Pdf file contains mathematical equations , images ,logos and other stuff.

[Unit-1.pdf](https://github.com/pdfminer/pdfminer.six/files/9016450/Unit-1.pdf)

**Comment by pietermarsman** [comment]
Hi @Pilli68,

I hope you figured this out yourself.

For next time, it helps if you show what you already did and explain what part of the code is not working as expected.
