### ISSUE TITLE
What required for extracting characters from pdf to work?

### ISSUE THREAD

**Issue by hoangmt** [pdfminer/pdfminer.six#782]
Hi,
What are the requirements of the pdf for the tool to work? Any kind of format or required layer? I trying to debug through the code but would be very much appreciated if someone can shed a light on this.

**Comment by krishnasism** [comment]
What kind of issue are you facing? @hoangmt

**Comment by hoangmt** [comment]
Thank you for replying @krishnasism. The problem i am facing is that for some files, the text locations (bounding box) are kind of perfect, however, for some other pdfs, the bounding box are like 30% shorter than it should be. Sorry I can not share the files here. :(
Just to provide more infor, in case it helps: for the pdf files that the location extracted are perfect, I can convert pdf to svg with the text elements reserved using inkscape, for the other pdfs, inkscape can only convert text to path.

**Comment by pietermarsman** [comment]
pdfminer.six supports almost all features from the PDF-1.7 specification.
