### ISSUE TITLE
Question: how to extract character (LTChar) directly from the page

### ISSUE THREAD

**Issue by Ev2geny** [pdfminer/pdfminer.six#783]
Thank you for supporting this tool.
I need to extract characters (```LTChar```) directly from the page without prior automatic layout analysis, because I want to do my own. There is a code example on the [documentation side](https://pdfminersix.readthedocs.io/en/latest/tutorial/extract_pages.html)
```py
from pdfminer.high_level import extract_pages
from pdfminer.layout import LTTextContainer, LTChar
for page_layout in extract_pages("test.pdf"):
    for element in page_layout:
        if isinstance(element, LTTextContainer):
            for text_line in element:
                for character in text_line:
                    if isinstance(character, LTChar):
                        print(character.fontname)
                        print(character.size)
```
I could use it this, but this means, that all the code, related to the automatic layout analysis has already run, which is the waste. So, how do I get to the characters directly?

I know the answer is somewhere in the source code, but I cannot get my head around it.

**Comment by pietermarsman** [comment]
You can disable layout analysis by using `laparams=None`.
