### ISSUE TITLE
Extract total page count from catalog ~ PDFObjRef

### ISSUE THREAD

**Issue by wendlingd** [pdfminer/pdfminer.six#789]
In now-Closed #172 there was a request for a super-short example for dealing with PDFObjRef.

Please point me to a super-short example of extracting the page count from the catalog. The below does not work. I have also been trying to access resolve1(catList['ViewerPreferences'])['DisplayDocTitle'] but I assume this is similar.

```
from pdfminer.pdfparser import PDFParser, PDFStreamParser
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdftypes import PDFStream, PDFObjRef, resolve1, stream_value
from pdfminer.psparser import PSLiteral, PSKeyword
from pdfminer.utils import decode_text

...

        with open(os.path.join('pdf/',filename), "rb") as fp:
            parser = PDFParser(fp)
            doc = PDFDocument(parser, fallback=True)

        catList = doc.catalog

        # currPgCount; so far has looked like 'Pages': <PDFObjRef:868>
        if 'Pages' in catList:
            try:
                currPgCount = resolve1(catList['Pages'])['Count']
            except:
                currPgCount = 'except'
        else:
            currPgCount = 'final else'
        
        print(currPgCount)
 
```

Thanks for this package, looks very useful!

**Comment by KunalGehlot** [comment]
Can you share the pdf as well?

**Comment by wendlingd** [comment]
Thanks, here are some URLs and what appears to be their contents, that I am getting. For page count I get only PDFObjRef. For the document property for Initial View, propDisplayDocTitle, my hope is to have True or False for whether the document is set to show the document title rather than the file name. This is an accessibility testing project.

[randomTestFiles.csv](https://github.com/pdfminer/pdfminer.six/files/9274930/randomTestFiles.csv)

**Comment by KunalGehlot** [comment]
Here are my observations, I ran the same code with the Expedia pdf.
It raised an exception: `seek of closed file`

All I had to do was put the following lines within the `with` and it worked.

Here is the working code
```Python
with open(os.path.join('01.pdf'), "rb") as fp:
    parser = PDFParser(fp)
    doc = PDFDocument(parser, fallback=True)

    catList = doc.catalog

    # currPgCount; so far has looked like 'Pages': <PDFObjRef:868>
    if 'Pages' in catList:
        try:
            currPgCount = resolve1(catList['Pages'])['Count']
        except:
            currPgCount = 'except'
    else:
        currPgCount = 'final else'

    print(currPgCount)
```

**Comment by wendlingd** [comment]
Awesome, thanks! I didn't think of the indents.
