### ISSUE TITLE
Extracted text isn't correct

### ISSUE THREAD

**Issue by Mart320** [pdfminer/pdfminer.six#791]
I'm not able to extract all correct data from pdf. The result of the newest version of pdfminer.six is much better, but some characters are still not correct.
In pdminer.six version 20181108 I've got this result:
`C.IV.2.(cid:51)(cid:72)(cid:81)(cid:268)(cid:229)(cid:81)(cid:116)(cid:3)(cid:83)(cid:85)(cid:82)(cid:86)(cid:87)(cid:284)(cid:72)(cid:71)(cid:78)(cid:92)(cid:3)(cid:81)(cid:68)(cid:3)(cid:126)(cid:254)(cid:87)(cid:72)(cid:70)(cid:75)`
the code is:
```python
from io import StringIO
from pdfminer.high_level import extract_text_to_fp

output_string = StringIO()
with open(r"c:\test.pdf", "rb") as fin:
    extract_text_to_fp(fin, output_string)
print(output_string.getvalue().strip())
```
In pdminer.six version 20220524 I've got this result:
`C.IV.2.
PeněžnÊprostředkyÊnaÊčtech
D.
D.1.
ČasovÊrozlišenÊaktiv
NkladyÊpřštchÊobdobÊ`

the code is:
```python
text = extract_text(
    pdf_file=r"c:\pdf_test\test.pdf",
    password="",
    page_numbers=None,
    maxpages=1,
    caching=True,
    codec="utf-16",
    laparams=None,
)
text = str(text)
text = text.replace("\n\n\n", "\n\n").strip()
print(text)

```
Is there any option to improve this text extraction? The pdf you can find in attachement. [test.pdf](https://github.com/pdfminer/pdfminer.six/files/9299083/test.pdf)

I've found this issue below, maybe it's the same problem, but I am not sure.
https://github.com/pdfminer/pdfminer.six/issues/746

**Comment by pietermarsman** [comment]
I can replicate this. The output of `python tools/pdf2txt.py test.pdf --codec utf-16` is: 

```
C.IV.2.

PeněžnÊprostředkyÊnaÊčtech

D.

D.1.

ČasovÊrozlišenÊaktiv

NkladyÊpřštchÊobdobÊ

 4 961  

  22  

  22  

 4 961  

 17 102  

  22  

  22  

  14  

  14  

  
  
  

```

**Comment by pietermarsman** [comment]
Not sure what the problem is though. Someone needs to investigate why some characters are not converted properly to unicode.

**Comment by KunalGehlot** [comment]
I'll try to look into it.

**Comment by Mart320** [comment]
> I'll try to look into it.

@KunalGehlot Thank you

**Comment by KunalGehlot** [comment]
Unable to recreate the issue, using ad6587c6970c4efeeb7196bf3e038603c1f77e82

For the same run command `python tools/pdf2txt.py test.pdf --codec utf-16`

I'm getting the output:

```bash
C.IV.2.

PeněžnÊprostředkyÊnaÊčtech

D.

D.1.

ČasovÊrozlišenÊaktiv

NkladyÊpřštchÊobdobÊ

 4 961  

  22  

  22  

 4 961  

 17 102  

  22  

  22  

  14  

  14
```

Python version: 3.9.12
pdfminer version: 20220524
[pip list dump](https://pastebin.com/0EqwNNaA)

**Comment by jjbiggins** [comment]
The above text is close, but still not correct. 

I was able to replicate both issues with the respective versions mentioned. I spent some time investigating; I haven't discovered a comprehensive solution, but here's was I have discovered.

It appears this PDF was created using Adobe Acrobat DC Paper Capture. This method uses OCR to make the text searchable. Furthermore, the PDF appears to contain a redaction of text. When opened in firefox, if one were to highlight the text in question, and copy-and-paste it elsewhere they would see what is copied is not what is visible. 

Also, using exiftool -v on the test.pdf file, one can see a font named /HiddenHorzOCR, and using pdffonts shows two non-embedded fonts. This leads me to the conclusion that the text shown is not embedded, and the /HiddenHorzOCR font comes from the redaction/OCR used in converting a scanned image to Adobe PDF. 

I'm not sure if my line of thinking is correct, or anyone more knowledgable could expand upon my observations. This appears to be rather unique PDF, and OCR maybe the only feasible method of proper extraction. I tested numerous text extraction tools, and found non that could accurately extract the text.

**Comment by Mart320** [comment]
> The above text is close, but still not correct.
> 
> I was able to replicate both issues with the respective versions mentioned. I spent some time investigating; I haven't discovered a comprehensive solution, but here's was I have discovered.
> 
> It appears this PDF was created using Adobe Acrobat DC Paper Capture. This method uses OCR to make the text searchable. Furthermore, the PDF appears to contain a redaction of text. When opened in firefox, if one were to highlight the text in question, and copy-and-paste it elsewhere they would see what is copied is not what is visible.
> 
> Also, using exiftool -v on the test.pdf file, one can see a font named /HiddenHorzOCR, and using pdffonts shows two non-embedded fonts. This leads me to the conclusion that the text shown is not embedded, and the /HiddenHorzOCR font comes from the redaction/OCR used in converting a scanned image to Adobe PDF.
> 
> I'm not sure if my line of thinking is correct, or anyone more knowledgable could expand upon my observations. This appears to be rather unique PDF, and OCR maybe the only feasible method of proper extraction. I tested numerous text extraction tools, and found non that could accurately extract the text.

Thank you @jjbiggins , 
I testet also many tools, but the best one was the newest version of pdfminer.six, that's why I hoped there's another solution than OCR, but it looks there's not.

**Comment by datatalking** [comment]
@jjbiggins would it make sense or is it feasible to create a feature as a sort of document_test function that looks for a variety of known issues and reports this to user?
