### ISSUE TITLE
Follow up from pull request #744

### ISSUE THREAD

**Issue by pettzilla1** [pdfminer/pdfminer.six#800]
Hi Is it possible to add as a requirement of any changes to the install requirements that they all be non copy left packages with no copy left dependencies as if any were this would mean that pdfminer.six would be copy left itself rather than MIT

**Comment by KunalGehlot** [comment]
Tagging #744 

We could do that; it shouldn't be a problem. I concur with the argument.

**Comment by pietermarsman** [comment]
Yes, I agree that that is desirable. 

Should be mentioned in the *CONTRIBUTING.md*
