### ISSUE TITLE
PDFObjRef  instead of int

### ISSUE THREAD

**Issue by gosiafilipek** [pdfminer/pdfminer.six#833]
I've encountered bug during extracting pages using extract_pages() (pdfminer.high_level). 
I already found a solution so I will create pull request with it.
Image below provides this bug:
![image](https://user-images.githubusercontent.com/90677030/202421118-152b45b2-0a6c-47a3-aecf-52b5c3aa6968.png)
![image](https://user-images.githubusercontent.com/90677030/202429440-fdbc246e-767a-48ce-abf5-1b5074dca757.png)
![image](https://user-images.githubusercontent.com/90677030/202441450-9e9396f2-8917-4fa8-b43b-56710f65f42e.png)

pdfminer version: 20221105
pdf to recreate bug: 
[pdf_bug_1.pdf](https://github.com/pdfminer/pdfminer.six/files/10030743/pdf_bug_1.pdf)

**Comment by KunalGehlot** [comment]
Confirmed, could replicate the bug

<img width="874" alt="image" src="https://user-images.githubusercontent.com/29948053/204499297-5aba9c31-724a-4d2e-8d77-550b689603f1.png">

Would love to see your PR on this :)

**Comment by gosiafilipek** [comment]
PR #834
https://github.com/pdfminer/pdfminer.six/pull/834#issue-1453253203
