### ISSUE TITLE
Is it possible to extract images using extract_pages()?

### ISSUE THREAD

**Issue by matthewcummings** [pdfminer/pdfminer.six#847]
**Cannot find/extract images use `extract_pages()`**

Hello, thank you for maintaining this project, `pdfminer.six` is excellent. I have a question about finding and extracting images from file using `extract_pages()`? Is that even possible? I seem to be able to detect every other page object type but I cannot list or access images.

I suspect that I'm missing something obvious here. Any help is appreciated.

**Comment by vilabho** [comment]
Hi @matthewcummings , definitely it is possible to extract all images from pdf; here's simple code to do the job : 
```
import pdfminer
from pdfminer.image import ImageWriter
from pdfminer.high_level import extract_pages


def get_image(layout_object):
    # recursively locate Image objects in page_layout
    if isinstance(layout_object, pdfminer.layout.LTImage):
        return [layout_object]
    if isinstance(layout_object, pdfminer.layout.LTContainer):
        img_list = []
        for child in layout_object:
            img_list = img_list + get_image(child)
        return img_list
    else:
        return []

def extract_pdf_img(pdf_filepath):
    iw = ImageWriter('output_dir')
    for page_layout in extract_pages(pdf_filepath):
        image_list = get_image(page_layout)
        if len(image_list):
            for image in image_list:
                iw.export_image(image)


if __name__ == "__main__":
    pdf_filepath = r"C:\projects\git-repos\pdfminer.six\samples\SamplePdf_1.73Mb_87_Page.pdf"
    extract_pdf_img(pdf_filepath)

```
Here is the sample pdf input file that I tested with -
[SamplePdf_1.73Mb_87_Page.pdf](https://github.com/pdfminer/pdfminer.six/files/10747974/SamplePdf_1.73Mb_87_Page.pdf)
and 
the images extracted from above input are in zip file - 
[output_dir.zip](https://github.com/pdfminer/pdfminer.six/files/10747983/output_dir.zip)

**Comment by matthewcummings** [comment]
@vilabho thank you for the response. I forgot that I had posted this issue, I figured this out sometime thereafter. I didn't know at first that images could be embedded in (potentially nested) LTContainer objects.

**Comment by parasatiskylar** [comment]
> Hi @matthewcummings , definitely it is possible to extract all images from pdf; here's simple code to do the job :
> 
> ```
> import pdfminer
> from pdfminer.image import ImageWriter
> from pdfminer.high_level import extract_pages
> 
> 
> def get_image(layout_object):
>     # recursively locate Image objects in page_layout
>     if isinstance(layout_object, pdfminer.layout.LTImage):
>         return [layout_object]
>     if isinstance(layout_object, pdfminer.layout.LTContainer):
>         img_list = []
>         for child in layout_object:
>             img_list = img_list + get_image(child)
>         return img_list
>     else:
>         return []
> 
> def extract_pdf_img(pdf_filepath):
>     iw = ImageWriter('output_dir')
>     for page_layout in extract_pages(pdf_filepath):
>         image_list = get_image(page_layout)
>         if len(image_list):
>             for image in image_list:
>                 iw.export_image(image)
> 
> 
> if __name__ == "__main__":
>     pdf_filepath = r"C:\projects\git-repos\pdfminer.six\samples\SamplePdf_1.73Mb_87_Page.pdf"
>     extract_pdf_img(pdf_filepath)
> ```
> 
> Here is the sample pdf input file that I tested with - [SamplePdf_1.73Mb_87_Page.pdf](https://github.com/pdfminer/pdfminer.six/files/10747974/SamplePdf_1.73Mb_87_Page.pdf) and the images extracted from above input are in zip file - [output_dir.zip](https://github.com/pdfminer/pdfminer.six/files/10747983/output_dir.zip)

Thanks it worked really fine
