### ISSUE TITLE
PDF to HTML conversion issues <br> between table cells rather than separate divs

### ISSUE THREAD

**Issue by pettzilla1** [pdfminer/pdfminer.six#856]
Hi I'm having some issue with a few PDFs ( unfortunately I cannot provide these ) 

The tables in the PDF have a unusual format if it were a pub quiz it would be written like 

question 1 |  answer 1 |   question 2 |  answer 2 |
question 3 |  answer 3_________________________|
question 4 |  answer 4              |   question 5        |        answer 5   | 

when I convert to html the tables in the PDF  it is pulling out the items column wise i.e.
`<div><span> question 1 <br> question 3<br> question 4<br><\span><\div>`
`<div><span> answer 1 <br> answer 3<br> question 4<br><\span><\div>`

is there any way in the settings to have each cell pulled out individually ? so it would be something like , so the positional arguments are not lost ?

`<div><span> question 1 <\span><\div>`
`<div><span>question 3<\span><\div>`

If not I think this may be a bug , thanks in advance

**Comment by vilabho** [comment]
Hi @pettzilla1,
Contents of a PDF are not stored in the order that we see it on screen; especially when content format is complicated like text within image body, tables with multiple spacing etc. 
So its very well possible that each text box in a single row of the table you are trying to extract is stored column wise, but displayed row wise or vis-a-versa. There is no exact order between stored text and sequence of text/table displayed on screen after pdf is rendered.

So this is not a bug in code but rather a PDF file content misalignment. 

However if you still want the order of text just like the screen, you can extract the pdf text with its (X,Y) page coordinates , after which you can sort them either on X or Y to get the desired output.

**Comment by pettzilla1** [comment]
Hi @vilabho ,
I’d normally presume this is the case however when the pdfs are opened and the rows of the table highlighted the column is not highlighted, I normally find this to be the case when the pdfs are formatted weirdly, in addition when they are converted to a word document the tables are extracted fine.

**Comment by pettzilla1** [comment]
If anyone else is experiencing the issue,

Just got to the bottom of this @vilabho, Its partially to do with how the pdf is organised but not fully https://github.com/pdfminer/pdfminer.six/issues/276 explains it better basically the text was very close together so being combined into one text box so the layout parameters need to be altered.
