### ISSUE TITLE
In setup.py, URL of project is a 404

### ISSUE THREAD

**Issue by hydrargyrum** [pdfminer/pdfminer.six#86]
The URL should be https://github.com/pdfminer/pdfminer.six/ but is https://github.com/pdfminer/pdfminer
Then, it's also wrong in https://pypi.python.org/pypi/pdfminer.six/20170720

**Comment by vstoykov** [comment]
It should be fixed in #87. When next release is made then it will be fixed in PyPi.

**Comment by pietermarsman** [comment]
Closing this as it is already fixed
