### ISSUE TITLE
Keywords that end a code stream are ignored.

### ISSUE THREAD

**Issue by qued** [pdfminer/pdfminer.six#884]
**Bug report**

Certain PDFs contain code where a stream of operations ends with a keyword, without any of the `END_KEYWORD` characters following it. This causes the parsing to end without the keyword being parsed, even though otherwise the operation stream is valid. For example, in the attached PDF, a code stream consists of `b'543 0 0 738 0 0 cm\n /Im1 Do'`.

The expected behavior is that if a code stream terminates while parsing a keyword, if the keyword is valid it will execute. Readers such as Adobe Reader, Chrome, and Firefox are able to render the images in the example PDF linked below.

**To reproduce**
```python
from pdfminer.high_level import extract_pages

elements = [el for page in extract_pages("IRS-form-1987.pdf") for el in page]
```
...will produce a list with two empty lists (one for each page), when each page contains a single image as an XObject.

Attached file used to reproduce: [IRS-form-1987.pdf](https://github.com/pdfminer/pdfminer.six/files/11392189/IRS-form-1987.pdf)

**Comment by pietermarsman** [comment]
I can reproduce this.

```python
from pdfminer.high_level import extract_pages

for page in extract_pages("IRS-form-1987.pdf"):
    for el in page:
        print(page, el)
```

Prints nothing.

**Comment by cole-dda** [comment]
The fix issue other problem。

Because parser use buf，sush as, stream = b'/IM Do'
but now buf=b'/IM D'
parse keyword => 'D'
use old method ,continue fill buf,again parse => 'Do'

code may be:
<img width="700" alt="screenshot_6595" src="https://github.com/user-attachments/assets/2a6c8dc1-08b0-4ee6-9e0b-74425a618540" />
