### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by QuentinAndre11** [pdfminer/pdfminer.six#915]
**When will the next version be released?**

Hello, 
I'm using pdfplumber which is built on the PyPi version of pdfminer.six, and I'd like to use the Bezier curves feature, but it's not available on the last release. Do you have an idea of when the last version (or at least the Bezier curves commit) will be released ?
Thanks a lot for your work

**Comment by WolfgangFahl** [comment]
see #165  see #154

**Comment by pietermarsman** [comment]
I'll do a next release after #923  is merged.

**Comment by pietermarsman** [comment]
Done.
