### ISSUE TITLE
Can not extract image from pdf

### ISSUE THREAD

**Issue by zd3tl** [pdfminer/pdfminer.six#920]
- A description of the bug

Try to extract image from https://raft.github.io/raft.pdf, follow https://pdfminersix.readthedocs.io/en/latest/howto/images.html, but image in output-dir all empty.

- Steps to reproduce the bug. Try to minimize the number of steps needed. 
  Include the command and/or script that you use. Also include the PDF that 
  you use.

Please download https://raft.github.io/raft.pdf, and run command `python3 pdf2txt.py -O yourdirname raft.pdf` in terminal , and then cd to your dir, open bmp file.

**Comment by FaizanSh** [comment]
@zd3tl - Thank you for creating the issue. Can you confirm the version which has this issue?

**Comment by zd3tl** [comment]
It's ok now，issue can be closed, thx.

**Comment by FaizanSh** [comment]
@zd3tl - Thank you for updating. Could you add any further information about how the issue was resolved?
