### ISSUE TITLE
original_path extraction error regarding LTCurve

### ISSUE THREAD

**Issue by KaboChow** [pdfminer/pdfminer.six#925]
During the process of extracting shape data from a PDF, I converted the created text letter 'o' into a shape object.

![image](https://github.com/pdfminer/pdfminer.six/assets/46550365/76ce7a9f-3c14-42eb-ada5-8eb086d78380)
Here is the curve data I obtained.

![image](https://github.com/pdfminer/pdfminer.six/assets/46550365/f9e4fe52-3f14-4ee8-aa33-6f2da9947478)
Normally, there should only be one set of curve data. 
However, it seems that there are two in this case. Here is the graphic created on the canvas using the obtained data:

![image](https://github.com/pdfminer/pdfminer.six/assets/46550365/90ce9794-8a39-4183-9c41-ea6434fe620e)
The filling color obtained for the second set of curve data is incorrect. 

This is the PDF I conducted the test on:
[LTCurve.pdf](https://github.com/pdfminer/pdfminer.six/files/13611413/LTCurve.pdf)

Is there any way to resolve this? 
Thank you very much.

**Comment by pietermarsman** [comment]
@KaboChow What is the code you are using to extract the curves?

**Comment by KaboChow** [comment]
@pietermarsman Thank you for your reply.
Regarding the question I am having, I have found the answer in another question [https://github.com/jsvine/pdfplumber/issues/1057] (url).
