### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by reema93jain** [pdfminer/pdfminer.six#926]
Hi Team,

I am trying pdfplumber for parsing data from pdf. When I tried importing pdfplumber I got below error:

"ImportError: cannot import name 'PDFStackT' from 'pdfminer.pdfinterp' (C:\Users\reema\anaconda3\Lib\site-packages\pdfminer\pdfinterp.py)"

I also upgraded to pdfminer.six & my python version is Python 3.10.6.

Can you please assist on resolving this issue?

Thanks
Reema Jain

**Comment by pietermarsman** [comment]
You probably have multiple versions of pdfminer (the original) and pdfminer.six installed. Make sure that only pdfminer.six is installed in your python environment.
