### ISSUE TITLE
converting to text outside of command line

### ISSUE THREAD

**Issue by cschwem2er** [pdfminer/pdfminer.six#93]
Hi there,

I'm currently trying to use pdfminer within a jupyter notebook to convert pdf files to text but fail miserably :/ I know that you provide the command line tool pdf2text.py, but isn't this also possible in another way? Let's say I use the example code you provided up to the following point:
````
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfpage import PDFPage
# Open a PDF document.
fp = open('sample.pdf', 'rb')
parser = PDFParser(fp)
document = PDFDocument(parser)
````
How could I create a text file out of this then? Is it somehow possible that you create a function for `pdf2text.py` functionality?

Thanks anyway for the package :)

**Comment by WhalenKaiser** [comment]
What's your operating system?

**Comment by methodds** [comment]
I use both linux and windows and could of course just access the shellwithin a jupyter notebook (which also works with the poppler pdftotext tool), but a function would be OS independent.

**Comment by ganeshtata** [comment]
@methodds  Have you taken a look at this - https://stackoverflow.com/questions/26494211/extracting-text-from-a-pdf-file-using-pdfminer-in-python ? The answer seems to contain code used for extracting text from PDFs.

**Comment by pietermarsman** [comment]
This is a minimal code example:

```python
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfparser import PDFParser

with open('sample1.pdf', 'rb') as in_file:
    with open('sample1.pdf', 'w') as out_file:
        parser = PDFParser(in_file)
        doc = PDFDocument(parser)
        rsrcmgr = PDFResourceManager()
        device = TextConverter(rsrcmgr, out_file, laparams=LAParams())
        interpreter = PDFPageInterpreter(rsrcmgr, device)
        for page in PDFPage.create_pages(doc):
            interpreter.process_page(page)
```

**Comment by pietermarsman** [comment]
Closing this because I am considering this question answered.

**Comment by cschwem2er** [comment]
Thanks for getting back to this old issue! Unfortunately, your code above raises a unicode error for [this example pdf](https://www.dropbox.com/s/ss5tmv4y5o7ldur/ajps_reviewer_2010.pdf?dl=1). I am running Python 3.6 and just installed the latest pdfminer.six version. Do you know how to solve this problem?

**Comment by cschwem2er** [comment]
Nevermind, the syntax listed in one of the answers for the stackoverflow question mentioned above seems to work:

```
import io

from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage


def convert_pdf_to_txt(path):
    rsrcmgr = PDFResourceManager()
    retstr = io.StringIO()
    codec = 'utf-8'
    laparams = LAParams()
    device = TextConverter(rsrcmgr, retstr, codec=codec, laparams=laparams)
    fp = open(path, 'rb')
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    password = ""
    maxpages = 0
    caching = True
    pagenos = set()

    for page in PDFPage.get_pages(fp, pagenos, maxpages=maxpages,
                                  password=password,
                                  caching=caching,
                                  check_extractable=True):
        interpreter.process_page(page)

    text = retstr.getvalue()

    fp.close()
    device.close()
    retstr.close()
    return text
```

**Comment by pietermarsman** [comment]
> Thanks for getting back to this old issue! Unfortunately, your code above raises a unicode error for [this example pdf](https://www.dropbox.com/s/ss5tmv4y5o7ldur/ajps_reviewer_2010.pdf?dl=1). I am running Python 3.6 and just installed the latest pdfminer.six version. Do you know how to solve this problem?

Hi @cschwem2er, happy to hear that you've found a way to solve your problem. I am also interested in replicated the `UnicodeError` because it's a good starting point for improving pdfminer.six. However, I can't replicate the error. Could you perhaps share the full error and stacktrace?
