### ISSUE TITLE
ModuleNotFoundError: No module named 'pdfminer'

### ISSUE THREAD

**Issue by st-little** [pdfminer/pdfminer.six#959]
I have installed `pdfminer.six` with the help of the [Extract text from a PDF using Python](https://pdfminersix.readthedocs.io/en/latest/tutorial/highlevel.html), but I get the following error

```bash
$ pipx install pdfminer.six
  installed package pdfminer-six 20231228, installed using Python 3.12.2
  These apps are now globally available
    - dumppdf.py
    - pdf2txt.py
done! ✨ 🌟 ✨
$ pdf2txt.py --version
pdfminer.six v20231228
$ python extract-text.py
Traceback (most recent call last):
  File "/workspaces/pdfminer-six/extract-text.py", line 2, in <module>
    from pdfminer.high_level import extract_text
ModuleNotFoundError: No module named 'pdfminer'
```

Is there a solution?

```python
# extract-text.py
from pdfminer.high_level import extract_text
text = extract_text('test.pdf')
print(text)
```

**Comment by EduardoNeville** [comment]
Have you tried running using the pipx command?
`pipx run extract-text.py`
Check the [github](https://github.com/pypa/pipx) documentation for better usage of pipx:
When running
`python extract-text.py`
you are running the file using your local python environment not the pipx environment you created.

**Comment by st-little** [comment]
Yes, I ran the pipx command. The result is as follows.

```bash
$ pipx run extract-text.py
Traceback (most recent call last):
  File "/workspaces/pdfminer-six/extract-text.py", line 2, in <module>
    from pdfminer.high_level import extract_text
ModuleNotFoundError: No module named 'pdfminer'
```

**Comment by pietermarsman** [comment]
I'm not an expert on pipx, but probably it installed pdfminer.six into a different python environment than you were expecting. 

You can try these commands to figure out what is happening:

```
which python
which pipx
python -V
