### ISSUE TITLE
Can you replace the text now

### ISSUE THREAD

**Issue by 2622594863** [pdfminer/pdfminer.six#962]
**Feature request**

Thanks for your suggestion on improving pdfminer.six. To helps us discuss and
implement this request, please make sure to include the following information:

- A description of the feature you would like to have
- If relevant, the context that you are in. What are you trying to achieve?
- I want to achieve the function of loading a pdf file, the contents of the inside to replace, and then save to a new file, may replace a few characters, I want to keep the style unchanged, only replace the characters, do not know now can achieve this function
- If possible, an example of what you want to achieve. Include the PDF that
  you are working on. Include the output that you would like to have.

**Comment by 2622594863** [comment]
Replace without changing the original layout

**Comment by pietermarsman** [comment]
pdfminer.six will never support changing the content of a PDF. It's purpose is to read the content and display it in various ways.
