### ISSUE TITLE
COPY+PASTE error installing via pip on Python 3.6

### ISSUE THREAD

**Issue by manel00** [pdfminer/pdfminer.six#99]
Command "/home/alumne/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ti4r7xo3/pycryptodome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gn51nvyh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ti4r7xo3/pycryptodome/

Thanks, sounds interesting this module, need to extract text from PDF 1.5 and PYPDF2 cannot do it

**Comment by pietermarsman** [comment]
Hi @manel00, 

I'm closing this issue because it is been inactive for a long time and I don't really understand the issue. Feel free to reopen it if this issue is still important to you.
